### ISSUE TITLE
[CTTT & SM3DW] Star Bloom

### ISSUE THREAD

**Issue by JOHN30011887** [slashiee/cemu_graphic_packs#103]
I tested out the new files for captain toad and iv noticed Episode 1 page 8 where particles are used still look bad

Im running at 4k, used graphic pack from here :)

![screenshot 4](https://user-images.githubusercontent.com/12979984/31349902-edabec08-ad1c-11e7-8a68-71d97364d458.png)

**Comment by Crementif** [comment]
Oh okay... this is gonna be a hassle as these look exactly like the SM3DW shaders I found yesterday, which I couldn't get fixed sadly. Might want to retry it, but I didn't play the full game with these shaders on so I couldn't find them. Thanks for noticing, will add it on my to-do list. @NAVras-Z Did you found some extra things I should account for when shader editing mips? Or you have any shader that has a correct implementation on it?

**Comment by NAVras-Z** [comment]
@Crementif well nothing new i guess, just need to look out for the  broken scaling mips and use passParameterSem to get the right texture size

**Comment by Crementif** [comment]
Ah okay. I'll be careful with the passParameterSem.

**Comment by Crementif** [comment]
Some information to confirm that they both have the same problem.
![Captain Toad: Treasure Tracker effect in Nsight](https://user-images.githubusercontent.com/26669564/31408779-f79d3ada-ae09-11e7-9a6d-a0e4f1116125.png)
![Super Mario 3D World](https://user-images.githubusercontent.com/26669564/31409257-851ede1c-ae0b-11e7-9712-1400d866f3af.png)
Super Mario 3D World uses 2 shaders to do this bloom with 2 passes.
* First pass by 5661793d88425685
* Second pass I'm not quite sure about
Captain Toad: Treasure Tracker uses 1 shader to do this bloom and thereby only uses 1 pass.
* First pass by 83f42767ee584d5a
* Yet to find a 2nd pass.

There's currently no fix for this, but I'll try to resolve this.

**Comment by JOHN30011887** [comment]
Thanks for looking into this, it looks confusing to me but thanks again :)

**Comment by Crementif** [comment]
NAVras reported  another one for cttt, 13d075473967e063

**Comment by NAVras-Z** [comment]
[cttt.zip](https://github.com/slashiee/cemu_graphic_packs/files/1375716/cttt.zip)
Found these both used in glowing points and star trails, the appear at corresponding events, but removing them in nsight doesn't make a change, could be texture read back someone mentioned before?

**Comment by Crementif** [comment]
Yes, it's really annoying to fix those in Nsight. There's some large
shaders that probably need to be edited, but CTTT and SM3DW use a lot of
this or rather like to keep the previous texture that got rendered.

**Comment by NAVras-Z** [comment]
![ps](https://user-images.githubusercontent.com/21133512/31493497-019e9cbc-af82-11e7-8070-0f8233981e01.png)
_dang_ vertex just return a bunch of 0/0.5/1, looks like the shift coordinates are from this, but I've no clue what those are

**Comment by Crementif** [comment]
https://github.com/slashiee/cemu_graphic_packs/commit/220d400ead9a3a41f2ae14260bb03faf446cb329 Fixed the most prevalent bloom again, now with vertex shaders. I might try and fix this one. Think it could be possible (atleast achievable) with vertex shaders.

**Comment by Crementif** [comment]
![Fixed glitter bloom](https://user-images.githubusercontent.com/26669564/33230506-136b924e-d1e5-11e7-8835-0e4af6d0c30a.png) (There's some broken bloom remaining in the image, but this is resolved in the final version from the commit)

This issue is fixed in commit so I'll be closing this issue. Feel free to test the new resolution pack and tell me if it's fixed.
https://github.com/slashiee/cemu_graphic_packs/commit/6fb42060aea676a0e36edef2939dccfd40d17388 .

Still need to fix Super Mario 3D World shaders, but I'll update this comment once I do that. Closing for now atleast.

**Comment by JOHN30011887** [comment]
Thanks so much for the fixes, works perfectly now, i really appreciate the hard work :)
