### ISSUE TITLE
XCX 0AA (AA removal) simply shows black screen for 3d renderspace (UI elements still visible)

### ISSUE THREAD

**Issue by manywelps** [slashiee/cemu_graphic_packs#112]
XCX 0AA (AA removal) simply shows black screen for 3d renderspace (UI elements still visible)

As of CEMU 1.10.0f.

7700k
win7x64
290x Driver 17.7.1

Edit: I modded the AA out of XCX and deleted my shader cache and it started working...?

**Comment by slashiee** [comment]
Well if it started working again, then no need to keep this issue open, right?
