### ISSUE TITLE
Title Mismatches

### ISSUE THREAD

**Issue by SniffleMan** [slashiee/cemu_graphic_packs#118]
The following enhancement packs have different names than the resolution packs:

- The Legend of Zelda: The Wind Waker HD
  - The Wind Waker HD - No Anti-Aliasing
  - The Wind Waker HD - Adjustable Bloom
  - The Wind Waker HD - Higher Quality Shadows

- The Legend of Zelda: Twilight Princess HD
  - Twilight Princess HD - No Anti-Aliasing
  - Twilight Princess HD - Adjustable Bloom
  - Twilight Princess HD - Higher Quality Shadows

- Super Smash Bros. for Wii U
  - Super Smash Bros. - Higher Quality Shadows

Also these enthusiast packs have different names than their quality pack counterparts:

- One Piece: Unlimited World Red
  - ONE PIECE Unlimited World Red - 5120x2280
  - ONE PIECE Unlimited World Red - 7680x4320
  - ONE PIECE Unlimited World Red - 10240x5760

**Comment by slashiee** [comment]
Forgot to rename the packs when transferring the main ones to a template format, I can fix tomorrow

**Comment by slashiee** [comment]
Quickly went on computer to fix most of the naming issues: will take care of one piece tomorrow

**Comment by slashiee** [comment]
One piece is fixed
