### ISSUE TITLE
[BotW] Strange issues with the sky and other object shadows

### ISSUE THREAD

**Issue by BSE97** [slashiee/cemu_graphic_packs#122]
Cemu version: 1.10.0f Specs: i5 4690, 16Gb DDR3, gtx 1070
Hi, I have a strange issue when I use a 1080p graphics pack. It seems that all the clouds and elements from the background are floating in the foreground and on the incorrect positions.
Here is a picture: https://imgur.com/QVRjMTL

**Comment by slashiee** [comment]
Update BotW version

**Comment by BSE97** [comment]
I have the 1.1.2 Version and can't find any other update that this.
I used Wii U Updater and MapleSeed2

**Comment by slashiee** [comment]
Piracy, no support from me.
