### ISSUE TITLE
[Multiple] Textures don't scale properly

### ISSUE THREAD

**Issue by slashiee** [slashiee/cemu_graphic_packs#126]
This happens with Pokkén Tournament's in-game graphics, Splatoon's player icons, Super Mario Maker's NSMBU mode, Color Splash's colorless spots and Yoshi's Woolly World.

![](https://cdn.discordapp.com/attachments/299321271039033344/388139538058575872/unknown.png)
![](https://cdn.discordapp.com/attachments/292733452590120961/372886148399366144/unknown.png)
![](https://cdn.discordapp.com/attachments/292733452590120961/388140992521437196/unknown.png)
![](https://cdn.discordapp.com/attachments/292733452590120961/388141979025932288/unknown.png)

**Comment by slashiee** [comment]
Pinned in #gfx_packs in the Cemu discord

![2017-12-10_15-49-57](https://user-images.githubusercontent.com/15317421/33811024-cbbfcd14-ddc1-11e7-9096-e0e959d48c54.png)

**Comment by Crementif** [comment]
Yoshi's Woolly World is also broken due to this I think, can't scale the 1280x720 without breaking the background.

**Comment by slashiee** [comment]
Majority of games fixed as of Cemu 1.11.3!
![image](https://user-images.githubusercontent.com/15317421/34341400-6b3d7352-e94b-11e7-93f3-6ed488184373.png)
![image](https://user-images.githubusercontent.com/15317421/34341427-3f10a8f2-e94c-11e7-8a72-d6ee31d913bd.png)

Color Splash is still broken.
![image](https://user-images.githubusercontent.com/15317421/34341419-ee14e17a-e94b-11e7-8eb2-70ea069b5eac.png)
