### ISSUE TITLE
[Mario Tennis] Texture rules not filtered for video's

### ISSUE THREAD

**Issue by Crementif** [slashiee/cemu_graphic_packs#129]
Issue reported by deejay87#6120 on discord. Not sure if it's actually a problem, can't check myself. He used cemuhook. On native resolution the game showed the videos. All his packs were up to date.

![image provided by deejay87#6120](https://cdn.discordapp.com/attachments/292733452590120961/375257066237067265/Capture.JPG)

It also doesn't seem like there's any tilemode filtering in there so that's likely to be the issue.

**Comment by slashiee** [comment]
Should be fixed 0ee7c55c32f5eceb69f52b9d8d7c3d7945b09718
