### ISSUE TITLE
[Mario Kart 8] hover skids

### ISSUE THREAD

**Issue by theboy181** [slashiee/cemu_graphic_packs#13]
I'm not sure what to call them but when the karts are in hover mode the skidmarks (while in 4k) look very displaced. It's like the skid textures are too low of a resolution for the 4k mod

**Comment by slashiee** [comment]
Is there any screenshot of the issue? I think this may just be part of the game itself.

**Comment by theboy181** [comment]
Forgot to mention it happens in 2P mode with 4K enabled. if you play in single player mode its fine. 

![capture](https://cloud.githubusercontent.com/assets/9299743/22096504/d8c0b060-ddd0-11e6-95eb-51c896870f41.PNG)

**Comment by theboy181** [comment]
Single Player
![capture](https://cloud.githubusercontent.com/assets/9299743/22096658/a5528176-ddd1-11e6-8ebb-f8891dfc1ff9.PNG)

**Comment by slashiee** [comment]
This could just be Nintendo optimizing the multiplayer modes. But I'll keep this issue open until it's confirmed.

**Comment by Darkemaste** [comment]
Alright I , a fix for this is included in my current PR.

**Comment by slashiee** [comment]
Fixed as of #16
