### ISSUE TITLE
Xenoblade Chronicles X 

### ISSUE THREAD

**Issue by getdls** [slashiee/cemu_graphic_packs#132]
On hold, waiting for  Cemu texture rewrite 1.4~1.5 to stabilize. If brightness and alignment are fixed, about half of the shaders will need to be removed/updated 

~~XCX stopped crashing in cemu, so~~ I got around to fixing some stuff.. and noted that there are still some other issues. 

http://compat.cemu.info/wiki/Xenoblade_Chronicles_X
- Crashes on cemu 1.11.5 -> upgrade to latest Cemu version, 1.12.1b works well as of now
- Purple garbled textures -> Later versions tend to work better but it's not fixed yet (1.12.1b pretty good)
- Grass/bushes missing since v 1.7.2 -> can't be fixed with graphic packs
- Audio mixing is off  -> can't be fixed with graphic packs

21:9 GUI fix issues
- Characters are squished on equip screen -> Due to same shaders scaling GUI -> Needs patch to be fixed
- Map screen touch area is off -> Due to same shaders scaling GUI -> Needs patch to be fixed
- Mini map is halved -> Due to same shaders scaling GUI -> Needs patch to be fixed

 overwriteRelativeLodBias setting is disabled by default in rules.txt, uncomment for sharper textures and shimmering

Cemuhook patches - 60 fps / AMD brightness / offline tag / 21_9 
- Separate thread, I don't want to mix none shader related issues https://github.com/slashiee/cemu_graphic_packs/issues/214

## To do 
- [ ] Over brightness, Nope, still broken. I'd hoped uf_remappedPS[0] could be used as differentiator between a day and night profile... fell apart once you reached main map area. 

- Improves the fix using the shadow map.https://github.com/slashiee/cemu_graphic_packs/commit/5039752b451701793b5ecb652d5244f0ec566f5c  
 - Adjusted to better balance with new blur, https://github.com/slashiee/cemu_graphic_packs/commit/9eb95d1bf549c9f4ca3566e69359c82b710f32ef 
 - Improve - Brightness truncation banding,   increase depth + dithering https://github.com/slashiee/cemu_graphic_packs/commit/3eb451a13cbf580221397d1ef5148ae0b6c20005, https://github.com/slashiee/cemu_graphic_packs/commit/6331abdc50907d27e922c3ec78060cbb1718790a
 - Raises black level to compensate drop in exposure, balances with gamma. Slightly lowers reflection to compensate gamma contrast peak brightness. ie darkest part is slightly brighter, middle part is more contrasty. https://github.com/slashiee/cemu_graphic_packs/commit/6191ba122377e800c76622fbfcac4872848c82b1

```
//uf_remappedVS[0].x == {1065353216, 1065353216} //metal back 
//uf_remappedPS[0] {1064030938, 1065353216, 1064304640, 1023410176} //  indoors

//uf_remappedVS[0].x == {1065353216, 1065353216} //dayligh plain
//uf_remappedPS[0] {1075838976, 10653532216, 1064304640, 1023410176} // daylight plain

//uf_remappedVS[0].x == {1065353216, 1065353216} //night forest
//uf_remappedPS[0] {1075838976, 10653532216, 1064304640, 1023410176} // night forest 
```
 
- [ ] Full two pass vertical + Horizontal scaling  -  current commit is a compromise, pre-blurred, half scale. 
Preferably solution should also scale up focus depth, and that isn't fixed. Runs into alignment issues and over blurring 
- [ ] Add separate Y shader scaling for ultra wide (21:9) - All shaders currently scale x and y to the same value.. difference is minor, but will eventually be fixed
- [x] Floaty car light trails. Usual scaling fix doesn't work, possible integer rounding issue ? Wohoo fixed with https://github.com/slashiee/cemu_graphic_packs/commit/9a9362e0c3d58885970120578f75a04915af8251
- [x] Buffer alignment is one pixel off leading to leaking light around characters, character bleeding into depth etc. Various causes usually a combination of alpha blending is low-res, shadow is another res and stencil  ("fake DOF").  Some can't be fixed, some can be fixed but needs to scale everything to main resolution, some fixes break other areas etc. Looking into scaling half res to full res, but this in turn has a lot of unwanted side effects on every other buffer. 
- Initial fix/commit of  new alignment https://github.com/slashiee/cemu_graphic_packs/commit/8fa52937c9873ad5e2c17afa6ab8ab6e1bd9756f 
 - And done, rounding up internal res x1.333 smooths out transitions, helps a bit with shimmering and masks remaining edge bleeding https://github.com/slashiee/cemu_graphic_packs/commit/9a9362e0c3d58885970120578f75a04915af8251

- [x] Bug other ppl that Cemu crashes in nsight when loading  a game after windows fall update, including updated nsight and nvida gfx drivers - Works in latest update, but unstable
- [x] Scale controler/map view in main pack

- [x] Shader used for (cross)fade causes brightness jumps since it still uses original shader exposure https://github.com/slashiee/cemu_graphic_packs/commit/596e66f7c8c458a307bcfd7453e56a9fcce85a3e
- [x]  1x1 is used for cut scene shadows,  not related to over brightness. Closing. 

- [x] Shadow acne fix, Z tweak, there are probably more locations. Just don't overdo it and get floating shadows. Go back later and see if a proper fix can be done instead of magic z values..
Mostly resolved with shadowscaling. https://github.com/slashiee/cemu_graphic_packs/commit/5039752b451701793b5ecb652d5244f0ec566f5c , https://github.com/slashiee/cemu_graphic_packs/commit/5dd2f2aed53289db1608dbd75ca6d18b4fc2c934

- [x]  Initial blend/blur layer changed to scale. This in turn fixes the usual pixelated bloom and dof

- [x] Fixing all DOF errors removes too much blur, go back later and add optional blur to compensate https://github.com/slashiee/cemu_graphic_packs/issues/132#issuecomment-343700188
https://github.com/slashiee/cemu_graphic_packs/commit/61bf0415c705bf460246861a0369853c53462938 
- [x] Blur fix still need to fix separate scaling 1.5 -> 3.5, Fixed https://github.com/slashiee/cemu_graphic_packs/commit/9b9bd602cd3dad63fcb46246247bb55f737e78ba 
. 

- [x] Alignment of DOF blur is off when blending horizontal/vertical.. 
A perfect fix would be preferable but https://github.com/slashiee/cemu_graphic_packs/commit/d226a06fa175f9ba62fc995363e0270cb21db20c, and https://github.com/slashiee/cemu_graphic_packs/commit/c1d361fa4dfa6df6aaca36880d35ede0dffa8684 are good enough, no more floating lights in cut-scenes. 
- [x] Count down movie when opening the stasis pod is broken again, this was a rule fix, but I can't remember what now. 
- [x] Native AA scaling to res - Resolved, also fixes separate AA pass for skell view https://github.com/slashiee/cemu_graphic_packs/commit/47aa3c10b21d9ec8728052286acb79b4e32b0a60 and sharpen pass https://github.com/slashiee/cemu_graphic_packs/commit/696d9f0d07385c927dbf49ae6db9dfd5ea4b4a2b

- [x] Aa noise was misaligned and unscaled edge detection 
- [x] Shadows changed to scale, ie "pixelated" shadows blend fix https://github.com/slashiee/cemu_graphic_packs/commit/5ad576f57d97387a94d19ff1f6fe1464a56c2575 https://github.com/slashiee/cemu_graphic_packs/commit/f7ef21ef548e57f7d2471137b0fa6ee4779c2ffc
- [x] Cockpit view fixed https://github.com/slashiee/cemu_graphic_packs/commit/f42fd6b791c52f481b15dcf0f25d634c043438d6  

- [x]  AO scaling -  can scale but character range check is off, 
Mostly resolved https://github.com/slashiee/cemu_graphic_packs/commit/5f6725df662e3bf1493be93cf7a00f16c4d8b685 , https://github.com/slashiee/cemu_graphic_packs/commit/5dd2f2aed53289db1608dbd75ca6d18b4fc2c934

- [x] 21:9 Gui    https://github.com/slashiee/cemu_graphic_packs/commit/b521212b3fb83c51a33f607b9390d3fdee6b2073 , https://github.com/slashiee/cemu_graphic_packs/commit/4bd4fc40d4aa3a22063f0e765f24f9ea55f189fe , https://github.com/slashiee/cemu_graphic_packs/commit/c9305b4b9d3a0189fe8795b41725c4afbb35f820, https://github.com/slashiee/cemu_graphic_packs/commit/3eb451a13cbf580221397d1ef5148ae0b6c20005, https://github.com/slashiee/cemu_graphic_packs/commit/52d89f4aa3e978c8b875b0fc9cc0ad42962ea841 etc.. 
- [x] Motionblur scaling https://github.com/slashiee/cemu_graphic_packs/commit/12f2c6c8fe15d489228f71f661228150eb79f325

![xcxfixes](https://user-images.githubusercontent.com/25286924/32526332-097c6156-c429-11e7-95cb-676e651a10b7.png)

 #153

**Comment by slashiee** [comment]
i looked into the zip and converted it to the build script format, hopefully i didn't mess anything up
[XenobladeX.zip](https://github.com/slashiee/cemu_graphic_packs/files/1452324/XenobladeX.zip)

**Comment by getdls** [comment]
Cheers Slashie

Stasis and B&W videos fixed, 


```
[TextureRedefine] # game rendering resolution. 	#Change this value
width =	1280
height = 720
tileModesExcluded = 0x001
#formatsExcluded = 0x001 #FMV starfield	 
...
[TextureRedefine] # Party/Bestiary/Menu Screens. FMV buffer, custom proportio integer scaling 	
width =	1024
height = 720
formatsExcluded = 0x001 #stasis fix. (movie)	
```

**Comment by getdls** [comment]
Well that was obvious now that I stop and think about it..

![failbokeh](https://user-images.githubusercontent.com/25286924/32694269-5562b17c-c73c-11e7-8d79-0cf4425e807d.png)

**Comment by getdls** [comment]
uh. oh...  um.. looks like I'm commiting to an old branch!.. just ignore my ramblings while I figure this out..

**Comment by getdls** [comment]
21:9 Gui and  some minor in-game fixes.  Note, this is not the general shader scaling fix, just the GUI https://github.com/slashiee/cemu_graphic_packs/commit/b521212b3fb83c51a33f607b9390d3fdee6b2073

**Comment by Crementif** [comment]
I just want to mention (besides the file itself where you've commented this) that this does increase the amount of passes, which could decrease performance FYI. Probably should make that clear.

**Comment by zerocold1981** [comment]
![screenshot](https://user-images.githubusercontent.com/10199092/32845096-f8dfce52-ca34-11e7-9594-1a30f65183c2.png)
on AMD polaris cards it's impossible to play yet ...

**Comment by getdls** [comment]
Can you test the three versions below? 

Gutted should tell us if its broken before the grading shader
Grading only should tell us if exposure part is wrong
Halved should tell us if its any use going after the exposure at all. 

[OnlyGrade_XenobladeX_1440p.zip](https://github.com/slashiee/cemu_graphic_packs/files/1475532/OnlyGrade_XenobladeX_1440p.zip)
[Gutted_XenobladeX_1440p.zip](https://github.com/slashiee/cemu_graphic_packs/files/1475533/Gutted_XenobladeX_1440p.zip)
[Halved_Exp_XenobladeX_1440p.zip](https://github.com/slashiee/cemu_graphic_packs/files/1475534/Halved_Exp_XenobladeX_1440p.zip)

**Comment by zerocold1981** [comment]
OnlyGrade_XenobladeX_DAY / NIGHT
![onlygrade_xenobladex_day](https://user-images.githubusercontent.com/10199092/32875800-df51129a-caaa-11e7-9c28-0fd577e08263.jpg)
![onlygrade_xenobladex_night](https://user-images.githubusercontent.com/10199092/32875804-e228c29c-caaa-11e7-8aa0-9ce0b208cf92.jpg)
Gutted_XenobladeX_1440_Black screen all time
![gutted_xenobladex](https://user-images.githubusercontent.com/10199092/32875825-fefd9898-caaa-11e7-82c2-b353d6f3ab80.jpg)
Halved_Exp_XenobladeX_DAY / NIGHT
![halved_exp_xenobladex_day](https://user-images.githubusercontent.com/10199092/32875843-1259c7fe-caab-11e7-90b6-e3741b43ab8b.jpg)
![halved_exp_xenobladex_night](https://user-images.githubusercontent.com/10199092/32875846-14dfffac-caab-11e7-8b39-c9a95a5f6c5b.jpg)

thanks, the third option allows me to play)

**Comment by getdls** [comment]
@zerocold1981  I've added a tweak where shadows contribute less to the overall scene exposure. It truncates more of daylight and less of night. Could you try this one, and maybe tweak the value up and down a bit?

`const float shadowExposure = 0.75; // tweakable value in the header of the shader 0.1 ->1.0 less exposure. 
`
[XenobladeX_HighResShadows.zip](https://github.com/slashiee/cemu_graphic_packs/files/1482307/XenobladeX_HighResShadows.zip)

**Comment by zerocold1981** [comment]
unfortunately there is no effect. Even with a value of 2.0. I just did not see any changes. Probably does not work on polaris

**Comment by getdls** [comment]
Values below 1.0 (0.3 example) should have decreased brightness. Anything above 1.0 should have made the problem even worse...

**Comment by zerocold1981** [comment]
one sec.

**Comment by zerocold1981** [comment]
0.10 + Halved_Exp_XenobladeX_DAY
![screenshot](https://user-images.githubusercontent.com/10199092/32951109-c97d7fd4-cbb9-11e7-9b8a-8223ce58bd13.png)

**Comment by getdls** [comment]
Alright, so it does work.. I'd stick with values around 0.4 to 0.6 or you won't have any normal shadows left... 
This one contains the shadow tweak at .5 and "brigntess" fix with similar settings. 
in File 3cc7e98f78c258b4_00000000000003ca_ps.txt

```
const float preExposure = 0.55; // overall brigtness, around .4 for AMD
const float bloomExposure = 0.3; // How much we blend the other parts of the shaders
const float gammaPostExposure = 0.9; // compensate pre exposure, but loss of contrast when positive. 

```

[XenobladeX_1440p.zip](https://github.com/slashiee/cemu_graphic_packs/files/1482579/XenobladeX_1440p.zip)

**Comment by zerocold1981** [comment]
DAY, 
very good
![screenshot](https://user-images.githubusercontent.com/10199092/32958572-eeb29e36-cbcf-11e7-94f0-3038315c019b.png)
NIGHT, 
very good!!!
![screenshot](https://user-images.githubusercontent.com/10199092/32958717-5e27acf2-cbd0-11e7-9579-8acd92d594fe.png)


Thank you very much friend, this is a very big job for me !!!


before that I used the schedule from here: https://www.reddit.com/r/cemu/comments/5uv91b/massive_graphic_pack_for_xcx_13_gfx_settings_5/
He was the best, but now outdated.
Thanks again, I really appreciate it.

**Comment by getdls** [comment]
I'm glad it worked.
If you find a good brightness / shadow setting after some tweaking, please post the values. As I haven't got an AMD card, its all guesswork for me.

**Comment by Crementif** [comment]
Gamepad isn't scaled yet (according to **@Hdoge#6924**) for some reason like all/most other packs. This causes the probe menu on the gamepad to be hidden. I can't test this myself, but I'm pretty sure it should be enabled by default. Here's the fix (thanks **@Snorgrind#3134**) if you want to include this.
```
[TextureRedefine] # gamepad
width = 854
height = 480
overwriteWidth = <?=round($scaleFactorX*854)?>
overwriteHeight = <?=round($scaleFactorY*480)?>
```

**Comment by getdls** [comment]
Thanks,  should be fixed in the next commit.
Reminder to self, check 21:9 scaling before sync

**Comment by getdls** [comment]
I guess that subtraction part was there for a reason... should probably fix that before committing.  

![moarbloooom](https://user-images.githubusercontent.com/25286924/33637257-26731b6c-da20-11e7-956e-dc9684137b77.png)

**Comment by getdls** [comment]
That's more like it :)
![awalkinthepark](https://user-images.githubusercontent.com/25286924/34084038-34bd0d64-e37a-11e7-898a-ea7f7363936e.png)

**Comment by jhonyndx** [comment]
Hey guys, i play on 21:9 and its amazing with the current 2d and GUI fix, but the only thing that interferes in play, is that the gamepad scales with the main game window, thes no way we can just ignore the effects os GUI fiz on gamepad screen?

**Comment by Crementif** [comment]
Hey,

Could you elaborate your problem please, it's not very clear. Including
screenshots with some notes on it definitely helps us understand.

**Comment by slashiee** [comment]
i think he's talking about the gamepad being stretched

**Comment by getdls** [comment]
The gamepad is scaled to 21:9 but the clickable area is still 16:9.. ie corner clicks are off towards the centre. 
I'll check but it probably needs to be in the 21:9 patch, not the VS

Also noted some issues with car lights and mist, those I can fix.

**Comment by jhonyndx** [comment]
Oh sorry if i wasn't clear, but i think you figured out @getdls, if you click the red area 1 in the print below, it will hit the blue area 2, it will be inverted in the other side ( area 3 and 4) and will be okay in the center, so the click areas are aligned with the resolution 21:9 but the image itself isn't.

![capturar](https://user-images.githubusercontent.com/34873477/34381064-40fb363a-eaed-11e7-8b26-bca4658d4d5c.JPG)

**Comment by getdls** [comment]
Fixed some more 21:9 stuff, https://github.com/slashiee/cemu_graphic_packs/commit/4bd4fc40d4aa3a22063f0e765f24f9ea55f189fe, but I can't do anything about the touch area.  

- Map area uses the same shaders as all the other text and menu boxes. 
- Touch sensor area is set by cemu, not by shaders

**Comment by Crementif** [comment]
Quoting Rajkosto here, but he said that the touch area is caused by using
wrong deprojection matrix. Not really sure if it's any different from other
games.

**Comment by jhonyndx** [comment]
Understood, since the touch is for fast travel, its easy to get used, thanks for everything you all have done, playing on ultrawide is awesome.

**Comment by jhonyndx** [comment]
Since i have no problems with menus or texts scaled with 21:9, i tried to find what is making gamepad screen like that, and is this guy down here:

![capturar3](https://user-images.githubusercontent.com/34873477/34427757-c7334ae0-ec2c-11e7-95ce-ff370e8b534e.PNG)

Disabling those commands in the screen above, i keep the menus, dialog boxes and texts scaled to 21:9 (not so ugly) and keep the tower count, party and npc's skells lights, gamepad screen, transporter flare effects, and other things working properly, its a nice price to pay.  Dunno what to say about that shooting flash in the gamescreen below.

![capturar4](https://user-images.githubusercontent.com/34873477/34427874-ede2e17c-ec2d-11e7-846c-23b9eee288de.PNG)

**Comment by getdls** [comment]
That's a good idea, how about attaching the changes in a zip file? 
Just edit your message and do a drag n drop.

**Comment by Xalphenos** [comment]
I could maybe fix that effect.  There was an aspect calculation I left unmodified.  I couldn't find any difference that it made but I was still early in the game and didn't have much use for the gamepad screen.  But it seems recent packs don't scale the gamepad like they used to?

**Comment by getdls** [comment]
Xalphenos, that would be great. Any chance you could take a stab at Wind waker as well? 
Same issue...

**Comment by Xalphenos** [comment]
What version of the graphics pack do I need to not stretch the gamepad screen back out?  And yeah I could look into WW as well.  That one may be odd.  I remember the aspect ratio wasn't calculated in that game it was just there as a rodata constant.  But yeah I'll look into it.

**Comment by getdls** [comment]
Latest commit graphicPacks_2-575, any 219 . (XenobladeX_2880p219)

**Comment by Xalphenos** [comment]
Don't know what I may be missing but gamepad is stretched for me.  Not pillarboxed like the previous pics.  Does the scaling not work on amd gpu?  

Some games calculate aspects and some don't.

**Comment by getdls** [comment]
*checking*

**Comment by Xalphenos** [comment]
Ah I see now.  I should have noticed that folder before I guess.

**Comment by getdls** [comment]
Considering I did the commit.. that makes us two ;)
It's like you get a brain reset when you switch between projects..

**Comment by getdls** [comment]
Since the build PHP rule drives me nutty I bashed together a log.txt  to rule converter 
[rulesGen.zip](https://github.com/slashiee/cemu_graphic_packs/files/1649262/rulesGen.zip)

Usage:
`>rulesGen  |  rulesGen <multiple> `


rulesGen 3.75 Looks for log.txt in local folder and generates rules.txt with 3.75x scaling and gitRules.txt with php tags

No error handling what-so-ever. if log.txt is missing or locked, program  will just barf.. and it probably needs updated .net libraries.

**Comment by Crementif** [comment]
Sounds useful! But what does the log.txt contain exactly? Does it work like
that Cemu Viewport Finder program which used Cemu's logging feature?

**Comment by getdls** [comment]
The same approach, scans log for GX2SetScissor and builds a rule file from last two positions 
[00:44:46] GX2SetScissor(0, 0, 320, 176)
If they match, rules are commented out with a #possible texture note

**Comment by getdls** [comment]
New "brightness" pre-set https://github.com/slashiee/cemu_graphic_packs/commit/4fa595b430054b406f585ec9a2de4a73066f0e52 , opening scene is still awesome :)

![xcx1](https://user-images.githubusercontent.com/25286924/35236620-3c3423c6-ffa8-11e7-96a6-f301aff52de7.png)

![xcx3](https://user-images.githubusercontent.com/25286924/35236641-4ca236bc-ffa8-11e7-88c9-eed7677040a4.png)

**Comment by JamieeLee** [comment]
well hello there beautiful , there it starting to look like sexy goodness.

**Comment by getdls** [comment]
@JamieeLee XCX clarity, what about sticking it in the AA shader like the old BOTW version? 

Combine it with exposure fix https://github.com/slashiee/cemu_graphic_packs/commit/4fa595b430054b406f585ec9a2de4a73066f0e52 but set it to netutral?  [0.55 pre ex, 1.05 post, all contrasty settings to 1 or 0]

The pack below has higher priority than both AA fix and brightness fix. 
[Xenoblade-Clarity.zip](https://github.com/slashiee/cemu_graphic_packs/files/1679761/Xenoblade-Clarity.zip)

**Comment by getdls** [comment]
I’ve tested some more presets in the AA shader and since then and didn’t like the results. It always ends up too dark, or can’t restore any overbloom. Clarity probably needs the brightness shader  for some of the effects.

Sharpen and similar works as expected, others probably not

**Comment by getdls** [comment]
RulesGen v1.5 [rulesGenv1_5.zip](https://github.com/slashiee/cemu_graphic_packs/files/1712180/rulesGenv1_5.zip)
Now checks for formats in \dump\shaders \dump\textures matching texture format to rules.txt viewports

If shaders/textures folders are empty functionality is the same as previous version

*Don't forget clear shader//textre dump when switching between games or the wrong formats will be matched to the viewport rules*

**Comment by getdls** [comment]
Close and commit still isn't comment...

**Comment by JamieeLee** [comment]
@getdls Hey for the exposure issue could we try something like this . 
#define SAMPLE_COUNT 9
 
static unsigned int Pixels[SAMPLE_COUNT][2] =
{	
	iWidth*0.50, iHeight*0.50,
 
	iWidth*0.25, iHeight*0.50,
	iWidth*0.75, iHeight*0.50,
	iWidth*0.50, iHeight*0.25,
	iWidth*0.50, iHeight*0.75,
 
	iWidth*0.25, iHeight*0.25,
	iWidth*0.25, iHeight*0.75,
	iWidth*0.75, iHeight*0.25,
	iWidth*0.75, iHeight*0.75
};
 
Vector3D kAveragedSamples;
unsigned char Samples[SAMPLE_COUNT][4];
for( unsigned int i = 0; i < SAMPLE_COUNT; i++ )
{
	glReadPixels( Pixels[i][0], Pixels[i][1], 1, 1, GL_RGBA, GL_UNSIGNED_BYTE, &amp;Samples[i][0] );
	kAveragedSamples += ( Vector3D(Samples[i][0], Samples[i][1], Samples[i][2])/255.0f )/SAMPLE_COUNT;
}
 
AverageBrightness = max( max(kAveragedSamples.x, kAveragedSamples.y), kAveragedSamples.z );
 
fExposure = 0.5/AverageBrightness;
fExposure = fPreviousExposure+( fExposure-fPreviousExposure )*0.02;
 
fPreviousExposure = fExposure;

or  at the end .
TargetExposure = 0.5 / Average_Brightness;
Exposure = Exposure + (TargetExposure - Exposure) * 0.1;

**Comment by getdls** [comment]
Havn't got access to a gpu, but without weights remembering prev scenes (ie not a shader) won't this flash/strobe between over dark and light every time you pan and sample points goes from a shadow to sunlight?

**Comment by JamieeLee** [comment]
prob will but we may be able to make some ghetto adaption to it thats kinda shader faked.   I may play with it.  I have not loaded xcx in a bit to test your latest stuff sorry been busy.

**Comment by getdls** [comment]
No worries, family's always comes first.  Especially for something that for all we know Exzap may fix next month

**Comment by JamieeLee** [comment]
Amen and so true to that getdls

**Comment by getdls** [comment]
If NLA/white whale has crash landed, shouldn't she be a little bit more worn down and dirty? 


![nladirty2](https://user-images.githubusercontent.com/25286924/37565624-e47c6b7c-2aac-11e8-804c-0de1e76edc12.png)

**Comment by getdls** [comment]
## Pre-release PR shot vs Cemu, can we match it with Cemu? 

About a year ago I found out about Cemu.. the PR shot of XCX was one of the things that got me into tweaking stuff.. So as a one year anniversary special  *Pre-release PR shot vs Cemu, can we match it with Cemu?*

*clickbait title, roll Youtube 1 minute intro, click below to subscribe*

_In game shot_

![rawbeach2](https://user-images.githubusercontent.com/25286924/38167619-705e0458-3538-11e8-8709-9478a69d8f21.png)

_Pre-release_ 

![refxx20](https://user-images.githubusercontent.com/25286924/38167630-8e4969da-3538-11e8-9098-7ab0357493af.png)

So can we?? No, at least not with just graphic packs, but we can get pretty close and even improve on some areas. *click bait remorse, why did I even read this far?!*

### What can’t be done with graphics packs: 

__FOV__
The PR shot uses a narrower FOV and is is taken from further away that what is possible during game-play.. A rough approximation would be that the in game uses  35mm lens wile PR shot is a 50mm. 

__Higher LOD and DOF__ 
See the cliff side above the purple bunny creature? PR shot shows trees and blurry DOF, the DOF doesn’t affect the clouds. 

__Volumetric fog__
The fog around the waterfall is just two flat layers in-game. The PR shot looks like its volumetric, or at least uses a bunch of more samples

### Things Cemu already does better

__AA__
PR shot uses in-game AA. With cemu we can brute force SSAA

__Texture filtering__
Nicer texture filtering, the beach is an obvious example

__Colour / layer mixing__
Less banding - Higher color precision when mixing, the sky box 

__Shadow resolution__
Your GPU is the limit


*Happy Easter folks* :)

**Comment by Crementif** [comment]
Lovely write-up on what you've been doing with your commits for people that don't completely understand what has been changed. Thanks for all your work (and the other awesome folks working on this game), I'll definitely be doing a playthrough.

And happy easter to y'all too!

**Comment by getdls** [comment]
*Gaaah Kill it with fire!*
![gaaah](https://user-images.githubusercontent.com/25286924/39401319-51df5c28-4b42-11e8-90a0-3b7727ef7db7.png)

**Comment by getdls** [comment]
Closing, 1.4.x gets a separate thread if needed. 
1.4
Purple texture is fixed
Crashes are (afaik) fixed

Over brightness is still broken
Foliage is still broken
Distant texture is still occasionally black/corrupted (looks like squares)
AA still broken
