### ISSUE TITLE
BreathOfTheWild_CleanCameraRune removes text from map

### ISSUE THREAD

**Issue by lucasaxm** [slashiee/cemu_graphic_packs#135]
This is what it looks like when it's activated: 

![Screenshot](https://i.gyazo.com/45bf0d91afb21c9f22cc7f5f81ad52ae.png)

I got it from [this reddit thread](https://www.reddit.com/r/CemuPiracy/comments/7c7xdh/botw_map_language_bug/?st=ja1s4bvx&sh=d8e2a14a), but I had the same problem.

I saw that there are multiple presets but I'm not sure how to change between them. I got this issue with the standard configuration, just pasting on graphicPacks and activating it.

**Comment by slashiee** [comment]
Linking to the piracy subreddit? No thanks.
