### ISSUE TITLE
Breath of the Wild

### ISSUE THREAD

**Issue by slashiee** [slashiee/cemu_graphic_packs#137]
Main:
* In certain cinematics the depth of field is completely black when format 0x816 is excluded (320x180)
* Bloom becomes all pixelated and randomly disappears when format 0x816 is upscaled (320x180) 
* So called "red filter" missing in certain areas (320x180) 
* Fix shadow upscaling
* Update packs to support v1.4.0 (DLC 2 update)

Optional:
* Fix the teleport animation (Cemu 1.11.2 fixed it)
- [x] Figure out how to fix AMD circle lights (Nesquick found the file... now we need someone with AMD to fix)
- [x] Fix tiling issue, since apparently a NVIDIA Inspector setting edit doesn't fix it completely (shader)
* Fix the majority of the ~~Z-fighting~~, if possible ([Cemu issue](https://github.com/slashiee/cemu_graphic_packs/issues/38#issuecomment-337920676))

Large Old Thread (closed due to being too long) which has lots of useful information to learn from: https://github.com/slashiee/cemu_graphic_packs/issues/38

**Before reporting any graphical issues, please check the BotW specific GFX FAQ from this repository: [Breath of the Wild FAQ](https://slashiee.github.io/cemu_graphic_packs/botw)**

**Comment by Darth-Cthoras** [comment]
Can confirm light circle AMD issue fixed as of the 407 release of graphic pack on AMD RX 480 in 1.3.3. No longer a problem, as seen in Gerudo Village which was full of light circles up until the 407 release with its Light Circle fix.

**Comment by vacodoceo** [comment]
Any ideas or fix for this? https://imgur.com/a/fY63v

Im running it with the latest grapic packs and cemu 1.11.1, on a rx 470

**Comment by Darth-Cthoras** [comment]
@vacodoceo What precisely is the issue? I'm not seeing anything wrong here.

**Comment by vacodoceo** [comment]
Oh, i didnt know that. 

Thanks

**Comment by Darth-Cthoras** [comment]
@vacodoceo In the future, you can find fixes for some issues here: https://slashiee.github.io/cemu_graphic_packs/botw

**Comment by SeRoM** [comment]
light / reflection problem visible only from the vah ruta dungeon.
The behavior is the same with fire / ice weapons.
I have the first suspense RefExtra, but I see the fault activated or not.
Do you have an idea ?

Ps: It's huge how RefExtra improves the visual. I did not realize it ... Thank you very much for your work!

![desktop screenshot 2017 12 11 - 20 45 37 86](https://user-images.githubusercontent.com/7047226/33857227-1e53fa96-decb-11e7-8c58-ab33ce8828bf.png)
![desktop screenshot 2017 12 11 - 20 45 51 34](https://user-images.githubusercontent.com/7047226/33857228-1e719696-decb-11e7-8da8-47cdba7ad674.png)
![cemu screenshot 2017 12 11 - 20 45 59 49](https://user-images.githubusercontent.com/7047226/33857248-2e739e4a-decb-11e7-935c-1bd4ab6d722a.png)

**Comment by DaRkL3AD3R** [comment]
Any word on what's currently broken with 1.4.0 still? It seems resolution pack is solid, but Contrasty is still outdated.

**Comment by Darth-Cthoras** [comment]
For the record, AMD Light Circle needs an update to 1.4.0 - Cypher technically made one, but it's not really fit for public use as it's very imperfect and buggy.

**Comment by mindtrip11** [comment]
any fix for something like this?  used all graphic mods. nothing worked. its version 1.4.0 while 1.3.3 was working great...update drivers also. 
https://imgur.com/a/wDDlg
specs.
Processor: Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (4 CPUs), ~3.6GHz
Memory: 16384MB RAM
Available OS Memory: 16368MB RAM
Page File: 14651MB used, 4659MB available
DirectX Version: DirectX 12
Chip type: GeForce GTX 480
Display Memory: 9671 MB
Dedicated Memory: 1488 MB
Shared Memory: 8183 MB

**Comment by Crementif** [comment]
That GPU looks quite old, not sure if it has the latest OpenGL drivers. Could you check the log.txt from your Cemu folder and tell us what OpenGL version it's running at. And are you sure this happens on native resolution, because if it does, it wouldn't be a graphic pack issue per se.

**Comment by sil3ntkilr** [comment]
I have this block of shadow following me around when using 1080p graphics pack. I have tried using amd shadow fix and amd lights circle fix but still the same. Can any one help me please?
Specs:
i5 2500k, amd 7870, cemu 1.11.2, zelda 1.4.0 with ballad dlc.
![shadow glitch](https://user-images.githubusercontent.com/12911737/34072669-811f9ba6-e283-11e7-8502-f2d64fc43059.jpg)

**Comment by Mr-Dexterous** [comment]
Having issues with teleporting and with the monks of the shrines. Sometimes some black squares apperar suddently when teleporting or when I see a monk in the shrine and they start like moving all around. I haven't seen that issue on other textures.
Actually I'm using: 
- BOTW v176 (All the DLCs)
- CEMU 1.11.2
- Clarity GFX for 1.4.0
-FPS++
-NVIDIA explosion smoke
-1920x1080

Specs:
-GTX 1070
-Intel i7 4790k @4 GHz 
-16 GB RAM 2400 mhz DDR3

**Comment by NAVras-Z** [comment]
[99b917d7030d3c58_0000000000001e49_ps.txt](https://github.com/slashiee/cemu_graphic_packs/files/1618949/99b917d7030d3c58_0000000000001e49_ps.txt)
heatwave avoid mip by changing bias in line 88
so heatwave won't have artifact when half-res is upscaled
waving effect is there however blur is gone, 'cause it's not using a mip maybe?

**Comment by NAVras-Z** [comment]
Found two textures(tex0 minor, tex1 blocky) causing blocky lava being fetch and update like 5 times using 6f6f6e7b9aae57af.
Added a "barrier();" before texture() or before everything, blocking is gone, but now I get rainbow lava.
![dang](https://user-images.githubusercontent.com/21133512/34875847-ed591d40-f7d9-11e7-9900-0678850d71b5.jpg)

**Comment by slashiee** [comment]
At this point it seems like most issues are fixed... Finally.
