### ISSUE TITLE
BOTW Depth of field effect in combat missing in higher res packs.

### ISSUE THREAD

**Issue by RedEchoes** [slashiee/cemu_graphic_packs#139]
Using the 720p pack during combat renders the depth of field almost exactly like on the Wii U. Why is this not the case with higher res pack. The 2160p pack gives me about 10% of how the DoF should look.

Issue is on all res packs except 720p.

**Comment by alexkiri** [comment]
This is a known issue, and  the only workaround will impact performance. To put this simply, the blur for the DoF effect is calculated in a single shader, in a single pass, and there is no way to scale it with resolution increase without affecting performance. The same issue can be seen for the camera rune DoF effect.

**Comment by RedEchoes** [comment]
Could you still tell me what values I would need to change? I would appreciate it.

**Comment by alexkiri** [comment]
On the other hand, this issue was fixed some time ago, but the fix was removed because of the fps drop. An alternate solution was implemented. This solution removed the grid artifacts on dof effects, but it had this side effect. I can get you the old (performance heavy) dof shaders, but I'll have to do some edits to make them work with the current solution.

**Comment by alexkiri** [comment]
It's not a simple value to change. Unless you want to remove the blur fix entirely, and revert to the grid blur issue.

**Comment by RedEchoes** [comment]
I'd love to test it! Thank you very much!

**Comment by alexkiri** [comment]
[cb0e6e8cbec4502a_0000000000000079_ps.txt](https://github.com/slashiee/cemu_graphic_packs/files/1525945/cb0e6e8cbec4502a_0000000000000079_ps.txt)
You can add this shader to any of your resolution packs. Also, edit it to adjust the radius.
![clipboard01](https://user-images.githubusercontent.com/6061770/33539532-94cd54da-d8cf-11e7-9494-91c3a71b4848.png)

**Comment by RedEchoes** [comment]
I'll test it tomorrow. Thanks.

**Comment by RedEchoes** [comment]
Ok so there's no preformance loss whatsoever but...

![cemu_2017-12-04_14-06-49-55 1](https://user-images.githubusercontent.com/34226871/33571003-a66b64d4-d8fc-11e7-8497-042c0dc3e013.jpg)

**Comment by RedEchoes** [comment]
I just redownloaded the file and everything seems great!! I'll play more today to see if it adds glitches anywhere else.

Value of 4 at 4K looks great.

**Comment by alexkiri** [comment]
The shader was added to the build script. The DoF effect now looks correct in all resolutions. We'll wait and see if the performance is affected for weaker gpus.

**Comment by modzilla99** [comment]
Does that work in V1.4?

**Comment by Crementif** [comment]
Yes it does.

**Comment by modzilla99** [comment]
Nice, thx, I'll update then ^^
