### ISSUE TITLE
[Xenoblade X] resolution reset after entering cockpit mode on skell

### ISSUE THREAD

**Issue by Lgnz** [slashiee/cemu_graphic_packs#14]
Playing in 4k and as soon the animation of cockpit mode appears everything beside the interface is resetted to 720p. Is it just me? Anyone with the same problem? Help!

**Comment by slashiee** [comment]
This is with playing with the graphic packs from this repo and not straight from Cemu, right?

**Comment by Lgnz** [comment]
Mmmmmm i just found out that the problem is still there even without graphic packs. :( 
Any idea why is it happening?

**Comment by slashiee** [comment]
It's either:
-A cemu issue, have to wait for Exzap to fix
-Optimization with the game, nothing we can probably do then

**Comment by Tsume** [comment]
This has been fixed in 1.7.1.

**Comment by slashiee** [comment]
If there happens to be a save file for it, I could quickly check to see if it actually is fixed as of 1.7.1

**Comment by Tsume** [comment]
Ask you ye shall receive.
https://pixxy.in/FFp5200.zip

This is for the US updated version.

**Comment by slashiee** [comment]
Alright thanks. Now for the fun part, because of the fact that I haven't played this game that far.

**Comment by slashiee** [comment]
Yeah, I honestly don't know what to do. Can someone else please attempt to confirm that 1.7.1 fixes the issue?

**Comment by getdls** [comment]
1.7l1 fixed the issue
