### ISSUE TITLE
When scaling the shadow map resolution in rules.txt, the blur part (penumbra) needs to be scaled to the same level in the shader

### ISSUE THREAD

**Issue by getdls** [slashiee/cemu_graphic_packs#143]
When scaling the shadow map resolution in rules.txt, the blur part (penumbra) needs to be scaled to the same level in the shader.

![4kscaled](https://user-images.githubusercontent.com/25286924/33717745-62bc3cc0-db5b-11e7-97c2-1a4d7e351336.png)

Otherwise you end up with a shadow like below. I assume we have the same problem for other games.
![4kunscaled](https://user-images.githubusercontent.com/25286924/33717794-7ee08c6c-db5b-11e7-9ea8-abab14e38a7b.png)

The problem is that this scaling follows the shadow map, ie high res shadow pack not the main rules. @slashiee , any suggestions on how you want to organize this?

- Stick all of the shadow shaders and scaling in the source folder 
- Generate separate shadow resolution folders by adding build logic
- Leave as is and hope ppl read the header and scale shadow shader to the same multiple as high res shadow rules
- Other suggestions?

**Comment by slashiee** [comment]
Probably put the higher resolution shadows in the packs themselves? Dunno how other people would think of that though

**Comment by Crementif** [comment]
We already scale the blur in other blur and shadow shaders, so I'd go with that. Something like this https://github.com/slashiee/cemu_graphic_packs/commit/47264be1b8836de48aaca79b925bb6db28d17fbc would be sufficient, so some code like
```<?php 
include 'Source/functions.php'; 
$fullWidth = $argv[1]; 
$fullHeight = $argv[2]; 
$scaleFactorX = always_decimal_format($fullWidth / 1280.0); 
$scaleFactorY = always_decimal_format($fullHeight / 720.0); 
?>
#version 420
#extension GL_ARB_texture_gather : enable
#extension GL_ARB_shading_language_packing : enable
// shader 1f83c0d47b1c4c34
// Used for: Background Blur
const float resXScale = <?=$scaleFactorY?>; 
const float resYScale = <?=$scaleFactorY?>; 

~Rest of shader code~
```. Having people change stuff hasn't been working wonderfully in the past.

**Comment by getdls** [comment]
That's what I'd vote for as well.

Maybe round to 1 <?=round($scaleFactorX)?> so we don't downscale shadows. 
hmm.. all of the other scaling is probably off below 1280x720 now that I think about it :(

**Comment by getdls** [comment]
Alright, scale in source folder it is then.

**Comment by slashiee** [comment]
i made a branch that puts all the shadow scaling into the game packs themselves, feel free to work off of this

https://github.com/slashiee/cemu_graphic_packs/tree/experimental_shadowscaling
