### ISSUE TITLE
Weird white Squares with Clarity GFX v176

### ISSUE THREAD

**Issue by Mr-Dexterous** [slashiee/cemu_graphic_packs#148]
When I'm playing Breath of the Wild 1.4.0 with the Clarity graphic pack sometimes there are this weird squares around the monks. The squares disappear if I disable the mod.
Graphic Packs that I'm using:

-  1920x1080

- Clarity GFX

- NVIDIA explosion smoke

- FPS++
![cemu screenshot 2017 12 16 - 23 34 49 83](https://user-images.githubusercontent.com/34608442/34076960-415934fe-e2bb-11e7-8c91-3bc1795e3fee.png)

**Comment by slashiee** [comment]
happens on Cemu itself w/o any gfx packs
