### ISSUE TITLE
add a way to know if graphic packs are up to date

### ISSUE THREAD

**Issue by slashiee** [slashiee/cemu_graphic_packs#158]
maybe generate a rules.txt through appveyor telling you the current version? like maybe the folder being "!GFXVersion" and the rules.txt pack name being "--Graphic Packs version ###--"?

**Comment by Crementif** [comment]
Added something in the latest website commit https://github.com/slashiee/cemu_graphic_packs/commit/0aa5deb7f50f4361feeb0f4ab5321e2638319e6a which gives an indication if there's a new update for their graphic packs alongside some other changes. Probably good enough besides the zip file names?

**Comment by slashiee** [comment]
this seems fine for now, gonna close this issue
