### ISSUE TITLE
I have this shadow glitch on amd gpu. please help

### ISSUE THREAD

**Issue by sil3ntkilr** [slashiee/cemu_graphic_packs#164]
i5 2500k, amd 7870 gpu using; Cemu 1.11.3, high res shadow, lwzx crash, 1080p pack, amd lights fix, amd shadow fix, sqare shadow fix. I have this shadow issue. any help please
https://imgur.com/a/WDBSp
https://imgur.com/a/mqnqP

**Comment by slashiee** [comment]
try disabling high res shadow

**Comment by sil3ntkilr** [comment]
i solved it by buying nvidia graphics card needed an upgrade anyways. also for those who are have this issue on their amd graphics card use 1080p pack only from graphicPacks_2-460 or lower. I think later versions not compatible with some amd cards.
