### ISSUE TITLE
CEMU Crash with Super smash brows brawl 

### ISSUE THREAD

**Issue by pCoder3000** [slashiee/cemu_graphic_packs#165]
Crashlog for Cemu 1.11.3
Date: 18-01-2018 19:48:40

-----------------------------------------
   Stack trace
-----------------------------------------
0x00007ff77e570840 (+0x00007ff77e570840)  ntdll.dll        cemuLog_log
0x00007ff77e570840 (+0x00007ff77e570840)  ntdll.dll        cemuLog_log
0x00007ffa0612ef90 (+0x00007ffa0612ef90)  ntdll.dll        RtlUserThreadStart
0x00007ffa060dbcc0 (+0x00007ffa060dbcc0)  ntdll.dll        RtlWalkFrameChain
0x00007ffa06163b70 (+0x00007ffa06163b70)  ntdll.dll        KiUserExceptionDispatcher
0x00007ffa061007c0 (+0x00007ffa061007c0)  ntdll.dll        RtlProcessFlsData
0x00007ffa02b30b00 (+0x00007ffa02b30b00)  ntdll.dll        DeleteFiber
0x00007ff77e5baa20 (+0x00007ff77e5baa20)  ntdll.dll        PPCCore_executeCallback
0x00007ff77e5baa20 (+0x00007ff77e5baa20)  ntdll.dll        PPCCore_executeCallback
0x00007ffa04b01fd0 (+0x00007ffa04b01fd0)  ntdll.dll        BaseThreadInitThunk
0x00007ffa0612ef90 (+0x00007ffa0612ef90)  ntdll.dll        RtlUserThreadStart
Exception 0xc0000005 at 0x7ffa0610089b(+0x4089b) in module ntdll.dll
cemu.exe at 0x7ff77e480000

RAX=00000000c00000f0 RBX=0f04247489ce0f18 RCX=0f04247489ce0f18 RDX=0000000000000000
RSP=0000005911bff7c0 RBP=000000000000000c RDI=0000000000000001 RSI=000000590f1d9000
R8 =0000005911bff7c8 R9 =0000000036e21e40 R10=0000000000000000 R11=0000000000000246
R12=00007ff77ee496e4 R13=0000000000000002 R14=0000000000000001 R15=0f04247489ce0f20

-----------------------------------------
   Game info
-----------------------------------------
Game: Super Smash Bros. [EU]
TitleId: 5000010145000
RPXHash: 7e0e6290

-----------------------------------------
   Active PPC instance
-----------------------------------------
IP 0x00000000 LR 0x00000000 Thread 0x115999c0

-----------------------------------------
   PPC threads
-----------------------------------------
52665a40 Ent 00e03624 IP 0382c0c4 LR c4c08203 SUSPENDED Aff 010 Pri 80 Name NULL
1158a0c0 Ent 02166690 IP 02043ac8 LR c83a0402 SUSPENDED Aff 100 Pri 93 Name TempManager
1158df80 Ent 02166690 IP 02052a50 LR 502a0502 SUSPENDED Aff 100 Pri 64 Name ResourceSystem:Reading
1158e680 Ent 02166690 IP 02052a50 LR 502a0502 SUSPENDED Aff 001 Pri 64 Name ResourceSystem:Reading
1158ed80 Ent 02166690 IP 020532c0 LR c0320502 SUSPENDED Aff 100 Pri 93 Name ResourceSystem:Dividing
1158f480 Ent 02166690 IP 020532c0 LR c0320502 SUSPENDED Aff 001 Pri 93 Name ResourceSystem:Dividing
115999c0 Ent 0382c170 IP 02070628 LR c8060702 READY     Aff 100 Pri 80 Name IGraphicsFactory::Create
52421410 Ent 00000000 IP 00e03644 LR 0000e000 RUNNING   Aff 111 Pri 32 Name NULL
1159d9e0 Ent 0382c170 IP 0382c170 LR 0000e000 RUNNING   Aff 100 Pri 79 Name NU::CommandManager

**Comment by slashiee** [comment]
![image](https://user-images.githubusercontent.com/15317421/35128363-138db2ce-fc6b-11e7-89c8-6a385d905176.png)
