### ISSUE TITLE
(Shantae HGH) Background workaround

### ISSUE THREAD

**Issue by frykillr** [slashiee/cemu_graphic_packs#167]
hi, i found this issue with Shantae HGH and was wondering if at line 80 (theres an unssuported instruction) that could be fix? 
in makes the game lose half the screen in black in certain part.

Cemu log says this

Unable to compile shader 382405578f453201
Compile error in shader 382405578f453201.

![image](https://user-images.githubusercontent.com/7881098/35346769-1a04c1d4-0101-11e8-9265-31daef6e8af6.png)
i added a screenshot of the error 

[382405578f453201_000000000000f249_ps.txt](https://github.com/slashiee/cemu_graphic_packs/files/1660794/382405578f453201_000000000000f249_ps.txt)

**Comment by Crementif** [comment]
Having an shader not compile is quite common. I don't have any shader compile issue, it's just random change, plus it's not a big deal having a shader not compile.  
  
The 'real' issue is there when you don't use any graphic packs, thereby it's a Cemu issue. I might look into a **workaround** today to see if it's a quick fix.

**Comment by alexkiri** [comment]
I've investigated this issue some time ago. It's a Cemu issue, the generated shader includes an unsupported instruction. The problem is, it cannot be overridden

**Comment by alexkiri** [comment]
![7e24a53d-dc6d-4483-882c-b4a9ba96dcc1](https://user-images.githubusercontent.com/6061770/35445748-3cb523a2-02bb-11e8-84ae-e0a474784c47.png)
![1e0457c2-0c42-4a1a-9d95-f04c77156d34](https://user-images.githubusercontent.com/6061770/35445749-3cdbcd9a-02bb-11e8-8308-d4fc6b218559.png)

**Comment by Crementif** [comment]
yeah, now that I've looked with Nsight this issue is definitely Cemu related. Fixing the shader isn't even possible, as there's supposed to be that fragment shader you've mentioned but it doesn't get referenced. Exzap is made aware, so it might be fixed someday, if it's really important at all. The missing shader or info also affects other elements like the speech bubble position from what I know.
