### ISSUE TITLE
 Fusion with CEMU project

### ISSUE THREAD

**Issue by pingo-power** [slashiee/cemu_graphic_packs#177]
Can you please enter in touch with CEMU dev. to integrate your projet as an option in CEMU and work with them to improve graphic integration in CEMU please ? So the work of graphic optimisation will be common to all CEMU related dev. :)
Because it's difficult to make simply playable CEMU, so for sit on the crouch, playing on the TV, with a Steam Controller, connected to a Steam Link to your PC, running Steam Big Picture mode, who running Z:BOTW in CEMU, you need to be a dev. for do all of that !

What do you think about an option in CEMU who auto. configure that in one click (or by default) ? It would be better than go to GitHub to get an app. that nobody know for configure it ONLY for have graphics, not a game fully playable, only the graphics, for the rest you need a ton of configuration...

**Comment by slashiee** [comment]
I don't understand

**Comment by JamieeLee** [comment]
Is this even in English , Slashiee?
