### ISSUE TITLE
Bayonetta 2 [US] Title ID: 0005000010172600 missing from rules.txt

### ISSUE THREAD

**Issue by Gistix** [slashiee/cemu_graphic_packs#178]
Very straightforward, title ID 0005000010172600 is not included in rules.txt

**Comment by slashiee** [comment]
The Title ID exists
https://github.com/slashiee/cemu_graphic_packs/blob/master/Source/Bayonetta2/rules.txt#L11

**Comment by Gistix** [comment]
![untitled 3](https://user-images.githubusercontent.com/5958298/35938980-eab4f8cc-0c31-11e8-9ed8-e7bc8fe9d8ba.png)

Straight from graphicPacks_2-688.zip\Bayonetta_2160p\rules.txt

**Comment by Gistix** [comment]
I was using the wrong graphics pack (from Bayo 1), I apologise.
