### ISSUE TITLE
BOTW - No Shadow resolution not working on gfx pack that contains shadow shader files

### ISSUE THREAD

**Issue by frykillr** [slashiee/cemu_graphic_packs#180]
hi, i was testing a no shadow resolution and found a bug.
testing from the native resolution (720P) i made a custom no shadow resolution at works but creates a sort of darker tone to the game in general where light should be there.

on a 540P pack i dropped the Shadows in the rules.txt to 0 and no effect shadows still visible. so im thinking its maybe related to those shadow shader files that controls them.

is it normal?

thanks

i submitted all my files and showed the printscreen also.

thx

[No Shadow Bug.zip](https://github.com/slashiee/cemu_graphic_packs/files/1703424/No.Shadow.Bug.zip)
![no shadow 540p](https://user-images.githubusercontent.com/7881098/35921494-c1e8b198-0be8-11e8-8f42-d9bd583f3e3c.JPG)
![no shadow native resolution](https://user-images.githubusercontent.com/7881098/35921506-c63f533c-0be8-11e8-9a4e-ce427cf69f00.JPG)

**Comment by Crementif** [comment]
Scaling overwrite rules to 0 doesn't do anything, so it's normal. Scaling the shadow viewport resolution is also not a very good way to remove the shadows, as it's likely gonna affect other viewports that are that size (which are common).

**Comment by frykillr** [comment]
would it be possible to officialy disable/remove shadow?
