### ISSUE TITLE
Resolutin ²

### ISSUE THREAD

**Issue by mixasrb** [slashiee/cemu_graphic_packs#185]
I have 16:10 monitor with 1680 x 1050 and there is no botw graphic resolution pack for me.
Pls meke it?
PS why did you close my last post , a nobody lived coment.

**Comment by slashiee** [comment]
Hold on

**Comment by slashiee** [comment]
https://github.com/slashiee/cemu_graphic_packs/tree/mixasrb

**Comment by slashiee** [comment]
https://ci.appveyor.com/project/slashiee/cemu-graphic-packs/build/700

**Comment by mixasrb** [comment]
which file I should edit


2018-02-10 10:27 GMT+01:00 Michael <notifications@github.com>:
