### ISSUE TITLE
Xenoblade Chronicles X Cockpit Mode

### ISSUE THREAD

**Issue by Kropiix** [slashiee/cemu_graphic_packs#194]
The cockpit mode on a 1080p texture packs seems to be broken, as it seems to render in a 720p in a small part of the screen.
![zyrvaqq](https://user-images.githubusercontent.com/36678022/36446800-ba506670-1682-11e8-9a62-c2a23ecc4299.jpg)

**Comment by getdls** [comment]
Can't reproduce here. 
Have you cleared caches and installed latest version of graphic pack?
Whats your gpu?

**Comment by Kropiix** [comment]
My gpu is Nvidia GTX 960M.
Cleared the GLCache, installed the newest graphic pack, even tried playing with no shader cache, but sadly the problem is still there. To add more information i'm currently on cemu 1.11.3, but when i tried it on 1.11.4 sadly it happens there as well :/. As for graphic packs I'm using the 1080p, AARemoval, AdjustableBrightness and NoOfflineTag.

**Comment by getdls** [comment]
I've may have found a shader that breaks, possible in combination with AA removal.  
I'll update if I figure it out.

**Comment by getdls** [comment]
@Kropiix  Try the updating to the latest version 
 https://github.com/slashiee/cemu_graphic_packs/commit/f42fd6b791c52f481b15dcf0f25d634c043438d6 should have fixed the skell issue. 

Also, try running without AA removal and see how you like it, the latest AA fix includes sharpen. .

**Comment by Kropiix** [comment]
The problem seems to have been fixed. Thank you for the help :)
