### ISSUE TITLE
Where's the documentation to each graphic pack?

### ISSUE THREAD

**Issue by miracleflame** [slashiee/cemu_graphic_packs#197]
Sorry to put it this way but how is one supposed to understand what is each of the graphics pack for BOTW doing, which are conflicting, which obsolete and why etc.?

Even the page https://slashiee.github.io/cemu_graphic_packs/ has very little to no explanation to each graphic pack.

Where are the detailed descriptions available to read?

**Comment by Crementif** [comment]
http://compat.cemu.info/wiki/The_Legend_of_Zelda:_Breath_of_the_Wild_Graphic_Packs You should probably have reformatted the question, github issues are not really meant to ask question. But there ya go.

**Comment by miracleflame** [comment]
Very good point. Thanks. I am reformatting the issue.

Page https://slashiee.github.io/cemu_graphic_packs/ does not contain such important link as to http://compat.cemu.info/wiki/The_Legend_of_Zelda:_Breath_of_the_Wild_Graphic_Packs and if it does it's painfully hard to find.

**Comment by Crementif** [comment]
I've added a link, it's not that big of an edit but it's there, now.
