### ISSUE TITLE
[BOTW] Transparent Link has color when using Monochromia

### ISSUE THREAD

**Issue by strubelz** [slashiee/cemu_graphic_packs#198]
I don't know if this belongs here, but when the camera is near Link he becomes transparent (normal). But when using Monochromia he now has color again. Maybe they use some kind of special shader or model for this whitch is not affected by Monochromia.
[Video](https://streamable.com/3klz9)

**Comment by Crementif** [comment]
It's fixed, finally! Check for commit https://github.com/slashiee/cemu_graphic_packs/commit/8848092651219b37b137c35cef2de6ba80e9f5ca for the details

**Screenshots:**
;)
![Panty shot](https://user-images.githubusercontent.com/26669564/38454642-2c8e4a70-3a6b-11e8-8db8-e43740861a31.png)
and the other bits
![image](https://user-images.githubusercontent.com/26669564/38454671-c98462e2-3a6b-11e8-9a3d-738e5f8a0f52.png)
