### ISSUE TITLE
Wind Waker HD Resolution Packs have pixelated shadows

### ISSUE THREAD

**Issue by JillianTo** [slashiee/cemu_graphic_packs#205]
https://cdn.discordapp.com/attachments/292733452590120961/420355910163103745/unknown.png
There's a problem with the AO in Wind Waker causing pixelated shadows when using any resolution changing graphics pack.

**Comment by getdls** [comment]
hmmm, may have forgotten double the scaling when I fixed the light bleeding..
I'll do a commit and double AO. Looks OK at 4k at least.. but it will probably still be off for 21:9

**Comment by getdls** [comment]
Allright, try the latest update, AO is scaled is updated 
 Also plz msg back the results so issue be closed if fixed.
