### ISSUE TITLE
[Splatoon] Ultrawide pack issues

### ISSUE THREAD

**Issue by slashiee** [slashiee/cemu_graphic_packs#207]
Squid Sisters TV is stretched
-
The main render is handled by vertex shader ae5bf21625f134f3. Fixed with 847911a0a6162a8fb5c1632c36a35c4f6a4db742
![image](https://user-images.githubusercontent.com/15317421/38182136-3a4d8c76-35ec-11e8-9c88-049e1d553bb4.png)
I've yet to find the shaders for the TV behind them.

Positioning relative to 3D objects off
-
Because the HUD is also scaled to 21:9, it causes the positioning of these HUD elements to be off-center. Could be fixed via patches.txt
![image](https://user-images.githubusercontent.com/15317421/38182150-5c93a81a-35ec-11e8-85a9-1ca39106bfb9.png)

Equip 3D rendering still stretched
-
Will need to be fixed via patches.txt (could possibly be fixed via shader edits?)
![image](https://user-images.githubusercontent.com/15317421/38182205-c31e058a-35ec-11e8-8b38-d1e17f4a53fb.png)

HUD elements that were meant for 16:9 but could fit 21:9 with edits
-
These could probably be easily fixed via vertex shader editing.
![image](https://user-images.githubusercontent.com/15317421/38182180-94f384a0-35ec-11e8-9540-e89689ff995c.png)

**Comment by Crementif** [comment]
**Blur background fix:**
![Blur background fixed](https://cdn.discordapp.com/attachments/292733452590120961/431538496835026964/unknown.png)
**Squid TV fix:**
![Squid TV fixed](https://cdn.discordapp.com/attachments/292733452590120961/431519993113346059/unknown.png)
**Inked screen (image before fix):**
![Inked screen before fix](https://cdn.discordapp.com/attachments/292733452590120961/431385887075467274/unknown.png)
**Majority of backgrounds fixed:**
![Inventory screen fixed](https://cdn.discordapp.com/attachments/292733452590120961/431375668157087744/unknown.png)
![Character selection backgrounds](https://cdn.discordapp.com/attachments/292733452590120961/430617588003766282/unknown.png)
![Random screens](https://user-images.githubusercontent.com/26669564/38388955-1a12d6e4-391d-11e8-892e-f28aae2557f7.png)
![Squid Sisters in TV-scene stretch fixed](https://cdn.discordapp.com/attachments/292733452590120961/430466436482203648/unknown.png)
