### ISSUE TITLE
Hyrule Warriors lines and "ghost shadow" (coop)

### ISSUE THREAD

**Issue by Kralle160** [slashiee/cemu_graphic_packs#213]
lines appear when using a res-pack :
![cemu_2018-04-29_03-04-56](https://user-images.githubusercontent.com/11779571/39402374-d2321526-4b5d-11e8-8471-e280a3f9b5df.jpg)
and the ghost shadow is a mystery to me but it seems like an outline of the characters 
(look at the enemy/allie healthbars)
![applicationframehost_2018-04-29_03-46-03](https://user-images.githubusercontent.com/11779571/39402451-ed63b640-4b5f-11e8-9646-8bafcd6519f8.png)

**Comment by Crementif** [comment]
I'm guessing this is fixed in the new Cemu 1.14.0 graphic packs, feel free to reopen if that's not the case.

**Comment by Tarou64** [comment]
![24baf19a0ba829affe8f0e56b9890fcb](https://user-images.githubusercontent.com/48785916/54738480-d99c9b00-4b8a-11e9-8003-99c5ee36cf8d.jpg)

On Cemu 1.15.3b, downloaded the latest community pack and only found the one resolution modifier which works for both single and mulitplayer for the main TV screen but the gamepaid has black lines and the resolution is not scaling at all.

**Comment by getdls** [comment]
Reproduced.. 
Let's see if we can't do something better than just fix the scaling.

**Comment by getdls** [comment]
I've added 2p res scaling, and some custom resolutions. They try to change 2p to the native resolution, instead of running at half and just upscale it.  I'm not sure if this will work on Amd / Intel, or just generate more black lines. 

Please test it  and close if things are working..

**Comment by Tarou64** [comment]
That did it! Thank you! It works amazing!

![7c50f52ed08bf7a598e65f6ff865fb67](https://user-images.githubusercontent.com/48785916/54872573-65d1dc80-4d9c-11e9-94d4-2d7edbac5f43.jpg)

**Comment by getdls** [comment]
Validated by reporter, closing
