### ISSUE TITLE
Xenoblade 60 FPS patch

### ISSUE THREAD

**Issue by getdls** [slashiee/cemu_graphic_packs#214]
Commited! https://github.com/slashiee/cemu_graphic_packs/commit/3540909821bea9a8c719e7266e783c2f5abd2a53
It’s a 60 fps patch, I’d love some help with anything in the  "what needs fixing" section 

For 60fps you will need a 6700k or newer CPU, and even that struggles in NLA.  XCX has frame pacing issues esp when switching between cut scenes. The fix is static, ie any time you don't hit 60fps, there's slow down.

v0.70. Ported to latest version of all releases (US, EU, JPN)
* Jitter issues remain, any scene with panning and character looks off, fog reveal scene is esp bad, but this version should be playable from start to end.  
* Japanese version should work, but I can't verify...
* FOV  can be changed in the patch file, just edit the float 
* No offline tag should probably replace the shader version, no broken dialog boxes
* 21:9 GUI will replace the current shader approach soon, just need to sort out some files. 
* Brightness fix, not commited.. should be combined with the regular shader fix. Screenshot below looks too dark. 
* Controller acceleration fix replaced with in game, now works as expected due to "elevator" fix  v0.71 

## What's  ok
- Character movement and animation speed
- Battle animation/ timings
- Menu animations
- Title scene
- Controller acceleration 
- Looping animations, grass, water, blinking lights etc 
- Birds, leaves _updated v0.31_
- Cutscenes now plays at correct speed, with some jitter issues _updated v0.5_
- Fog, Probe lights, Day/night cycle v0.51
- In game cut-scenes, arts slow motion  v0.6
- Vehicles and elevator movement speed v0.65
- Ported to EU, US, JPN, latest patches commited v0.70
- Controller acceleration fix replaced with in game, now works as expected due to "elevator" fix v0.71

## What needs fixing
- A better approach to slow down cinematic cutscenes
  - Camera pans esp parallax pans are jittery AF (frame doubling/blur broken?)
  - Camera shake events are way off  
- Verify the Japanese release
- Preferably go back to 60 fps logic approach eventually
  - 60 fps  for looping animations
- AMD fix, merge with regular brightness fix, should improve nights 
- Improve performance/pacing? I've tried killing all the vsyc calls, but didn't see any improvements compared to cemus no-vsync. But there are multiple calls all over...
- 90hz/45fps (100/50) patch Can't verify if cutscenes scenes work with 0.75/ 1.5 multiplier or if it's just my screen, in-game is fine.

**Comment by getdls** [comment]
Two potential patches to look into, brightness fix (AMD) and GUI scaling. 
Both need additional values, but initial fix looks promising

[XenobladeX_Amd.zip](https://github.com/slashiee/cemu_graphic_packs/files/1960206/XenobladeX_Amd.zip)
[XenobladeX_21_9_gui.zip](https://github.com/slashiee/cemu_graphic_packs/files/1960207/XenobladeX_21_9_gui.zip)

**Comment by Gamedev1909** [comment]
im testing now on amd both 60fps patch and brightness one

**Comment by Gamedev1909** [comment]
ok so brightness patch report .25 is to low 1.25 is perfect

**Comment by Gamedev1909** [comment]
![xcx](https://user-images.githubusercontent.com/18043258/39503514-b752a1f8-4d9c-11e8-9b0d-0951b7b92ae3.png)

**Comment by getdls** [comment]
Thanks for checking GAmeDev, are there any improvements compared to running the regular shader brightness fix?

I'm thinking set the shader brightenss/exposure  fix to 1.0 ie just use the shadow lift + gamma and combine it with the patch for AMD. That  should give some decent results.

**Comment by neoaga** [comment]
Hope it will work on EU rom soon .

**Comment by getdls** [comment]
*#!?¤%%&!!*... It's like this stupid game is mocking me! Why would nop:ing the row fix all of the ingame cutscene timing issues.. and just as I'm about to celebrate it removes all of the characters instead!?!



```
0x027A3350  = nop #     stwu      r1, -0x30(r1)
#0x027A3354                 stmw      r27, 0x30+var_24(r1)
#0x027A3358                 mflr      r0
#0x027A335C                 stfd      f31, 0x30+var_10(r1)
#0x027A3360                 ps_merge10 f31, f31, f31

```

**Comment by neoaga** [comment]
Look like i couldn't reach 60fps , it's only around 35-46fps , 40fps is average although my GPU and CPU only load 40-50% . 

My specs is 
I7 4770k@4.4ghz
980 Ti 
16GB Ram 
And i use lastest Cemu Build

**Comment by getdls** [comment]
Sorry, can't do much about performance, It's all about what cemu and your CPU can push. For reference, I get 60 fps in open areas, and 50 fps in NLA. 

If you check your CPU load, its about 50% average, but when you go by core the main cemu thread is limited to a single core. That one is maxed out. The slow down is due to the FPS fix being static 60, the game logic tied to the frame rate. 



![perf](https://user-images.githubusercontent.com/25286924/40579540-be6daa96-6129-11e8-8e13-1a8eac17d198.png)

**Comment by neoaga** [comment]
that's weird because usage of each core of mine rarely reach to 70-80% 
![cemu screenshot 2018 05 27 - 07 59 24 44](https://user-images.githubusercontent.com/39509434/40581500-9289139c-6184-11e8-9699-2c5878e34de6.png)
![cemu screenshot 2018 05 27 - 08 00 51 35](https://user-images.githubusercontent.com/39509434/40581501-92bb2634-6184-11e8-8575-9bef4571320e.png)

**Comment by Gamedev1909** [comment]
Exzap needs to add triple core support for this game

**Comment by getdls** [comment]
Please keep this on topic, I'll leave this here for a day so everyone can see and then remove the whole performance part.

**Comment by slashiee** [comment]
I'm probably just gonna clean it and post those messages onto #gfx_packs in the discord

**Comment by getdls** [comment]
Closing, not really getting anywhere with the shake/jitter issue...and I need a break from XCX

The source is committed, if anyone wants to poke at it, its probably the area around 0x027A33D8
