### ISSUE TITLE
Breath Of The Wild - Paraglider And Snowquill Texture Glitches 

### ISSUE THREAD

**Issue by Orangian** [slashiee/cemu_graphic_packs#222]
As you can see at [this link,](https://imgur.com/a/mJAlsL9) both the Snowquill set and the paraglider have graphical glitches when viewed at most angles. Im not sure what information I have to put here, so just ask me any questions.

Specs: 
Windows 10
Gtx 1070
I7-6700k 4.0 GHZ.
32GB Ram.

Cemu 1.12.0d
BOTW US build V208 all DLC's.

**Comment by slashiee** [comment]
Texture cache issue with Cemu, wait for the rewrite.
