### ISSUE TITLE
Super Mario Maker World Preview Missing/Corrupt after applying resolution graphics pack

### ISSUE THREAD

**Issue by Morph1984** [slashiee/cemu_graphic_packs#224]
SMM 720p with no GFX Packs applied

![smm720pnogfxpack](https://user-images.githubusercontent.com/39850852/40877209-0c4cfdca-66a7-11e8-9045-45cb0bc879fc.png)
![smm720pnogfxpackworld](https://user-images.githubusercontent.com/39850852/40877252-c414b7f4-66a7-11e8-9636-14fa54ead534.png)

SMM 2160p with 2160p resolution GFX Pack applied

![smm2160pgfxpack](https://user-images.githubusercontent.com/39850852/40877246-9e29bc4c-66a7-11e8-8736-2bee72333d45.png)
![smm2160pgfxpackworld](https://user-images.githubusercontent.com/39850852/40877247-a4278ce6-66a7-11e8-9065-ee1d748b1818.png)

**Comment by slashiee** [comment]
Sounds like a texture from the main resolution pack doesn't have a format excluded.

**Comment by slashiee** [comment]
![image](https://user-images.githubusercontent.com/15317421/40884166-c69fe252-66c3-11e8-9872-899d24ab8625.png)
