### ISSUE TITLE
No lens flare effect in Super Mario 3D World when applying any resolution GFX Pack

### ISSUE THREAD

**Issue by Morph1984** [slashiee/cemu_graphic_packs#227]
No resolution GFX Pack applied (720p resolution)

![sm3dw lens flare effect 720p](https://user-images.githubusercontent.com/39850852/41651647-3a4fdd52-74ab-11e8-84e2-4c3f0b94e588.png)

4K (2160p) resolution GFX Pack applied

![sm3dw no lens flare effect 2160p](https://user-images.githubusercontent.com/39850852/41651681-5725264e-74ab-11e8-9f4f-a0c94d64de01.png)

**Comment by Crementif** [comment]
Can you test if you change the shader mul to min in your gamepad config. Check the exampe file if you need any help with that.

**Comment by Crementif** [comment]
Also, I did have to do a ton of changes to the overview of that world, see https://github.com/slashiee/cemu_graphic_packs/issues/103 . I can't remember any problems with that though.

**Comment by Morph1984** [comment]
The one I posted is with accurateShadermul = true

**Comment by Morph1984** [comment]
accurateShadermul = min does not change anything

**Comment by Morph1984** [comment]
This applies to World Star, Mushroom, Flower and Crown

**Comment by Crementif** [comment]
![image](https://user-images.githubusercontent.com/26669564/41668697-38864998-74b0-11e8-8953-992368134fd4.png) also discovered by another user.

**Comment by Crementif** [comment]
Anyway, I'll probably look into this when I've got time. Can you check remove all the texture rules in the `rules.txt` of the resolution pack, but keeping the shaders in there.

**Comment by Morph1984** [comment]
Removing everything besides rules.txt fixed the issue.

**Comment by Crementif** [comment]
Can you now change shaderMin to false?

**Comment by Morph1984** [comment]
With the shaders removed and accurateshadermul = false, the lens flare effect is present.

**Comment by Morph1984** [comment]
I am using an NVIDIA GT1030 with latest drivers installed.

**Comment by Morph1984** [comment]
When I played through SM3DW, I rotated between accurateshadermul = false, min and true. No differences

**Comment by Morph1984** [comment]
Only when I applied a resolution GFX pack this effect disappeared

**Comment by Morph1984** [comment]
It seems that the shaders are to blame

**Comment by Crementif** [comment]
@getdls So, wait, my shader fixes are correct? 🤔 Should I close this issue?

**Comment by getdls** [comment]
Sorry... I was lazy and forgot to update to latest. 
[15:56:46] Compile error in shader 6d9067fd20086bc0. Log:
[15:56:46] 0(68) : error C1115: unable to find compatible overloaded function "intBitsToFloat(float)"
0(72) : error C1115: unable to find compatible overloaded function "intBitsToFloat(float)"

[15:56:46] Compile error in shader 280351fcf8e5949f. Log:
[15:56:46] 0(64) : error C1115: unable to find compatible overloaded function "intBitsToFloat(float)"

Should be fixed in :
https://github.com/slashiee/cemu_graphic_packs/commit/687b2a244284b6cc19c1c585f3cc3732703eefe6

**Comment by Morph1984** [comment]
Fixed
