### ISSUE TITLE
Cemu 1.14.0 is released, some BotW resolutions are outdated

### ISSUE THREAD

**Issue by windyboy1704** [slashiee/cemu_graphic_packs#234]
The latest Cemu version, 1.14.0, disables users from enabling outdated graphic packs. My laptop is a potato, and the BotW 480p graphic pack is outdated so I can't play BotW on this Cemu version. I hope you can update this graphic pack (and others).

**Comment by Supersonicboss1** [comment]
These are [WIP 1.14.0 Graphics Packs](https://github.com/slashiee/gfx_pack)
You can try using these but they may not work.

**Comment by windyboy1704** [comment]
> These are [WIP 1.14.0 Graphics Packs](https://github.com/slashiee/gfx_pack)
> You can try using these but they may not work.

Thanks, I've tried it and it works. However, BotW can't get past the loading screen on 1.14.0, so I have to stay on 1.13.2 (it's not the graphic pack's fault).

**Comment by Crementif** [comment]
We don't really plan on keeping the version 2 graphic packs anymore. I suggest backing up and removing your shader cache if you haven't tried that, or try a clean install.
