### ISSUE TITLE
Fix inconsistent pack naming

### ISSUE THREAD

**Issue by Crementif** [slashiee/cemu_graphic_packs#237]
Fix the Hyrule Warriors title! And contrasty should also be located under Enhancements, not directly in the game title's root. I also noticed some capital letter stuff like `name = default`. But that's mostly minor OCD stuff for some people. We can't moderate your commits with PR's anymore, but this should be checked before pushing things.

Hope you can fix these... dope that we've got new contrasty packs though, these were requested pretty often so I'm glad you've added these!

**Comment by Crementif** [comment]
![yoshi's woolly world](https://cdn.discordapp.com/attachments/292733452590120961/507279327927205898/unknown.png) Seems like here's another title.

**Comment by slashiee** [comment]
fixed wooly world name issue

**Comment by slashiee** [comment]
I fixed the Woolly World and Hyrule Warriors issue

**Comment by Crementif** [comment]
Fixed it with commit https://github.com/slashiee/cemu_graphic_packs/commit/cc1e5f7f9ae335c40e1e23f493d0cb88bde552ed .
