### ISSUE TITLE
Super Mario 3D World has weird render when turning Resolution graphic pack

### ISSUE THREAD

**Issue by windyboy1704** [slashiee/cemu_graphic_packs#238]
I don't know if this is Cemu issue or graphic pack issue (on Intel GPU). When I choose Resolution graphic pack 540p or 360p, SM3W has weird render and it's too ugly to look at.
[https://i.imgur.com/7fv4ErE.png](https://i.imgur.com/7fv4ErE.png)
[https://i.imgur.com/hE7Ei4h.jpg](https://i.imgur.com/hE7Ei4h.jpg)
Hope you guys can take a look at this problem. I tried to delete the cache but it didn't work. I have the latest graphic card version.

**Comment by getdls** [comment]
Thats what, the 3rd report on ”uneven” sub 1280 resolutions breaking? 
I wote for removing anything but 640x360

**Comment by getdls** [comment]
Try the latest build. Please report back and close this issue if it works for you.

**Comment by windyboy1704** [comment]
Thanks a lot! The latest graphic pack version worked for me
