### ISSUE TITLE
Paper Mario: Color Splash [CNF#01]

### ISSUE THREAD

**Issue by slashiee** [slashiee/cemu_graphic_packs#24]
Broken colorless spots

1080p:
![image](https://cloud.githubusercontent.com/assets/15317421/23097514/b0405aaa-f5ea-11e6-91b9-54c85a31b174.png)

720p (native):
![image](https://cloud.githubusercontent.com/assets/15317421/23097503/655f499c-f5ea-11e6-971e-62ea9d019e3a.png)

**Comment by slashiee** [comment]
![Color Splash 1080p](https://cloud.githubusercontent.com/assets/15317421/22576220/2db29dfa-e96f-11e6-9d2e-a37b9f10cb66.png)

I'll add it to the repo soon

**Comment by slashiee** [comment]
Support added as of e8ecf132, but no formats have been ignored yet related to 720p and 480p

**Comment by slashiee** [comment]
Game freezes after intro movie, so it's a cemu issue.

**Comment by slashiee** [comment]
Looks like there might be some framebuffer shenanigans going on with this game?
![oh god](https://cloud.githubusercontent.com/assets/15317421/22577183/ff38d48e-e974-11e6-8a4a-57684b5fa288.png)

**Comment by slashiee** [comment]
Yep, definitely framebuffer shenanigans. Reznoire's video doesn't have those issues, and he runs the game at 720p

https://www.youtube.com/watch?v=sh7r2RVWiT0

**Comment by slashiee** [comment]
```=============================
CemuViewportSkimmer by MHVuze
=============================
Depending on your CPU and the log size, the processing might take some time.

0, 0, 1024, 1024
0, 0, 1280, 720
0, 0, 512, 512
0, 0, 256, 256
0, 0, 640, 360
0, 0, 320, 180
0, 0, 160, 90
0, 0, 854, 480

Found 8 unique viewport resolutions and a total of 1804.```

**Comment by slashiee** [comment]
I just realized that this would be more of a format issue than framebuffer issue. We just need to exclude the format the colors are at. I'll still keep it just incase it happens to be a framebuffer issue.

**Comment by slashiee** [comment]
Turns out the freeze after the intro movie happens without any graphics pack on as well. Seems like cycle based is recommended for this game. This is really confusing.

**Comment by slashiee** [comment]
I have found the shader for the colorless spots. Removing all of void main completely got rid of them. Tested it on both title screen and beginning of Port Prisma. This is the file itself:
[459057c5fc27ffbe_000000078007924b_ps_source.txt](https://github.com/slashiee/cemu_graphic_packs/files/877857/459057c5fc27ffbe_000000078007924b_ps_source.txt)
Now, it needs to be fixed for the resolutions.

**Comment by slashiee** [comment]
For those curious, this is the save with no colorless spots workaround and with no AA:
![image](https://cloud.githubusercontent.com/assets/15317421/24439816/7c6f7902-1405-11e7-93bf-d6b4c645861b.png)

**Comment by getdls** [comment]
From the screenshot it looks like the depth render is broken, not just unscaled so DC TF style fix probably won't help. I'll see if I can borrow a copy , but for non as fixes, we probably should see what 1.74 change.

**Comment by slashiee** [comment]
```
GX2: Fixed a bug in GX2ClearBuffersEx() and GX2ClearDepthStencilEx() where depthbuffer->clearDepth was set to the incorrect value
```

Cemu 1.7.5 has this in the change log, maybe this will fix it?

**Comment by slashiee** [comment]
I'm able to confirm that it does not fix the issue. So, that's still an issue. Maybe later I can attempt doing the DCTF style fix to see if it fixes it

**Comment by slashiee** [comment]
Color Splash might be fixed with 1.7.6, will check to make sure. If it's fixed, will close this issue with 1.7.6 public release.

![BotWFix](https://i.imgur.com/s7MmfuI.png)
![TFFix](https://i.imgur.com/iZkSJes.png)

**Comment by slashiee** [comment]
Cemu 1.8.0 does not fix this issue

**Comment by slashiee** [comment]
Looking into Nvidia Nsight, the framebuffers are 66 68 for me.

-66-
Format: GL_DEPTH24_STENCIL8
Target: GL_TEXTURE_2D

-68-
Format: GL_DEPTH24_STENCIL8
Target: GL_TEXTURE_2D

![image](https://user-images.githubusercontent.com/15317421/30466382-509d1e52-9992-11e7-9985-8b6799a2bb29.png)

**Comment by slashiee** [comment]
[efc16c7f50957110_000000078007924b_ps.txt](https://github.com/slashiee/cemu_graphic_packs/files/1347971/efc16c7f50957110_000000078007924b_ps.txt)

**Comment by Crementif** [comment]
Had a lot of issues tracing this specific shader. @slashiee You've mentioned both `efc16c7f50957110_000000078007924b_ps.txt` and `459057c5fc27ffbe_000000078007924b_ps_source.txt`. Does 1 apply the blurred layer and does 1 blur the layer like some of BotW shaders have? I'll use the save you've provided (helps a lot!) and do some work on this today.

**Comment by Crementif** [comment]
![720p Cemu](https://user-images.githubusercontent.com/26669564/31405947-dd599aa6-adff-11e7-9d22-c8c4255d0d53.png)
![720p Wii U](https://user-images.githubusercontent.com/26669564/31406596-4878a46a-ae02-11e7-8467-b00b0f93b8c4.png)
This seems like it's a Cemu issue?

**Comment by NAVras-Z** [comment]
yea, looks like cemu issue, it seems texture redefine isn't working properly on some textures, they ended up having original res but the size/coordinates is scaled thus misplaced.

**Comment by kchavezs** [comment]
> I have found the shader for the colorless spots. Removing all of void main completely got rid of them. Tested it on both title screen and beginning of Port Prisma. This is the file itself:
> [459057c5fc27ffbe_000000078007924b_ps_source.txt](https://github.com/slashiee/cemu_graphic_packs/files/877857/459057c5fc27ffbe_000000078007924b_ps_source.txt)
> Now, it needs to be fixed for the resolutions.
> For those who need a save file at the beginning of Port Prisma, here you go:
> [ac33e303.zip](https://github.com/slashiee/cemu_graphic_packs/files/877862/ac33e303.zip)

Where do i paste this?

**Comment by Crementif** [comment]
You shouldn't need them anymore. The game runs without any graphical or crashes that I know of, just audio problems.
