### ISSUE TITLE
Paper Mario: Color Splash Resolution Pack Missing

### ISSUE THREAD

**Issue by Luigia12** [slashiee/cemu_graphic_packs#242]
thanks for fixing BOTW, SM3DW and YWW.

I missed the Resolution Packs for
Paper Mario: ColorSplash
New Super Mario Bros. U

**Comment by slashiee** [comment]
Transferred from old repo

NSMBU packs now exist, but none yet for Color Splash

**Comment by Luigia12** [comment]
BatchFW ColorSplash v2 to v3 cloud and sky missing

[Definition] 
titleIds = 000500001f600b00 
name = Resolution 
path = "Paper Mario: Color Splash/Graphics/Resolution" 
description = Changes the resolution of the game 
version = 3 
# 
[Preset] 
name = 1280x720 (Default) 
$width = 1280 
$height = 720 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 640x360  
$width = 640 
$height = 360 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 960x540  
$width = 960 
$height = 540 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 1280x720  
$width = 1280 
$height = 720 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 1600x900  
$width = 1600 
$height = 900 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 1920x1080  
$width = 1920 
$height = 1080 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 2240x1260  
$width = 2240 
$height = 1260 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 2560x1440  
$width = 2560 
$height = 1440 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 2880x1620  
$width = 2880 
$height = 1620 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 3200x1800  
$width = 3200 
$height = 1800 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 3520x1980  
$width = 3520 
$height = 1980 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 3840x2160  
$width = 3840 
$height = 2160 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 4160x2340  
$width = 4160 
$height = 2340 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 4480x2520  
$width = 4480 
$height = 2520 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 4800x2700  
$width = 4800 
$height = 2700 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 5120x2880  
$width = 5120 
$height = 2880 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 5440x3060  
$width = 5440 
$height = 3060 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 5760x3240  
$width = 5760 
$height = 3240 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 6080x3420  
$width = 6080 
$height = 3420 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 6400x3600  
$width = 6400 
$height = 3600 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 6720x3780  
$width = 6720 
$height = 3780 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 7040x3960  
$width = 7040 
$height = 3960 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 7360x4140  
$width = 7360 
$height = 4140 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 7680x4320  
$width = 7680 
$height = 4320 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 8000x4500  
$width = 8000 
$height = 4500 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 8320x4680  
$width = 8320 
$height = 4680 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 8640x4860  
$width = 8640 
$height = 4860 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 8960x5040  
$width = 8960 
$height = 5040 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 9280x5220  
$width = 9280 
$height = 5220 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 9600x5400  
$width = 9600 
$height = 5400 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 9920x5580  
$width = 9920 
$height = 5580 
$gameWidth = 1280 
$gameHeight = 720 
# 
[Preset] 
name = 10240x5760  
$width = 10240 
$height = 5760 
$gameWidth = 1280 
$gameHeight = 720 
# 
# Full Res 
[TextureRedefine] 
width = 1280 
height = 720 
overwriteWidth = ($width/$gameWidth) * 1280 
overwriteHeight = ($height/$gameHeight) * 720 
# 
# 2P Full Res 
[TextureRedefine] 
width = 640 
height = 360 
overwriteWidth = ($width/$gameWidth) * 640 
overwriteHeight = ($height/$gameHeight) * 360

**Comment by slashiee** [comment]
Don't use BatchFW, there are rounded resolutions to be accounted for
![2018-11-05_22-35-07](https://user-images.githubusercontent.com/15317421/48046931-0fe0fd00-e14b-11e8-9bb3-178bf1bb9dca.png)

**Comment by Luigia12** [comment]
the same problem with sky and clouds at SM3DW and YWW when make it with BatchFW. With your backs now problem. I hope Colorsplash 1440p is possible.
