### ISSUE TITLE
[XCX] Resolution & lighting

### ISSUE THREAD

**Issue by Hypothraxer** [slashiee/cemu_graphic_packs#243]
I'm encountering issues with lighting in XCX using resolution modifier included in current 1.14 WIP graphic pack : 
- nights are way too dark, especially outside town (the savefile will drop you outside of town at 01:00 am) ; I can't see anything. See screenshots attached.
![xcx_night_with_graphicpack](https://user-images.githubusercontent.com/42849162/44877482-6a219580-aca4-11e8-88e4-d8fd0fcc1814.png)
![xcx_night_without_graphicpack](https://user-images.githubusercontent.com/42849162/44877483-6a219580-aca4-11e8-8222-3703753cfb6e.png)
- some flashs (I can see some just at the title screen) popping from time to time, even at daylight
These issues disappear if I disable the resolution modifier.

Setup : 
- Cemu 1.14.0 W6
- Cemuhook 0.5.6.5
- XCX v1.0.1E
- resolution pack (whatever resolution set, even the default one)
- savefile attached [save.zip](https://github.com/slashiee/gfx_pack/files/2337807/save.zip)
- location for the savefile : mlc01\usr\save\00050000\101c4c00
Computer used : i7 8700 @ default settings, GTX 1070, 16Go DDR4 RAM, 2 SSDs (1 for system, 1 for games)

What I tried so far : 
- deleting the Cemu folder & recreating everything from scratch ; same issues
- downloading graphic packs again ; same issues
- tried to change some basic settings in Cemu ; same issues

I hope I posted this at the right place ; if not, my apologies.

**Comment by getdls** [comment]
Probably fixed with https://github.com/slashiee/cemu_graphic_packs/commit/3c8958ca35c50ecdaaf6eb000ef2c74b86a5ac49
I've addressed all the light issues I can reproduce.. But I really don't play in 1800. 

Please test and close if OK

**Comment by Crementif** [comment]
Well, I'm guessing this could probably be closed. Reopen if it's not yet fixed with the new pack.
