### ISSUE TITLE
Error in Ninja Gaiden 3 pack

### ISSUE THREAD

**Issue by Spiritovod** [slashiee/cemu_graphic_packs#244]
It looks like there is an error in vertex shaders in the source pack.
They're now:
const float resXScale = ($width/$gameWidth);
const float resYScale = ($width/$gameWidth);

instead of:
const float resXScale = ($width/$gameWidth);
const float resYScale = ($height/$gameHeight);

**Comment by slashiee** [comment]
fixed with 9d08710c29d570c64d377a3e5cd78bd208051d11
