### ISSUE TITLE
Downscaling issues with graphic packs

### ISSUE THREAD

**Issue by windyboy1704** [slashiee/cemu_graphic_packs#245]
Intel GPU. 360p resolution graphic pack. -nolegacy cmd
https://i.imgur.com/VlbR0Oz.png blur problem with Resolution graphic pack on
https://i.imgur.com/BFy32AB.jpg strange render for 2D graphic (in this screenshot, the picture is too blue)

And why 480p option is missing?

**Comment by Crementif** [comment]
Yeah, there's some problems with the downscaling of textures. Pretty sure this applies to any game in 1.14.0 currently.

**Comment by Cheesypoofy1** [comment]
Is this why the Bilinear downscaling option under Cemu's debug menu is disabled/greyed out?

**Comment by getdls** [comment]
Scaling breaks a bunch of tiny view ports on any resolution that's not an even mutiple of 1280x720
```
[23:47:17] Source:      f430c000 origResolution  128/  80 effectiveResolution  128/  80 fmt 001a mipIndex 0 ratioW/H: 1.0000/1.0000
[23:47:17] Destination: f430c000 origResolution  120/  75 effectiveResolution  180/ 112 fmt 001a mipIndex 0 ratioW/H: 1.5000/1.4933
```

I also needed to convert    resXScale with intToFloat for a couple of VS haders. Maybe cast to float is possible in rules.txt but I haven't found out how. 

`const float resXScale = intBitsToFloat($width)/intBitsToFloat($gameWidth);  `

Another partial fix is to scale the res to the expected proportion. 

```
 [Preset]
name = 1920x1080 (HD)
$width = 1920
$height = 1080
$gameWidth = 1280
$gameHeight = 720
$scaleShader = (720.0/1080.0)

```

```
[TextureRedefine] #
width = 16
height = 8
###formats = 0x008,0x80e # ,0x431,0x031
formatsExcluded = 0x431,0x035,0x034,0x033,0x031
overwriteWidth = ($width/$gameWidth) * (16*$internalRes)
overwriteHeight = ($height/$gameHeight) * (8*$internalRes)
```

However the results were mixed.. It works well for fixing stuff like 512x512.. and in a pinch stuff like 16x8 that 3200x1800 keeps breaking.  But shader scaling a bit of hit n miss when fixing all textureRedefine combined with widescreen + patches. Things like multi pass effects alignment being slightly off. 

In the end I just left it for shadow scaling (1024, 512), and disabled anything below 32x32 in XCX.

**Comment by skalfate** [comment]
Cemu 1.14c had some unfortunate bugs. One of which is The lower resolution issue in botw. Exzap looked into it, and he has the fix already but it isn't released yet. With the changes in 14c to translate decimal properly for foreign languages locales, one of the bug that was created was the translation of floats into integers when the variables didn't have remainders.

It can be fixed with editing parts in shaders. But the easier fix is already implemented in the unreleased version of cemu.

**Comment by getdls** [comment]
Well, that was a waste of time and effort.. 
Thanks for the update skalfate

**Comment by skalfate** [comment]
your welcome
