### ISSUE TITLE
[BotW] Cutscenes are stretched in the 21:9 packs

### ISSUE THREAD

**Issue by Nemitis** [slashiee/cemu_graphic_packs#248]
The old graphics packs would keep the pre-rendered cutscenes in 16:9, but the new ones stretch them to 21:9.

**Comment by skalfate** [comment]
As of right now it isn't possible with a texture definition in rules.txt. 

It may be possible to do with a vertex shader mod to insert in black bars. Crementif said he'll look in to it when he can.

**Comment by Crementif** [comment]
I've tried to fix it with vertex shaders, but no usable results. It would repeat each 2s for some reason. It would also have pretty ugly edges. Also tried fiddling with resolutions, but the depth that is likely the cause of the issues I had with the vertex shaders can't be excluded using tilemodes.
