### ISSUE TITLE
FPS++ maxes out at 60FPS in BOTW

### ISSUE THREAD

**Issue by Atemu** [slashiee/cemu_graphic_packs#249]
I get >60FPS in some areas of the game (tested with static 144FPS mode) but dynamic mode won't let the FPS go above 60 in the same areas.

**Comment by slashiee** [comment]
Try the "Remove 60FPS Lock" pack under in the FPS++ pack.

**Comment by Atemu** [comment]
I just upgraded to the latest release (v156; I was running v147 when I wrote the OP) but that submenu is not showing up for me.

I then cloned the master and copied `Enhancements/*`, `Modifications/*`, `Source/*` and `Workarounds/*` into `graphicsPacks/` but there is still no such submenu to be found (though those should be the same files as in v156 anyways).

I'm currently running CEMU 1.14.0c and cemu hook 0570, are you running a non-public version of CEMU and/or your plugin which might be required for this to work?

**Comment by Cheesypoofy1** [comment]
Not sure what you're doing wrong because the submenus work for me.  Maybe try deleting your existing graphics packs and copy over the new ones instead of attempting to merge.  May sound obvious but you need to restart Cemu in order for the new graphics packs to be detected.

**Comment by Atemu** [comment]
>deleting your existing graphics packs and copy over the new ones

That's how I upgraded them.

> May sound obvious but you need to restart Cemu in order for the new graphics packs to be detected.

Turning it off and on again was the first thing I tried ;)

>the submenus work for me

Can you confirm that you are on the exact same versions of CEMU, cemu hook and graphicsPacks as I am?  
Here are the hashes of the zips I extracted:

ZIP | SHA256SUM
:-- | :--
cemu_1.14.0.zip | `CDB6B9FFBB2E095453AE04F18BC9D0E325A4BE9B11306754738E791724977181`  
cemuhook_1140_0570.zip |  `C58A38C60041146669C1AF6614E6A48AB580581207239B7A88D71DC00EA3CA58`  
graphicPacks156.zip | `0418D77FE6F97A4510D77AFAF8403460C7095707D087AC43C277F6527F6D0C0F`

**Comment by Cheesypoofy1** [comment]
So strangely I notice the submenu work in graphicPacks150.zip thru graphicPacks154.zip but not graphicPacks155.zip or graphicPacks156.zip.

**Comment by Cheesypoofy1** [comment]
_graphicPacks153.zip_ removes **BreathOfTheWild_FPS++_Arrows** previously in _graphicPacks152.zip_ even though there's no mention of it in the changelog/commit.

**Comment by slashiee** [comment]
arrows pack was removed for being a broken mess
