### ISSUE TITLE
[Super Mario Maker] Black Borders when playing with NSMBU theme

### ISSUE THREAD

**Issue by Gabryxx7** [slashiee/cemu_graphic_packs#25]
Both in Gamepad and TV, the NSMBU version shows two black borders, it looks like something is not properly upscaled as the non-black part becomes bigger at higher resolutions.
There must be another resolution that is not overwritten.
Probably the part of the screen that renders NSMBU has a different resolution than 1280x720

Super Mario Maker - 1080p
![cemu_2017_02_03_15_07_00_368](https://cloud.githubusercontent.com/assets/6282055/22594300/cf5a131e-ea22-11e6-8c4f-3eecebe9afef.png)

Super Mario Maker - 1440p
![cemu_2017_02_03_15_12_38_991](https://cloud.githubusercontent.com/assets/6282055/22594403/3eeb0030-ea23-11e6-93ea-74409af84395.png)

**Comment by Gabryxx7** [comment]
This is relative to the pull request I made, I probably shoul've waited until the request is completed!

**Comment by Darkemaste** [comment]
Finding the resolution for that was relatively easy/quick shortly after graphic packs where introduced, but everything that shows in what used to be the black area gets corrupted pretty badly (as you saw in closed issues) and I haven't been able to find a proper fix via formats or through GPUPerfStudio. 

The game actually uses multiple resolutions for different modes, and the other modes can be similarly broken as NSMBU mode if you target their resolutions too. It's removed from the repo until we can find a fix for NSMBU mode that doesn't break anything else/break other modes.

**Comment by slashiee** [comment]
@Gabryxx7 SMM works now with 1.11.3
