### ISSUE TITLE
Xenoblade Chronicles X GFX Pack does not work

### ISSUE THREAD

**Issue by EmulationChannel** [slashiee/cemu_graphic_packs#253]
Xenoblade Chronicles X GFX Pack does not work new Cemu 1.14.0c
![2018-11-05 2](https://user-images.githubusercontent.com/37957125/47998144-661b5500-e0e5-11e8-8bb4-93ba4de808bc.png)

**Comment by getdls** [comment]
@slashiee What's your stance on piracy for /cemu_graphic_packs ?  Technically you can do an incorrect dump ...

<img width="1172" alt="xcx" src="https://user-images.githubusercontent.com/25286924/48014596-4c026680-e127-11e8-83f7-319f296b25e4.png">

**Comment by slashiee** [comment]
no piracy
