### ISSUE TITLE
Missing parts of descriptions due to quotation marks

### ISSUE THREAD

**Issue by RandomGuyJCI** [slashiee/cemu_graphic_packs#259]
Some of the graphic packs' descriptions are cut off, because early quotation marks end the description earlier than it's supposed to.

**Example description:**

`description = "By default, every cheat is enabled. To specify the cheat you want and look at the specifics, please read the readme.txt in the "BreathOftheWild_Cheats" folder."`

**What the description's supposed to show:**

`By default, every cheat is enabled. To specify the cheat you want and look at the specifics, please read the readme.txt in the "BreathOftheWild_Cheats" folder.`

**What actually shows:**

`By default, every cheat is enabled. To specify the cheat you want and look at the specifics, please read the readme.txt in the `

**Comment by Crementif** [comment]
Oh whoops, I forgot about that... thanks for fixing this!
