### ISSUE TITLE
[FatalFrameProjectZero][JPN]Resolution Issue

### ISSUE THREAD

**Issue by holmes5800** [slashiee/cemu_graphic_packs#260]
I've got the newest graphic packs and tested Fatal Frame. When I run US version, everything is OK, but when I run JPN version, there is a grid like thing on the screen. And I see there is a patches.txt, something like [USAFatalFrameV0], [EuropeFatalFrameV0] in it, but no JPN content. Can we get this fixed ~~~

THX a lot !

**Comment by slashiee** [comment]
Can you try going to Debug> View RPL modules and send the Checksum please?

**Comment by holmes5800** [comment]
![_20181109120358](https://user-images.githubusercontent.com/44885060/48242780-be20c700-e417-11e8-9a58-1fb4eebe47a9.png)

This is the resolution I set.


![_20181109120229](https://user-images.githubusercontent.com/44885060/48242809-df81b300-e417-11e8-8eee-f563aafe0c93.png)

This is the GRID.


![_20181109120337](https://user-images.githubusercontent.com/44885060/48242816-ea3c4800-e417-11e8-84e9-4a9f0ea8e0d6.png)


And this is debug info

The checksum there I see is 

0xA86AA5B2

**Comment by skalfate** [comment]
Hi, here is the updated patches.txt file. Hopefully it works out. :)

**Comment by skalfate** [comment]
Unfortunately its not that simple, we also need the offsets to patch for the Japan Version. I don't have access to it yet. Perhaps sometime in the near future.

**Comment by holmes5800** [comment]
Is there anything I can do for help ?

**Comment by skalfate** [comment]
I just found the offsets for the Japan version. Patching it as I write this. Almost done.
