### ISSUE TITLE
[BOTW] 3440x1440 missing

### ISSUE THREAD

**Issue by DaneelReventelov** [slashiee/cemu_graphic_packs#264]
Can I have 3440x1440 resolution? There was in older pack
Thanks

**Comment by slashiee** [comment]
I think the reason why the resolution is gone is because of rounding issues. @skalfate is the one who did the pack so I'd wait for his response

**Comment by skalfate** [comment]
Various other resolutions will work, as long as the remainder is even when the resolution desired is divided by games real native resolution. If the remainder is long number, then Cemu rounds down and that is when glitches start to appear. At this point with the aspect ratio patch file, I suppose its possible.

With that resolution the aspect ratio would be 43 : 18. I don't know about adding odd resolutions to the main pack.

But for now What I can do is create you a custom pack with that resolution included, until Slashie decides on what to do with these kind of uncommon resolutions.

**Comment by DaneelReventelov** [comment]
Thanks for your res but I prefer a "Pack" version like the other things Bsod posted on his YT channel, if are good then I think should be introduced in this pack so is more simple to update

**Comment by skalfate** [comment]
Ok I'll push the resolution to the offical pack very soon.

**Comment by skalfate** [comment]
The resolution is now part of the main pack bud. I'll go ahead and close this issue.
