### ISSUE TITLE
NSMBU Black Background

### ISSUE THREAD

**Issue by Nindendy** [slashiee/cemu_graphic_packs#267]
Black Background in some world 2 levels with any custom resolution in graphics pack.
Cemu 1.14.0. If I disable this graphics pack, background return to normal

**Comment by getdls** [comment]
Please check if https://github.com/slashiee/cemu_graphic_packs/commit/924b0d062beaaab5e81896f14a8c11dc1349f2af fixes the issue, and close if OK.

If not, a save file would be helpful, I only have saves for lev 1.01-> 1.03

**Comment by skalfate** [comment]
Hey getdls,

I just wanted to let you know that in shaders modifications, when you use 

intBitsToFloat($width)/intBitsToFloat($gameWidth);

it breaks them from compiling.  The correct way to do it the following way 

float(Variable)

Thanks :)

**Comment by Nindendy** [comment]
getdls, I was download updated graphic pack with your fix. But background wasn't appear. I was checking this in world 2-1. I playing in NSMU + Luigi, if this important

**Comment by getdls** [comment]
@skalfate um... breaks compiling where?

@Nindendy When you see the error, close cemu and then please attach log.txt form the cemu folder.

**Comment by Nindendy** [comment]
@getdls 
[log.txt](https://github.com/slashiee/cemu_graphic_packs/files/2582034/log.txt)

**Comment by skalfate** [comment]
I remember from my own testing and from testing the super smash bros resolution pack shaders. Cemu log would give an error about casting the variable like that and failing to compile the shader. I don't have nsmbu so I cant test that out.

But even Exzap said to use float(variable) way.

**Comment by skalfate** [comment]
Its also visible in his log : 

[18:09:34] Compile error in shader 03285368cf940e37. Log:
[18:09:34] 0(6) : error C0000: syntax error, unexpected integer constant at token "<int-const>"

**Comment by getdls** [comment]
```
[18:09:34] Compile error in shader 03285368cf940e37. Log:
[18:09:34] 0(6) : error C0000: syntax error, unexpected integer constant at token "<int-const>"
```
Thats pretty interesting

**Comment by skalfate** [comment]
Nintendy, I recommend switching to single core recompiler. A lot of games begin to have instability with no single core. Botw Wild is the only one I know that doesn't get unstable.

**Comment by skalfate** [comment]
getdl,

In some instances, it'll work, but it isn't safe in all. In this scenario, try to run the game without all the shaders in the folder and see if that error happens, and then try to run the game with the default shader state. And see if that error comes up

**Comment by getdls** [comment]
I haven't got any shader errors with the game running at any resolution, that's why I find the above interesting.  Something differs between GPUs / Drivers for pretty general stuff. 


With that said, cemu always throws the same error regardless of graphics pack or not.  
18:52:23] GLDEBUG: Texture state usage warning: The texture object (0) bound to texture image unit 0 does not have a defined base level and cannot be used for texture mapping.

**Comment by Nindendy** [comment]
@skalfate, thank you for advice! Yes, I use triple-core recompiler for BOTW :)
@getdls, It's log file without turned on graphic pack - 
[log.txt](https://github.com/slashiee/cemu_graphic_packs/files/2582207/log.txt)

**Comment by skalfate** [comment]
See without the graphic pack, no errors are generated. With the resolution graphic pack, the modified shaders. One of them doesn't compile due to that : 

03285368cf940e37

And I am assuming its the same shader where the textureUnitPS0 is used differently than normally.

**Comment by skalfate** [comment]
@Nintendy,

Can you post your save file just for the purpose of testing, so we can visit the same area where your having the problem.

Getdl can get that fixed up for you. I don't have the game on my current hard drive.

**Comment by getdls** [comment]
Just a sec, I'm doing float conversion everywhere.. let's see if that changes anything.

**Comment by skalfate** [comment]
Ok

**Comment by getdls** [comment]
@Nindendy 
Can you please test the attached file. 
Delete the current NewSuperMarioBrosU_Resolution graphics pack, then unpack (don't overwrite, we don't want any leftovers)
[NewSuperMarioBrosU_Resolution.zip](https://github.com/slashiee/cemu_graphic_packs/files/2582389/NewSuperMarioBrosU_Resolution.zip)

**Comment by Nindendy** [comment]
@getdls same result with it. Log:
[log.txt](https://github.com/slashiee/cemu_graphic_packs/files/2582416/log.txt)

**Comment by Nindendy** [comment]
@skalfate Save File:
[1014b800.zip](https://github.com/slashiee/cemu_graphic_packs/files/2582423/1014b800.zip)

**Comment by skalfate** [comment]
getdl,

Don't you need to enable a certain extension to use texturesize()? I remember having to enable an extension to make it work.

**Comment by getdls** [comment]
Gg, work  @skalfate poke away if you have an suggestions. I can't reproduce any of the issues locally.

**Comment by skalfate** [comment]
Thank you. 

I am not sure if this will help @getdls, but I see it implemented differently than how I learned to do it.

In order to get texture size I think the parameter is : ivec2 resDim = textureSize2D(textureUnitPS0,0);

and you must enable #extension GL_EXT_gpu_shader4 : enable

**Comment by skalfate** [comment]
I will go fix this

[14:01:47] Compile error in shader 70b82af4d17024d2. Log:
[14:01:47] 0(8) : error C1115: unable to find compatible overloaded function "intBitsToFloat(float)"
0(8) : error C1115: unable to find compatible overloaded function "intBitsToFloat(float)"

**Comment by Nindendy** [comment]
@skalfate I made two screenshots in beginning of world 2-1. First with G/P, second without.
![cemu screenshot 2018 11 15 - 17 34 43 03](https://user-images.githubusercontent.com/45014201/48559769-4d891700-e8fd-11e8-86cd-df45c447a677.png)
![cemu screenshot 2018 11 15 - 17 36 06 24](https://user-images.githubusercontent.com/45014201/48559774-50840780-e8fd-11e8-80f8-ec8e66d8abc4.png)

**Comment by getdls** [comment]
@Nindendy Can you try the attached pack?   
By eliminating all of the assignment It should tell us if the casting is wrong or blur generation. 

[NewSuperMarioBrosU_Resolution.zip](https://github.com/slashiee/cemu_graphic_packs/files/2587344/NewSuperMarioBrosU_Resolution.zip)

**Comment by skalfate** [comment]
So one of the shaders had the casting wrong, and it had black screen, at the opening of the game. The post I posted a few messages above. Afterwards I have been playing though, and I don't get the screen. Let me get ot the spot and post a screenshot.

**Comment by skalfate** [comment]
@Nindendy , try the latest graphic pack, it should work fine now.

**Comment by Nindendy** [comment]
@getdls 
@skalfate 
Finally, It's works!! Thanks a lot for your help!
