### ISSUE TITLE
[ignore pls]

### ISSUE THREAD

**Issue by SvenZ64** [slashiee/cemu_graphic_packs#268]
I have a Nvidia GPU now. No point of making a 30FPS mod for Mario Kart 8 on Intel integrated graphics, that would be too much work...

**Comment by skalfate** [comment]
It is an easy fix, can be done, we just need some time for whomever gets the chance to do it.

**Comment by slashiee** [comment]
vsync presets would just end up slowing the game down. it would have to be a cemuhook patch in order to make the game run full speed at 30fps

**Comment by skalfate** [comment]
hmm

**Comment by Xalphenos** [comment]
I found speed variables for non racing npc speed. But never was able to find a speed variable for the main racers.

**Comment by skalfate** [comment]
You are half way there @Xalphenos , you can do it man. :)

@SvenDaHacker64 , I made a fps limiter for you. But like slashie said, it feels slowed down. I think the games original fps target was suppose to be 60. So in your case I am thinking your experiencing fast and slow with your 30-45 fps.

If the following packs helps you then great, but if not Xalphenos will one day find the right memory address to patch.

[MarioKart8_FPSLimiter.zip](https://github.com/slashiee/cemu_graphic_packs/files/2587881/MarioKart8_FPSLimiter.zip)

**Comment by SvenDaHacker64** [comment]
@skalfate Oh great, thanks. Gonna give it a shot. I'll be using 540p or 360p to have 50-60FPS at the moment until you're totally finished working on the 30FPS cap.

**Comment by rajahchaabeni** [comment]
in mario kart fps = game speed
50fps is unplayable it feels like you are playing 50cc
somebody need to make it skip some frames in order to smooth it
