### ISSUE TITLE
45FPS Xenoblade Chronicles X?

### ISSUE THREAD

**Issue by Thobro** [slashiee/cemu_graphic_packs#269]
Hey!

Would it be possible to make a static 45FPS pack for Xenoblade Chronicles X? I tried doing it myself but I'm not knowledgeable enough in this emulator.

EDIT:
I changed some values in the 60FPS file and locked my game to 45FPS and it seems to work fine. I locked my game via nvidia, it would be nice if we could lock it from within the patches file.

**Comment by getdls** [comment]
No further input, closing. 

Won't be making 45/50/60/75 patches with the current state of the patch.. and won't do any further digging for a long time.
