### ISSUE TITLE
[XCX] Physics pack might give crashes

### ISSUE THREAD

**Issue by Savanagi** [slashiee/cemu_graphic_packs#271]
I'm currently running on cemu 1.14.0c and XCX v1.0.2U and when I used the physics graphics pack, running or jumping made the game freeze but only the audio ran fine.

**Comment by getdls** [comment]
@lasyan3 ping, physics pack sounds like your cup of tea. 

Not hitting 30 fps breaking stuff?

**Comment by lasyan3** [comment]
Hi, I think it's linked to the Camera mod. I found out if it's active, I also have the freezes.
But the thing is, the mod is the same than with previous cemuhook so I suspect issue with it. Unless new info to share, I'm afraid the only action I can recommand is to disable the camera mod.

**Comment by lasyan3** [comment]
Just tried with cemu 1.15.0e and graphicpacks247 with both jump and run mods activated and no crash. Presets are "Speed x1.5" and "Horizontal 2.0 / Vertical 1.05".

**Comment by vegimata** [comment]
I tried a fresh install. Copied the same presets that you used. I am getting the same result. I can run using the Speed mod, but I cannot jump. Using Cemu 1.15.0e and graphics pack 247

**Comment by lasyan3** [comment]
Sorry to ask, but just to be sure, which version of the game do you use ?

**Comment by vegimata** [comment]
XCX v1.0.2U

**Comment by lasyan3** [comment]
Is it possible to share your savegame please?

**Comment by vegimata** [comment]
> Is it possible to share your savegame please?

https://openload.co/f/1cEl_Ekp1SA/XCX_Save.7z

**Comment by lasyan3** [comment]
Oh f*** I think it's linked to the savegame. Do you confirm you also have the crashes with a new game? Thanks to the new debugger in Cemu 1.15.0, I may be able to find out what is messing in the RAM and try to fix that.

**Comment by vegimata** [comment]
Yes, it also happens in a new game. It started happening when I was testing the RAMJET rifle

**Comment by lasyan3** [comment]
What is the RAMJET rifle? And can you share the last cemu log file of when it crashed please?

**Comment by vegimata** [comment]
It was an item given in a mission. The rifle is not with me anymore as I had finished the quest already. I will upload the logs later  when I get home in another 10 hours.

**Comment by vegimata** [comment]
https://openload.co/f/I8wvU_wp9z0/log.txt

**Comment by vegimata** [comment]
Yup it is working for me. Thanks! So it was just these codes?
_setVelocity = 0x00000000
0x00000000 = lis       r3, _velocity@ha

_setHorizVelocity = 0x00000010
0x00000010 = lis       r12, _hvelocity@ha

Just adding the letter a fixed it?

**Comment by vegimata** [comment]
Oh okay. Thanks again lasyan3!

**Comment by lasyan3** [comment]
You're welcome! I'm very relieved to finally have found the root cause of those crashes!
