### ISSUE TITLE
[BOTW] 21:9 3840x1600 Bloom or something not properly scaled

### ISSUE THREAD

**Issue by FirefoxinHell** [slashiee/cemu_graphic_packs#274]
testing the latest cemu_graphic_packs 207 on CEMU 1.14.0c i have problem in the start menu, and ingame in the botton of the screen i have like a black line or similar. other resos dont have this issue

https://steamcommunity.com/sharedfiles/filedetails/?id=1566620900
at the botton of the sreen black lines its visible

**Comment by slashiee** [comment]
Try the 4300x1800 resolution in the latest BotW pack.

**Comment by skalfate** [comment]
I'll be updating the pack to use a slightly different resolution. See if that works for you. If it does you can close the issue.

**Comment by slashiee** [comment]
That's good to hear.
