### ISSUE TITLE
Mario kart 8 ( 4 players split screen no shadow ) 

### ISSUE THREAD

**Issue by Mecak** [slashiee/cemu_graphic_packs#275]
Hello, does anyone else facing an issue  when shadow disappears in 4 player split screen mode after selecting graphic pack
It only exists when +2 players are in, no issues with single player

**Comment by rajahchaabeni** [comment]
exact same problem here 
ababab

**Comment by slashiee** [comment]
Fixed as of f46b40a292bcab2e9e892fde5fbf8e8f2d7484c7
