### ISSUE TITLE
[Splatoon] missing background in plaza when viewing inkling stats

### ISSUE THREAD

**Issue by slashiee** [slashiee/cemu_graphic_packs#276]
![2018-11-18_14-33-40](https://user-images.githubusercontent.com/15317421/48679000-6e40af00-eb3f-11e8-9df3-09eb23d4e827.png)

**Comment by getdls** [comment]
Dropping the format overwrite resolves that specific issue in this version.. But I'm not sure what you're accomplish?  

Getting it working with all possible format overwrites sounds interesting exercise.. I've been thinking about it myself. If we exclude a format from up scaling, would it make sense to still convert the format? Like fog, convert both the alpha on original fog texture and the view-port it renders to may improve quality.  Or in this case, the gradient/blur fade. 


```
[TextureRedefine]
width = 640
height = 368
formats = 0x816
#overwriteFormat = 0x823
overwriteWidth = ($width / $gameWidth) * 640
overwriteHeight = ($height / $gameHeight) * 368

[TextureRedefine]
width = 640
height = 360
formats = 0x816
#overwriteFormat = 0x823
overwriteWidth = ($width / $gameWidth) * 640
overwriteHeight = ($height / $gameHeight) * 360
```

**Comment by slashiee** [comment]
That sucks, guess I'll disable it for now...
