### ISSUE TITLE
BOTW Cheats not working on Cemu 1.14.0c

### ISSUE THREAD

**Issue by Berahthraben** [slashiee/cemu_graphic_packs#290]
Would really like to get Infinite Amiibos working again. If you have more important stuff, I'll understand, but any help is appreciatted. If you could tell me how to do it myself I'd put my best effort. (Still new to assemblies and programming in general, but I get by);

**Comment by Berahthraben** [comment]
Here you go. Sorry for the wait.
I've activated all available cheats just in case you needed to test them as well (Haven't really gotten to see which ones were/weren't working.
It's attached.
[log.txt](https://github.com/slashiee/cemu_graphic_packs/files/2655537/log.txt)

**Comment by Xalphenos** [comment]
You are running v64 of botw. None of the cheats have ever been ported to that version.
