### ISSUE TITLE
Pikmin 3 Resolution Pack

### ISSUE THREAD

**Issue by slashiee** [slashiee/cemu_graphic_packs#291]
Made this so that people can report issues that currently exist with the pack

Changes done to the pack:
* 7b7802ee1ad7dfe14d49e4a7a0a170d6ee8d6b37 - Inital Pack
* fe6a272876672c79612d99f5e273f91a4c21ed3c - Fix screen in spaceship and quarter res scaling
* c29d53bc43f0ba2517216dcd9172de38a068d94b - Add shadows pack and fix several bloom/blur related shaders

To be looked into:
* Gamepad
* Button blur

**Comment by Crementif** [comment]
Fixed the blur and bloom shaders + added a shadows pack.

**Comment by Crementif** [comment]
Fixed the low resolution water that was previously seen when using the gamepad with commit https://github.com/slashiee/cemu_graphic_packs/commit/cc1c7061af72e070c51deb4b778a8faeca06e0ea , so this issue should be closed.
