### ISSUE TITLE
Recommended Change: Change the title of this repo to better reflect what GFX packs has morphed into

### ISSUE THREAD

**Issue by lordneeko** [slashiee/cemu_graphic_packs#293]
Because this set now includes cheats and mods and gfx packs, I recommend a change to the repo's name to better reflect the vast increase in scope to this project.  Just a thought, but graphic_packs isn't as accurate anymore.

recommend perhaps: cemu_plugins
- cemu_plugins 
------ Graphics_Packs
------ ------ Resolutions
------ ------ Enhancements
------ Mods
------ Cheats
------ Workarounds

**Comment by slashiee** [comment]
I think I'll change it when Cemu itself changes the name, but I'm unsure for now

**Comment by lordneeko** [comment]
understood. Exzap should think of changing the name since it has become much more than it originally was.
