### ISSUE TITLE
 support for 4:3 or 5:4 

### ISSUE THREAD

**Issue by JIuBeP** [slashiee/cemu_graphic_packs#300]
Hey. Just question. Is it possible to add support for 4:3 or 5:4 resolutions (1024x768, 1280x1024)? I also noticed strange problems with shadows in LoZ BoTW when setting shadow resolution 0.5x (Nvidia geforce gtx 950, cemu 1.15.0e, LoZ BoTW 1.5.0)

**Comment by jiliangsoft** [comment]
shadow have black dot or line?my amd also have this problem when 0.5x. but normall in 1.14

**Comment by juantosuperpan** [comment]
yeah so is it possible at this point of time to create a 5x4\4x3 graphic pack for BOTW?

**Comment by skalfate** [comment]
It is, I think. I'll start looking into it now.

**Comment by slashiee** [comment]
any other requests for aspect ratios so we don't have to deal with them later on?

**Comment by skalfate** [comment]
I will test these out now

'[Preset]
name = 640x480 (4:3)
$width = 640
$height = 480 # 
$gameWidth = 1280
$gameHeight = 720

[Preset]
name = 1280x960 (4:3)
$width = 1280
$height = 960 # 
$gameWidth = 1280
$gameHeight = 720

[Preset]
name = 640x512 (5:4)
$width = 640
$height = 512 # 
$gameWidth = 1280
$gameHeight = 720

[Preset]
name = 1280x1024 (5:4)
$width = 1280
$height = 1024 # 
$gameWidth = 1280
$gameHeight = 720'

**Comment by juantosuperpan** [comment]
So I tested them out, and they look alright. Maybe the FOV could be a little higher. But, there is one thing that seems out of place when running those resolutions - the greyish\transparent line at the bottom of the screen. I'm not sure why it's there but... it's there.

**Comment by skalfate** [comment]
Which speaking of, on discord I was posting progress updates.

`there were black bars at the bottom of the new 4:3 and 5:4 resolutions due to the float results after the division, and trying to find the right height numbers without harming the aspect ratio was not possible in my testing

368 * 0.63
368 / 720
368 * 0.52
368 * 0.53
368 * 0.54
368 * 0.55
368 * 0.56
368 * 0.57
368 * 0.59`

So I came up with a new way that future proofs all bottom black bar issues.

**Comment by skalfate** [comment]
Ok I'll be publishing a new release with 3 resolutions for each ar ratio.

**Comment by juantosuperpan** [comment]
wow I never expected such involvement in my request, not speaking of how fast you got it solved. Many thanks man!

**Comment by skalfate** [comment]
Your welcome bud. The new changes are live. If there are any issues re-open this issue and we'll take a look.

**Comment by juantosuperpan** [comment]
so from what I played today, everything is fine and looks good, but the FOV could be wider, since the bow shooting feels weird, and Link covers up too much space on the screen.
