### ISSUE TITLE
Hyrule Warriors Gamepad Resolution

### ISSUE THREAD

**Issue by Kralle160** [slashiee/cemu_graphic_packs#306]
The Gamepad Resolution cannot be altered which was, as far as I know, possible in older versions.
I hope that feature will return, as it is absolutely critical for a awsome co-op experience.

**Comment by skalfate** [comment]
I do not see a gamepad pack for hyrule warriors in the old v2 latest pack available. However it is easy to make a gamepad map, if ofcourse you mean just increase the internal resolution?

**Comment by Kralle160** [comment]
As far as I remember the old resolution graphic pack increased both resolutions.

The graphic pack doesn't seem to work.
I tried it with and without the normal resolution pack.

![2018-12-26_05-27-48](https://user-images.githubusercontent.com/11779571/50432065-ab7f2600-08cf-11e9-8630-4bfb48936003.jpg)
![2018-12-26_05-32-20](https://user-images.githubusercontent.com/11779571/50432066-ab7f2600-08cf-11e9-996a-62daea8ecd63.jpg)

**Comment by slashiee** [comment]
seems more like resolutions tied to gamepad (besides from the gamepad resolution itself) are not scaled at all...

**Comment by Kralle160** [comment]
That works.

may i suggest editing the description to state that it'll also change the gamepad resulution.

![2018-12-26_05-58-00](https://user-images.githubusercontent.com/11779571/50432596-39a8db80-08d3-11e9-8c23-b54146232466.jpg)

**Comment by slashiee** [comment]
i think it'll be fine having it as is, considering there's other resolution packs that touch gamepad but don't mention that they do

**Comment by Kralle160** [comment]
alrighty and thank you.
