### ISSUE TITLE
graphicPack: can't parse preset "LOD -0.5 (Sharper): invalid operator found in expression: -0.5

### ISSUE THREAD

**Issue by JakeLD** [slashiee/cemu_graphic_packs#309]
The following error appears in cemu log.txt after loading game (via command line) such as Pikmin 3.

graphicPack: can't parse preset "LOD -0.5 (Sharper): invalid operator found in expression: -0.5

The issue is coming from the file XenoxbladeX_NegativeLOD\rules.txt. If I delete the file/folder the error is gone. See screenshot for details.

Thanks guys!
![lod -0 5 sharper error](https://user-images.githubusercontent.com/15003329/50392222-7a112980-071a-11e9-9f5b-514f92d69b8a.png)

**Comment by skalfate** [comment]
Oh thanks for tacking that down. I fixed one of these a while ago and I was seeing it creeping up again in peoples cemu logs.

I'll take care of it. Thank you.

**Comment by skalfate** [comment]
It has been fixed. I'll go ahead and close this issue. Thank you.

**Comment by JakeLD** [comment]
You guys rocks thanks!
