### ISSUE TITLE
New Super Mario Bros U FancyFX broken

### ISSUE THREAD

**Issue by JOHN30011887** [slashiee/cemu_graphic_packs#321]
the new fancy fx doesnt work correct, turning it on makes all blocks invisible, some turn invisible once you hit them

Turning off fancyfx fixes it, previous graphics pack didnt have this issue
i run at 4k for res and fancyfx

![cemu_2019_01_10_01_33_08_617](https://user-images.githubusercontent.com/12979984/50940220-f7a59b00-1477-11e9-9226-a80622f25db6.png)

**Comment by getdls** [comment]
Probably fixed in latest commit, please close if OK.

**Comment by JOHN30011887** [comment]
yip all fixed, thanks alot :)
