### ISSUE TITLE
cemu1.15.1e JPN XCX 60FPS slow motion

### ISSUE THREAD

**Issue by houlaiqingtian** [slashiee/cemu_graphic_packs#328]

**Comment by Xalphenos** [comment]
What FPS are you getting?  

It’s a static mod. If you can’t maintain 60 FPS you will get slow motion. Any deviation from 60 will result in a commensurate change in gamespeed.

**Comment by houlaiqingtian** [comment]
> 你得到什么FPS？
> 
> 这是一个静态mod。如果你不能保持60 FPS，你会得到慢动作。任何与60的偏差都会导致游戏速度发生相应的变化。

this should be the reason. can you make one dynamic FPS like botw ?

**Comment by getdls** [comment]
I won't.. unless Xalphenos feel like doing some serious hacking i suggest closing this with : won't fix.

There's already issues with cinematic cut scenes running camera pans at 30 fps while characters update at 60. Getting that to frame-rate match on dynamic updates is not something I'm willing do... even for free beer.

**Comment by Crementif** [comment]
Until someone makes a FPS++, a static FPS is all we'll get.

I'll look into adding different FPS presets to the repository, though.
