### ISSUE TITLE
BOTW FXAA error c1104

### ISSUE THREAD

**Issue by Mr6686** [slashiee/cemu_graphic_packs#332]
Hi, in 1.15.2d, 1.15.1e and 1.15.0e I got:
[13:06:01] Compile error in shader f14bb57cd5c9cb77. Log:
[13:06:01] 0(1068) : error C1104: too many parameters in function call

[13:06:03] Compile error in shader 0f2b9ee517917425. Log:
[13:06:03] 0(1020) : error C1104: too many parameters in function call

Nvidia FXAA is grayscale too (no problem with noAA and nativeAA)

[log_1.15.2d.txt](https://github.com/slashiee/cemu_graphic_packs/files/2836683/log_1.15.2d.txt)

**Comment by skalfate** [comment]
Sorry for the delay.  I wasn't aware. I think we had someone on discord have the same issue. We found out that he had changed cemu user interface language to a language that uses commas vs periods in numbers, for example $100.00 vs $100,00

Exzap said that he would have to fix the issue sometime in the future.

Meanwhile. try reverting cemu ui language to English and or any other language that uses periods in numbers.

**Comment by Mr6686** [comment]
Reverting language to Default (English) fixed it. Thanks for info

**Comment by Mr6686** [comment]
When using FXAA stars become black
![sans titre](https://user-images.githubusercontent.com/8061617/52902852-fefa5a00-3216-11e9-8f0d-6d3063f9c769.jpg)
Don't know if I open new issue for this or rename this topic
