### ISSUE TITLE
XCX Squished Characters in Menu's with Resolution pack enabled 1.15.2d

### ISSUE THREAD

**Issue by OldManKain** [slashiee/cemu_graphic_packs#334]
When you use any resolutions setting from the graphics pack Including the games default resolution 720p,  The models in the menu become horizontally squished.  Gameplay models are fine.

No Resolution Pack
![image](https://user-images.githubusercontent.com/47503099/52536846-6e9eaf80-2d14-11e9-9613-a6c9b8f513d6.png)

With Resolution Pack enabled, any resolution.
![xcxstreched](https://user-images.githubusercontent.com/47503099/52536786-e15b5b00-2d13-11e9-95e3-bcdf0338beef.png)

**Comment by getdls** [comment]
It's a side effect of having widescreen patches in the resolution folder. 
Delete patches.txt in the resolution graphic pack and it should return to normal.

**Comment by OldManKain** [comment]
> It's a side effect of having widescreen patches in the resolution folder.
> Delete patches.txt in the resolution graphic pack and it should return to normal.

Thank you very much,  Now it's also keeping a steady 60FPS instead of dropping to 55 or so.

**Comment by getdls** [comment]
Resolved i guess...
