### ISSUE TITLE
there are no packages for the Taiko no Tatsujin

### ISSUE THREAD

**Issue by Tavo000** [slashiee/cemu_graphic_packs#336]
Hello! good morning! in this version 1.15.2d all Taiko no Tatsujin games already work but their graphic packages are not available, I hope they can be added soon !!

**Comment by skalfate** [comment]
Hopefully, I dont have the game. I would of. If you want you can post some screenshots and we can make a good enough pack from that.

If you choose to. Run cemu with the game, and upload your cemu log here so we can grab the title id from it.

And more importantly, run the game, in cmeu user interface click Debugger --> View Texture Cache info.

Resize that window from top of the screen to the very bottom of your screen. Scroll all the way down and take a snapshot of that window and upload that here.

**Comment by Tavo000** [comment]
Hello, taking!
https://www.mediafire.com/file/gc6ixjp3ii8vnke/for_graphics_packages.rar/file
there are 4 games!

the first one is called

Minecraft Wii U Edition [AUMPDUDU]

Taiko no Tatsujin Atsumete? TomodachiDaisakusen! [BT3JAFAF]

Taiko no Tatsujin Tokumori! [BT9JAFAF]

Taiko no Tatsujin Wii U version! [AT5JAFAF]

**Comment by getdls** [comment]
[Taiko no Tatsujin.zip](https://github.com/slashiee/cemu_graphic_packs/files/2876952/Taiko.no.Tatsujin.zip)
This should work for all JP versions, please test and report back.

**Comment by Tavo000** [comment]
tested in all 3 with all resolutions! and it's perfect! thank you for your good work

**Comment by getdls** [comment]
Validated by reporter, closing.
