### ISSUE TITLE
Wind Waker Contrasty

### ISSUE THREAD

**Issue by Pastah** [slashiee/cemu_graphic_packs#337]
When enabling Contrasty (which looks far superior to the original) the water in the distance acts weird when moving the camera (some kind of flickering). The higher you go, the more noticeable it is. An example of the problem can be seen here (https://imgur.com/a/SvkSkDc), notice the water in the distance. Also, at certain camera angles, all of the water gets affected by it.
I've uploaded another sample, if the first one isn't clear. https://imgur.com/a/7cjvou6

**Comment by getdls** [comment]
Issue reproduced, I'll see what I can

**Comment by skalfate** [comment]
Thanks for that little app @getdls . Best of luck. I am chasing other botw stuff on discord. You should really be there bud.

**Comment by Pastah** [comment]
@getdls thanks for looking into this! Please take your time :)

**Comment by getdls** [comment]
I've mitigated the flashing and AO issues.. 
They aren't 100% fixed, bloom covers up some transition... but the grading should be close enough pass epileptic warning standards. 

Please test and close if OK.

**Comment by Pastah** [comment]
Haven't seen anymore flashing, thank you!

**Comment by getdls** [comment]
@skalfate I dropped by discord.. it looked more like BOTW support central, but every good comment was gone after one screen of text scrolling by. 

It's a nice place to shitchat, but for tracking purposes its horrible.  I still don't get why there's no proper issue tracker for Cemu.

**Comment by Sirius902** [comment]
@Pastah Can confirm that the issue is not fixed!
![water](https://user-images.githubusercontent.com/10891979/54169227-10f2a580-442f-11e9-8325-c64be6ac77ca.png)

**Comment by Pastah** [comment]
@Sirius902 Try using the default contrasty preset, the others seem to suffer more from it. Getdls told it's not completely fixed. It's like 99% gone for me.

**Comment by auwsmit** [comment]
@Pastah While it's true that using the default mostly fixes this issue, it doesn't help those of us who prefer the other presets. To my eyes, the default Contrasty is very, very subtly different from the original and has almost as much strong bloom, which is my main gripe with the HD graphical changes.

I would almost prefer to play with "Gamecube style"/"Less sky bloom" or not play at all. For me personally, this renders the HD remake *far* less playable, and makes Contrasty effectively useless unless I want to tolerate most of the ocean flickering for most of the game. Not sure this should be considered closed or entirely resolved until the other options are fixed.
