### ISSUE TITLE
RULE: [Breath of the Wild] No edits allowed on the graphic packs

### ISSUE THREAD

**Issue by slashiee** [slashiee/cemu_graphic_packs#34]
This rule will be in affect until March 3rd.

**Comment by Tsume** [comment]
Lol. This is so petty.

**Comment by BreakPoints** [comment]
Not really, it's not playable yet

**Comment by slashiee** [comment]
I'd just rather not have anyone dealing with graphic packs get in trouble over a game that people shouldn't have access to yet.

**Comment by BreakPoints** [comment]
Ah, people got hold of it. Makes sense, we know how Nintendo can be

**Comment by slashiee** [comment]
Alright, you guys can now make sure that the main menu works 100% on resolutions besides 720p.
