### ISSUE TITLE
Character invisible in DKC Tropical Freeze

### ISSUE THREAD

**Issue by d-apps** [slashiee/cemu_graphic_packs#342]
Cemu Version; 1.15.3b
CemuHook Version: 0.5.7.0

Specs:
CPU - Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz | 4 Threads | AVX+
Ram - 8.00 GB
OS - Windows 10 Last Build
HDD - 1 TB
GPU - Intel HD Graphics 5500 (driver updated)

I am using graphic packs 360p for DKC Tropical Freeze but the character is invisible, I can see his shadow and the game is playabe (fps), I don't have any graphic issues with other games (Mario Kart 8, NSMU, Zelda...).

Is it possible to help me with this issue?

![Screenshot](https://user-images.githubusercontent.com/20110433/54395552-de46e800-468e-11e9-85e2-de32256053e6.png)

**Comment by Crementif** [comment]
We don't fix problems that are caused by iGPU bugs. Cemu doesn't support iGPU's officially either.
