### ISSUE TITLE
[Mario Kart 8] Fail upscaling in multiplayer selection screen.

### ISSUE THREAD

**Issue by Learsodin** [slashiee/cemu_graphic_packs#343]
here the image: 
![mario kart 8](https://user-images.githubusercontent.com/48462414/54476994-23c7fa00-47e2-11e9-98a2-9ff291f31eaa.png)

**Comment by Learsodin** [comment]
here another link with the same image: [https://imgur.com/9f482d5f-1910-4128-bc7b-c7d490c85b7e]

**Comment by Crementif** [comment]
![Picture of the fix](https://user-images.githubusercontent.com/26669564/54761648-c58c8400-4bf2-11e9-83f3-12ffbccc94d2.png)

Fixed that thing in the latest update. Feel free to test if everything still works though, upscaling these players required quite a few textures and this game tends to be quite complicated with each player mode.
