### ISSUE TITLE
[Mario Kart 8] Shadows resolution fails in 3 and 4 players

### ISSUE THREAD

**Issue by Learsodin** [slashiee/cemu_graphic_packs#344]
here the image: 
![mario kart 8 2](https://user-images.githubusercontent.com/48462414/54477003-3d694180-47e2-11e9-82aa-234ff2389c91.png)

**Comment by Crementif** [comment]
![image of the fix](https://user-images.githubusercontent.com/26669564/54762037-9fb3af00-4bf3-11e9-9588-547f88ad4f23.png)

Also fixed this issue in the latest pack update! Interesting trivia, the game uses the same shadow map for multiple players if they're in close proximity, likely to reduce the load of rendering many players at the start of the race on 4 screens.
