### ISSUE TITLE
BOTW: Visual glitch in NVIDIA Defogger/DeBloom V2

### ISSUE THREAD

**Issue by Silver324** [slashiee/cemu_graphic_packs#345]
After turning on the Nvidia Defog V2, during day time in the game, several objects appear with a visual grey/white flashing the instant they are being rendered ("popping-in").
I made 3 pictures of that; look at the center:
1st pic: The unrendered rock
2nd pic: Rock is being rendered with a glitchy-looking visual flashing
3rd pic: The rendered rock

![1](https://user-images.githubusercontent.com/48661905/54502137-647e5b00-4929-11e9-8afe-526644aa7027.png)
![2](https://user-images.githubusercontent.com/48661905/54502138-647e5b00-4929-11e9-8632-8974bb1f040f.png)
![3](https://user-images.githubusercontent.com/48661905/54502140-647e5b00-4929-11e9-8bf6-cb6cad3cf123.png)

Especially if you ride through the fields on a horse, these flashings look quite terrible.
During game's night-time, this phenomenon seems to disappear as the objects become rendered in a darker way.
After turning the Defogger off, the problem disappears.
In addition, I merely used the Resolution mod scaled up to Full-HD to make better pictures, but it's defenitely the defogger's fault.

**Comment by Alstura** [comment]
Yeah this is remnant effect of removing fog.  If we can find the shaders used while drawing objects popping-in then we can defog them. But right now pop-in is "fog matched" to the distance where it first draws.... and yup this looks exactly like that.

**Comment by Crementif** [comment]
I'll close this issue since this pack isn't actually on this github. Feedback is preferably send via the discord channel to Altros in the official Cemu discord's graphic pack channel.

Besides that, it seems like this is a pretty difficult thing that has to do with things being drawn in, which isn't particularly easy at the moment.
