### ISSUE TITLE
[Request] Add these 48:3 aspect ratio resolution packs

### ISSUE THREAD

**Issue by HenrikoMagnifico** [slashiee/cemu_graphic_packs#346]
I am one of Cemu users who play using a 48:9 aspect ratio (triple monitor setup). However, I could not find any updated versions of the resolution packs for Breath of the Wild that supported the 48:9 aspect ratio. Therefore, I made an updated version myself with 5 new resolutions that support the triple monitor setup (From 1080p to over 5K). These are not only fun to play with, but are also great for taking ultra-wide screenshots when paired with the FOV mod.

I do not know how to use GitHub, so I'm adding the request here in hope of some more knowledgable user merging these changes to the master branch.

Thanks!

https://pastebin.com/5uvWJ4aF

**Comment by Crementif** [comment]
Have you tested all of these resolutions? Some resolutions don't work, there's a few specific rules you have to keep in mind.

**Comment by skalfate** [comment]
Yeah henriko, just to clarify,

You only added the resolution presets right, and didnt change anything else? 

Also the fifth variable regarding $heightfix, make sure to set those to either 0 or 1.

First set cemu general  options to stretch, and then run the 48/9 resolution and see if there is a black bar at the bottom while in-game.

If with $heightfix 0 there is no black bar, then we can add the resolutions.

**Comment by skalfate** [comment]
I could only the test the first 3, the 3rd one was making get like 2-3 fps at best. I'll just add 3 out of the 5.

I will go ahead and close this and the commit will happen soon after.
