### ISSUE TITLE
Need help with modificate swap map Splatoon mod

### ISSUE THREAD

**Issue by pdurant768** [slashiee/cemu_graphic_packs#350]
Hello, 
Please help me, I need all address for all dojo map in patches.txt

I need all dojo address for my project

This file patches.txt mentionned only 5 address.

I searched in log files but not find there information.

Please help me and give the all Dojo address.

Thank you

**Comment by slashiee** [comment]
would need to look into finding the addresses first

**Comment by pdurant768** [comment]
Ok and thank for your answer.
I looked in the log files but I did not find them.

I only have 4 addresses located in the file patches.txt.

0x100F9CE0 -> Fld_Tutorial00_Ttr
0x100F1244 -> Fld_Plaza00_Plz
0x10101F38 -> Fld_World00_Wld
0x100F8E74 -> Fld_StaffRoll00_Stf
0x100F8958 -> Fld_ShootingRange_Shr

??????? --> Fld_Crank00_Dul
??????? --> Fld_Warehouse00_Dul
??????? --> Fld_SeaPlant00_Dul
??????? --> Fld_UpDown00_Dul
??????? --> Fld_SkatePark00_Dul

My project is to play on local dojo on all the maps. Thanks to your work I almost reach the goal

**Comment by slashiee** [comment]
only found Fld_Crank00_Dul at 0x1002785C

**Comment by pdurant768** [comment]
Hello slashiee and thank you for your reply
I did not answer because I was traveling

I test the next line in the patches.txt file but it does not work
0x1002785C = .string "Fld_Tutorial00_Ttr" #Tutorial [Original: Fld_Tutorial00_Ttr]

The map is always Urchin Underpass in the dojo.
The Swap doesn't work

yet this line works for Octo Valley
0x10101F38 = .string "Fld_Crank00_Dul" #Octo Valley [Original: Fld_World00_Wld]

another idea used 2 stings value :
.string "Fld_Crank00_Dul" = .string "Fld_World00_Wld"
but don't work again

Please help me or give me the work method for find maps address

Thank you again for your help

**Comment by pdurant768** [comment]
> only found Fld_Crank00_Dul at 0x1002785C

Need help Slashiee  Please

**Comment by slashiee** [comment]
Try replacing it with cheat engine

**Comment by pdurant768** [comment]
Hello Slashiee,

Yes it's work !!!!!
But...
I want to use map swap and not cheat engine.
In cheat engine I change the value of address but it is not fixed and changes at each reboot game it's normal.
How to determine fixed address of Fld_Crank00_Dul 
how did you determine the other addresses in the patches.txt file

I almost reached my goal 

Thanks Slashiee

**Comment by pdurant768** [comment]
Hi Slashiee, I still can not determine the static address of Fld_Crank00_Dul.
My project works I miss it more than that
Need Help Please !!!

**Comment by slashiee** [comment]
I have no time to really look into it for the next few months
