### ISSUE TITLE
[WWHD] Lacking resoutions lower than 1280x720

### ISSUE THREAD

**Issue by mrbluru** [slashiee/cemu_graphic_packs#353]
Sorry if this isn't the place for it but I can't seem to find a reason why for example Wins Waker HD had it's resolutions under 720p removed. When I try to manually alter the rules file the resolution option disappears from the graphics pack menu altogether

**Comment by Morph1984** [comment]
Had someone test lower resolutions in that PR, seems to have worked

**Comment by slashiee** [comment]
@Morph1984 is it fine to re-open that PR and push it to master?
