### ISSUE TITLE
[Tokyo Mirage Sessions ♯FE] Static FPS doesn't support the Japanese game

### ISSUE THREAD

**Issue by yamanobe96** [slashiee/cemu_graphic_packs#354]
![無題](https://user-images.githubusercontent.com/46581513/56366469-304ed080-622e-11e9-904b-8bdefc2ccb43.png)

1. Graphic breaks when resolution is increased with latest version 1.15.4
There is no problem with 1.15.3

2. Static60FPS does not work well in Japanese version
This is good if it is possible, but can you cope?

**Comment by Crementif** [comment]
As of http://cemu.info/patreon/changelog/cemu_1_15_5.txt, the graphical bugs are fixed. Changed the title to reflect your other problem.

Could you please send us a screenshot of the View RPL Modules window in Cemu's Debug toolbar?

**Comment by yamanobe96** [comment]
![無題](https://user-images.githubusercontent.com/46581513/56430906-ed126180-6302-11e9-808e-de11f3043d34.png)

Screen shot
Thank you

**Comment by yamanobe96** [comment]
Please.
Is it difficult to handle static 60 FPS?

**Comment by Crementif** [comment]
Sorry, was away for a few days.

The 60FPS patch is for the unpatched EU version only. Since I don't own the game, I'm not sure what the difference/meaning is of the "uncensored" thing. I would recommend you search that, there's probably some patch out there that'll change your files to be uncensored.

**Comment by yamanobe96** [comment]
I am an unpatched JP version
It was known from the folder name that only the EU version is currently supported, but I thought it would be nice if I could get it compatible with the JP version.
