### ISSUE TITLE
[Xenoblade Chronicles X] Graphics Packs not working

### ISSUE THREAD

**Issue by NameBlah** [slashiee/cemu_graphic_packs#355]
Hi,

The following Graphics packs don't seem to do anything:

XenobladeX_mod_BladeGainTicketsFromMissions (tested both the DLC setting and TA setting with 0 results)
XenobladeX_NoOfflineTag (tag remains)

The latter is more of an annoyance, but the first one is really bad since the only way to get reward tickets quickly is by beating the big bosses and those are not available offline. :(

Using Cemu 1.15.3b

**Comment by yamanobe96** [comment]
I am Japanese version 1.15.4 but NoOfflineTag is working properly.
How does your language work with 1.15.4?

**Comment by NameBlah** [comment]
I don't have 1.15.4, where can I find that. and how do I get that to work with my current progress?

Also, I managed to remove the offline tag by placing a modded cpk file in the games content folder.

**Comment by Xalphenos** [comment]
Post your log.txt after running the game.

The latest version of cemu can always be found on the cemu homepage.

**Comment by NameBlah** [comment]
I tried 1.15.4, but with that one I have new issues. The XenobladeX_mod_MusicSkellFlightDisabled now wont work. The resolution mod works better with this one, but the music one is more preferable. 

I have removed the graphics packs that don't work such as the offline tag one and the mission one. Weird thing is. Ever since I used the forceweather mod I now have incredible lag in the game. Like 5 fps in some cases, but after being in an area for a bit the lag goes away mostly. 

I have removed the weather mod, but the issue remains. Also the log.txt has not been updated ever since I used the forceweather mod.

[log.txt](https://github.com/slashiee/cemu_graphic_packs/files/3108440/log.txt)

**Comment by NameBlah** [comment]
When starting the game the shader loading screen is not there, it just loads the game. Wtf...

**Comment by Xalphenos** [comment]
You need cemuhook for graphics packs that rely on rpx patching.

**Comment by NameBlah** [comment]
Yes, I have cemuhook
