### ISSUE TITLE
Black textures in BOTW with cemu 1.15.5c

### ISSUE THREAD

**Issue by andreluizgit** [slashiee/cemu_graphic_packs#356]
only Black textures in BOTW with cemu 1.15.5c + Latest cemu_Graphic_packs

I found the bugged pack : 

**CLARITY** --> Black Textures / Lights / Shaders in BOTW

**Comment by Crementif** [comment]
Should be fixed by https://github.com/slashiee/cemu_graphic_packs/commit/c152f7a8bbd61fc53114c25bd476413a3a94b373
