### ISSUE TITLE
error in graphic packs of taiko no tatsujin

### ISSUE THREAD

**Issue by Tavo000** [slashiee/cemu_graphic_packs#366]
hello from the latest versions of cemu in the graphic packs of taiko does not appear the images in the game when you set the resolution 2k or in 1080p when I deactivate the graphic packs and I leave it in 720 if it works here some photos

**Comment by Tavo000** [comment]
https://www.mediafire.com/view/wvd52l80ydiartt/hgjghj.png/file
https://www.mediafire.com/view/i2wjjq5vi776561/Sin_t%EDtulo.png/file

**Comment by slashiee** [comment]
this is due to a texture sharing the same format of a graphic pack override, nothing that can be done unfortunately.
