### ISSUE TITLE
[XCX] CEMU 1.15.6 graphics packs didn't work

### ISSUE THREAD

**Issue by KimixZahard** [slashiee/cemu_graphic_packs#367]
I try on the update version (48 US) with 60 FPS, change resolution and remove offline text. All of these didn't work. But it works well for version below 1.14 except 60 FPS. Do you have any idea? I try to read "https://github.com/slashiee/cemu_graphic_packs/issues/235" but no solution for me. Please advice. Thank you.

**Comment by henglinli** [comment]
Me too, and also "offline tag" did not work too.

**Comment by Crementif** [comment]
Everything above 1.14.0 required a new version of graphic packs, hence why these don't work on versions older than that. If you want the older version 2 graphic packs, they're still available from the [website](https://slashiee.github.io/cemu_graphic_packs/).

**Comment by KimixZahard** [comment]
I have downloaded the new graphic packs for version 1.14 and above(version 3) from your website but it doesn't work for Cemu version 1.14 and above. So I use graphic packs (version 2) with Cemu version 1.13, it work well for function "change resolution" and "remove offline text" but it still show only 30 FPS. I don't know why I can't use function 60 FPS. Do you have any idea?

**Comment by Crementif** [comment]
You need the latest updates for these mods since we don't support any game versions prior to that.
