### ISSUE TITLE
[Wind Waker HD] Shadow graphic pack not working due to missingtitle IDs

### ISSUE THREAD

**Issue by ap3nr0ts** [slashiee/cemu_graphic_packs#368]
Hi! I think the title IDs of the shadow graphic pack for Wind Waker HD need fixing. They only include one version of Wind Waker HD and need to be edited before you can use them in, for instance, a PAL version of the game.

**Comment by Crementif** [comment]
Thanks for reporting the issue, it should now work on european and japanese copies.
