### ISSUE TITLE
Add version 3 Fist of the North Star resolution pack

### ISSUE THREAD

**Issue by anseesaw** [slashiee/cemu_graphic_packs#370]
it just useful in the version lower than cemu 1.13x！i like this game

[Definition]
titleIds = 0005000010116600
name = "beidou - 1080p"

version = 2

[TextureRedefine] # tv

width = 1280

height = 720

overwriteWidth = 1920

overwriteHeight = 1080

[TextureRedefine] # q-res
width = 320
height = 180

overwriteWidth = 480
overwriteHeight = 270

[TextureRedefine] # q-res 2
width = 322
height = 182

overwriteWidth = 483
overwriteHeight = 273

#o-res

[TextureRedefine] # o-res
width = 160
height = 90

overwriteWidth = 240
overwriteHeight = 135

[TextureRedefine] # o-res 2
width = 162
height = 92

overwriteWidth = 243
overwriteHeight = 184

[TextureRedefine] # gamepad
width = 854
height = 480

#overwriteWidth = 1920
#overwriteHeight = 1080

how to change this code to the high version，for example to cemu 1.15.7c。

Would you give me a hand ？

**Comment by Crementif** [comment]
Sadly enough, it's far more complicated then just using the old pack in the new version. I'll look into creating a resolution pack for it today or tomorrow.

**Comment by anseesaw** [comment]
> 可悲的是，它比使用新版本中的旧包装要复杂得多。我会考虑今天或明天为它创建一个解决方案包。

You are so kind,Thanks a lot!

**Comment by Crementif** [comment]
Should be available now! 👍
