### ISSUE TITLE
[Xenoblade Chronicles X] Graphics Packs not working

### ISSUE THREAD

**Issue by JobLeite** [slashiee/cemu_graphic_packs#373]
Good night dear!

Could anyone help me to know why Graphic Pack Mods is not working?

Cemu 1.15.6c
Cemuhook 1115

**Comment by Xalphenos** [comment]
You'll need to provide a log.txt at a minimum for troubleshooting.  That said the discord is far more appropriate for general troubleshooting.

**Comment by JobLeite** [comment]
how to draw a log.txt?

**Comment by JobLeite** [comment]
[log.txt](https://github.com/slashiee/cemu_graphic_packs/files/3239529/log.txt)

would it be this?

**Comment by Xalphenos** [comment]
You need to update your game.
