### ISSUE TITLE
Improvements to organization of the graphic packs in the UI (suggestion)

### ISSUE THREAD

**Issue by Geroyuni** [slashiee/cemu_graphic_packs#375]
These are two separate suggestions, which I personally think should make things less confusing.

1. [**Put groups above toggles instead of mixing them alphabetically**](https://files.catbox.moe/49xqkt.png)
This is similar to what's [usually done with folders and files](https://files.catbox.moe/shpxwa.png).

2. [**Order BOTW's GPU specific workarounds in a clearer manner**](https://files.catbox.moe/z0j7hq.png)
Add GPU specific workarounds to its own group, and start the name of the workaround with the GPU.

**Comment by Crementif** [comment]
Change the packs to be ordered in a different manner according to your suggestion. Definitely a good suggestion.

We can't change the order of the graphic packs (without a lot of work on our end which would look pretty messy). If you want to see your first suggestion happen, you could file a feature request on [Cemu's bug tracker](http://bugs.cemu.info). Closing this issue therefore.
