### ISSUE TITLE
Breath of the Wild - No cheat working

### ISSUE THREAD

**Issue by hyquoccuong** [slashiee/cemu_graphic_packs#382]
No cheat is working for me on Cemu 1.15.9c and game EUR version

**Comment by Xalphenos** [comment]
post your log.txt after running the game if you want help.  Though this is not the proper forum for troubleshooting.

**Comment by hyquoccuong** [comment]
[log.txt](https://github.com/slashiee/cemu_graphic_packs/files/3325535/log.txt)
Here is my log.txt
Could you please let me know where to ask question about cheat on this game, I'm using comunity lastest graphic packs so I think I can ask here

**Comment by Xalphenos** [comment]
You don't have cemuhook which is required, at least for now, for any packs that require patching.  Cheats, UW mods, and FPS++ are examples of this.  

Issues here on github are for actual issues with the graphics packs listed here.  This place is not for troubleshooting user problems.  Your issue has nothing to do with graphics packs or this repo at all.  You simply don't have cemu set up correctly.  The proper place for troublshooting is either the official discord, forum, or reddit.  They can all be found on the emulators website.  Linked below. 

http://cemu.info/community.html
