### ISSUE TITLE
XCX offline tasks and missions don't work correctly

### ISSUE THREAD

**Issue by vsub** [slashiee/cemu_graphic_packs#389]
Cemu 1.15.10
CemuHook 0.5.7.3
The code enables the squad missions but setting the active preset to anything that normal work in a half wrong way

For example I set the preset to "Gain more Tickets(x10)"
Fighting the specified enemy - ok
Completing the task - ok
Completing squad mission - ok
Exchanging tickets for items...now there is something wrong here

The cost subtracted is also multiplied by the preset I choose and if the cost subtracted is higher that what I already have,I will get 9999 tickets

Have 1000t => buy something that cost 1000 => your tickets don't become 0 but 9999

**Comment by lasyan3** [comment]
Hi, this is a known issue. I'm working on separate this mod in 2: one for the offline missions and one for the Reward Tickets multiplicator.
