### ISSUE TITLE
[Wind Waker HD] Picto-Box Workaround

### ISSUE THREAD

**Issue by Vladimir-1799** [slashiee/cemu_graphic_packs#393]
I've made a workaround for Lenzo quest. He will now accept any picture you show. Works for EUR and USA versions. I'm just not sure how to upload it here.
[WindWakerHD_PictoBox.zip](https://github.com/slashiee/cemu_graphic_packs/files/3473085/WindWakerHD_PictoBox.zip)

**Comment by RokkumanX** [comment]
@Vladimir-1799 

Thanks for this!

One question though would this work for Treasure Chart 24 when you have to take a picture of [Ezlo and the woman](https://i.ytimg.com/vi/_x7sq4EF-Yc/hqdefault.jpg) at night which you have to show the gossip women?
