### ISSUE TITLE
XCX cheat to keep your skell when it is destroyed.

### ISSUE THREAD

**Issue by vsub** [slashiee/cemu_graphic_packs#395]
This address(main character skell) "1B777909" works like this when value is set
0 - the skell is ok
1 - the skell is destroyed

It doesn't seem to be the correct address because the game sometimes reverts it back to 1 and lock my charter inside the skell and I can't do anything other that restarting the game.

To get your skell back when the value is locked to 0,you have to do one of those things
1.Change your equipment and when you exit the screen,it will magically appear next to you
2.Teleport somewhere
3.Use the option to go back to the skell(you will literally be teleported to the location where it was destroyed...this can be used kinda like "jump to location")
4.You die...which actually acts as if you teleported.

XCX 1.0.1U
It's always been annoying me that if the skell is destroyed,I have to go back to get it(the money is not the problem if I don't have any insurances left,I have more than 100k million credits I get without cheating and there is nothing to use them for)

**Comment by lasyan3** [comment]
Added a new mod which restore your skell (as long as you made perfect score at the Soul Challenge or you ave insurance left) here: https://github.com/slashiee/gfx_pack/commit/13f637907885b4ce251148af4e61c7f8aa3cf543
