### ISSUE TITLE
[TwilightPrincessHD] FancyFX causing cobwebs to disappear

### ISSUE THREAD

**Issue by indeed-a-genius** [slashiee/cemu_graphic_packs#396]
Spider webs are not visible with FancyFX enabled.

Screenshot showing where it should be visible, with FancyFX disabled.
![2019-08-30 20_45_22-Cemu 1 15 12b - FPS_ 30 00  OpenGL   NVIDIA GPU   ShaderCache_ 3bc226d1   TitleI](https://user-images.githubusercontent.com/18271528/64044474-2edfce00-cb67-11e9-9250-969d9280da28.png)

Save attached, just go north in the Faron Woods until cave entrance. 
[00050000.zip](https://github.com/slashiee/cemu_graphic_packs/files/3561131/00050000.zip)

**Comment by getdls** [comment]
Should be OK with the latest commits, please update gfx pack and close if fixed.

I managed to eff up a copy paste between private an public while experimenting with format conversion. It may be a good idea to check for updates on TPHD the next few days.

On a side note, great report, both screenshot and save state. 

![image](https://user-images.githubusercontent.com/25286924/64074345-27750d80-ccaa-11e9-91d0-9c435f984b88.png)
