### ISSUE TITLE
[BotW] Bloom & blur fixes don't appear to work at 1080p resolution

### ISSUE THREAD

**Issue by Cheesypoofy1** [slashiee/cemu_graphic_packs#399]

**Comment by nathanvdh** [comment]
I can confirm - I am also experiencing this issue. However others in the Cemu discord are not experiencing it, despite also being on cemu 1.15.15b and the latest graphics packs

**Comment by Cheesypoofy1** [comment]
https://www.reddit.com/r/cemu/comments/ddugjm/botw_bug_odd_rendering_in_menus/

**Comment by slashiee** [comment]
able to reproduce on 1080p as well, will be checking non-integer resolutions
![2019-10-07_19-47-47](https://user-images.githubusercontent.com/15317421/66363547-7b26e680-e93b-11e9-800a-e9f2e0bc89ae.png)
![2019-10-07_19-48-03](https://user-images.githubusercontent.com/15317421/66363551-7d894080-e93b-11e9-91b8-4adea1644cd3.png)

**Comment by slashiee** [comment]
Try the latest version (446f066d48fc4d6b390fcfabb9a55513c1505d06) and see if it's fixed, it works on my end

**Comment by nathanvdh** [comment]
Yep seems to have solved it for me too! Good work.

**Comment by Crementif** [comment]
Ah, happy to see this fixed already 😉
