### ISSUE TITLE
Please add 1360x768 resolution

### ISSUE THREAD

**Issue by tirafesi** [slashiee/cemu_graphic_packs#406]
I tried to add the resolution myself by adding a entry to `Cemu 1.15.20\graphicPacks\downloadedGraphicPacks\BreathOfTheWild_Resolution\rules.txt` but this messed up the lighting / shadows, so I guess simply adding a new preset isn't enough?

```
[Preset]
name = 1360x768 (85:48)
$width = 1360
$height = 768
$gameWidth = 1280
$gameHeight = 720
$heightfix = 1
```

**Comment by slashiee** [comment]
Have you tried messing with the height fix?

**Comment by slashiee** [comment]
Can't seem to fix the height issue atm, will probably look at it at a later time.
