### ISSUE TITLE
[BOTW] "LWZX Crash" graphics pack resulting in crash

### ISSUE THREAD

**Issue by shinrax2** [slashiee/cemu_graphic_packs#407]
hi

with the new vulkan backend the "LWZX Crash" introduces a reproduceable crash when talking to cherry in the alkala institute

when deactivating the pack the crash dissappears

i double checked to make sure its not another graphics pack

**Comment by slashiee** [comment]
This pack is not required for Vulkan as you pretty much need GX2DrawDone enabled at all times in order for the backend to even work.

**Comment by shinrax2** [comment]
since GX2DrawDone is now enforced on maybe adding the (OpenGL) that and a rendererfilter might be a good idea
