### ISSUE TITLE
Graphics packs crash Mario Kart 8

### ISSUE THREAD

**Issue by PatiB87** [slashiee/cemu_graphic_packs#414]
Hey,

I narrowed down issues I currently have to the graphics packs. Whenever I turn on ANY graphics pack, CEMU quits to desktop after 2-4 races.

The background:

I am able to play Mario Kart 8 perfectly well - until it just exits to desktop after 2-3 races.
The log.txt does not even contain issues about this!

I'm on an GTX 1060 6G, most recent Nvidia driver, use most recent Windows 10 and run a Core i5 9600k. Nothing is overclocked.

My settings are:

- Single core recompiler
- GPU buffer cache accuracy: low
- VSync on
- Full sync at GX2DrawDone off
- Precompiled Shaders disabled

Messing with these settings didn't change my issue so I left it at these since I read at several sources, that these are the best settings for Mario Kart.

I also tried different CEMU versions: 1.16.1 and older 1.15.16 and 1.15.20.
Same issue in all the versions!

I also tried to delete ALL the shader caches and played a lot of tracks in order to rebuild the shader cache now on 1.16.1
=> Still the same issue (plus a lot of shader compile stutter, of course!).

I know for SURE that I never had these Issues around 1.15.15-20. It may have glithced here and there but never just quit to desktop!

BUT, what I now figured out by A LOT of trial and error:
The issue is coming from the graphics packs!!!
I tried:
- Resolution
- Shadow Resolution
- 4p/60FPS Mod

It ALL perfectly reproduces this behavior.

Any idea what can cause this?
Maybe I will try to find some old versions of graphics packs somewhere...

**Comment by PatiB87** [comment]
I randomly now downloaded a kinda old version of the graphics pack (version 277) from where I think I remembered that I never had crashes and for now it seems to be stable.

So my current conclusion is: the most recent Mario Kart 8 graphic packs contain severe bugs that crash the game randomly!

**Comment by Crementif** [comment]
You should:
1). Give us your log.txt file after it crashes. You can use [pastebin](https://pastebin.com/) to send it here.
2). Try enabling graphic packs one by one and narrow it down to the one graphic pack that it crashes. The bug potentially being somewhere in 3 graphic packs doesn't really help us here.

P.S. The old graphic packs thing sounds very irrelevant and is probably not a real fix. Since the 3-4 player 60FPS pack was added to the graphic packs relatively late, it might be that.

**Comment by PatiB87** [comment]
Hi, thanks for the reply.

1): As I said: "The log.txt does not even contain issues about this!"
2): As I said: All three packs (Resolution, Shadow Resolution, 60fps Mod) individually cause the crashing.

Nope, it's a workaround and should give you a hint what changed since 277 and what therefore could be the reason of the bugs.

**Comment by Crementif** [comment]
Actually, some people pointed out that you should have `Full sync at GX2DrawDone()` enabled for Mario Kart 8. That's your problem here, not some weird graphic pack issue. And you should use the Single core recompiler too since the multi-core recompilers will also add random crashes.

**Comment by PatiB87** [comment]
Hey,
as I said: 

> My settings are:
> Single core recompiler
> [...]
> Full sync at GX2DrawDone off
> [...]
> Messing with these settings didn't change my issue [...]

Meaning: I tried all possible settings for those two settings as well but in the end swiping full sync off was recommended everywhere for Nvidia cards. Anyhow: I can safely say that graphic packs are the issue and specifically those newer than 277.

I can also try more recent ones that 277 if you have a recommendation.

But a request from my side regarding this: please take this seriously and don't try to discuss this away. I spent almost my whole Sunday testing and narrowing down the cause, can safely reproduce the crashing and also work as professional IT project manager including QA testing so I guess my testing was at least not TOO unorganized. :)

**Comment by TeamCemu** [comment]
Turning 'Full sync at GX2DrawDone()' off is a hack and will lead to random crashes in many games, including MK8. As it is common with race conditions the frequency of these crashes may be affected by other settings or graphic packs, which may give the wrong impression that there is a correlation.

Turn on full sync and your problem is solved.

**Comment by PatiB87** [comment]
Ok, I will try it again and report back! Thanks for the reply.

**Comment by Crementif** [comment]
So, any news? Can we close this issue?

**Comment by PatiB87** [comment]
Will play a big session tomorrow with 4 players and report then.

**Comment by PatiB87** [comment]
It did not crash!! :) But I had to turn the graphics packs off in 4 player mode due to slow down.
And even without them here and there the game seemed to sometimes skip ahead half a second! Did you ever hear of that? It never happened in single player! 
Could this be cpu bottleneck? should I try dual/triple core instead of single?

**Comment by slashiee** [comment]
dual/triple core also cause crashes in MK8, and in-fact Cemu forces the game to be single-core via game profiles.

**Comment by PatiB87** [comment]
Do you happen to know something about the skipping? :/ I had 60 fps yet the game wasskipping forward half a second here and there...

**Comment by slashiee** [comment]
I have never heard of the game skipping before...
