### ISSUE TITLE
MK8 resolution graphics pack not being applied on character select screen in multiplayer

### ISSUE THREAD

**Issue by sanjaysatoji** [slashiee/cemu_graphic_packs#415]
I'm using the 1.16.1 vulkan and graphics packs v587. In Mario Kart 8 I'm using the 4k graphics pack. On the character select screen for multiplayer, the models appeared to be rendered at the native resolution rather than 4k. Ingame in multiplayer it is indeed 4k, and in the singleplayer character select screen it is indeed 4k.

**Comment by Crementif** [comment]
Thanks for reporting this issue! It should be upscaled if you update your graphic packs.

**Comment by Crementif** [comment]
![Picture of the fix](https://user-images.githubusercontent.com/26669564/71784692-5a336780-2ff6-11ea-8a3d-29bfacf5c171.png)
