### ISSUE TITLE
1.16.1 Vulkan v590 - Extreme 8.0x Shadow Resolution crashing every game

### ISSUE THREAD

**Issue by sanjaysatoji** [slashiee/cemu_graphic_packs#416]
Every game I have tried with Extreme 8.0x Shadow Resolution instantly crashes as soon as shadows would be displayed. The only exception is that 8.0x shadow pack seems to be working in the character select screen in MK8, but then crashes as soon as you load ingame.

Ultra 4.0x Shadow Resolution is working fine though in all games though.

I'm running a AMD Radeon VII so vram constraints should not be an issue. OpenGL 8.0x shadow packs are working. Thanks for your time

**Comment by Serfrost** [comment]
This isn't an issue with the graphicPack, it's an issue with Vulkan being unstable and still in testing phases, especially when it comes to RAM and VRAM consumption and stability.

Please just use what works best for you.

**Comment by slashiee** [comment]
Vulkan is still an experimental backend, so crashes occurring are not surprising. 8x shadows are quite overkill, so we'll probably be dropping support for them. Even 4x shadows can be overkill for certain games, Splatoon no longer gets to the hub due to the addition of squid sister shadows.

**Comment by slashiee** [comment]
With 736e6cf876c5f16da118dd87f9b0fa2fcbaccea8 I've reduced the max scale of shadows to 400%. Please note that on 1.16.1 you should stay at 200%, as 300% can still crash.
