### ISSUE TITLE
5k (5120x2880) res option gone from recent graphics packs

### ISSUE THREAD

**Issue by DaveACG** [slashiee/cemu_graphic_packs#422]
This started happening around a couple of weeks ago, updates to the graphics packs removed the 5K resolution option for all games. Is there a reason for this - was that resolution causing problems?

**Comment by slashiee** [comment]
This was a recent change as I thought it was a bit overkill, then I was told that we probably have enough overhead that it should still work fine. I would expect it to be added before we start working on v5 packs.

**Comment by DaveACG** [comment]
Thanks for the response. Yep on just my 1660 (gddr5) it's not a bottleneck at all for most games at that res, Mario games/Bayonetta run at 5k/60fps with my GPU barely breaking 70% utilization for example.

**Comment by Crementif** [comment]
We've added 5k and 8k resolutions back in, so I'm closing this issue
