### ISSUE TITLE
Version 5 graphic packs

### ISSUE THREAD

**Issue by slashiee** [slashiee/cemu_graphic_packs#425]
Any work on version 5 graphic packs will be done on a separate repository here: https://github.com/slashiee/gfx_pack

**Comment by slashiee** [comment]
@getdls Just want to make you aware of this repository for v5 packs.

And for others who are seeing this, I apologize for having this repository locked for that long.

**Comment by getdls** [comment]
Killed my remote fork, its too different to merge with main branch. I'll keep that one private and do a new fork from current v5

Patches are easy to merge back, I'll do them first, second fixes.

**Comment by IVy-The-Wusky** [comment]
How do the version 5 gfx packs work or differ from the version 4 ones? Or do they have any new features? Sorry, idk if I'm supposed to know about it, but I'm just kinda interested.
