### ISSUE TITLE
Super Mario 3D World Graphic Pack Resolution Issue

### ISSUE THREAD

**Issue by Peduls** [slashiee/cemu_graphic_packs#426]
When changing the resolution via the graphic pack for Super Mario 3D World certain areas (specifically areas where it's raining) look like this. It doesn't happen every time but seems to be more likely after playing for long periods of time. Happens on OpenGL and Vulkan.

How it's supposed to look
![screenshot_3](https://user-images.githubusercontent.com/34750422/79825190-9f856600-8355-11ea-9689-31d20b419b53.png)

How it looks when the problem occurs.
![screenshot_4](https://user-images.githubusercontent.com/34750422/79825214-af9d4580-8355-11ea-86b9-79a3b4c2af71.png)

**Comment by getdls** [comment]
reminder to check for format conversion issues before closing
