### ISSUE TITLE
Xenoblade Chronicles X [AX5#01]

### ISSUE THREAD

**Issue by DiBurkle** [slashiee/cemu_graphic_packs#43]
![4k](https://cloud.githubusercontent.com/assets/27022896/24814209/2410f4b2-1ba7-11e7-9213-77e820854584.png)

Using the 4k pack, there are no issues in the  2k and 1080p ones, used cemu 1.7.3d to 1.7.4d

**Comment by BreakPoints** [comment]
I can confirm this happens with the current 4k pack

**Comment by slashiee** [comment]
I thought @Darkemaste removed this issue already?

**Comment by slashiee** [comment]
Should be fixed with 16bf40e
