### ISSUE TITLE
Bayonetta 2 Dof removal request

### ISSUE THREAD

**Issue by JOHN30011887** [slashiee/cemu_graphic_packs#432]
I was wondering if it would be possible to remove dof (and bloom) if its possible please?
In some cutscenes its really broken as shown in this image
![Cemu_2020_04_26_03_23_47_547](https://user-images.githubusercontent.com/12979984/80295847-267b7980-876e-11ea-8b99-f41bbbd2edba.png)

I saw a note few days ago on the updated bayonetta 2 graphics pack saying Cutscene DOF is LOD based, should not have been scaled.
I thought that was a fix but wasn't, so guess that was for something else, so i thought id ask here

Great job on the 60fps cutscenes :)

**Comment by getdls** [comment]
Glad you liked the 60fps pack, I was a bit lucky that the code path didn't break more stuff. 

There wasn’t enough space to be more specific about LOD, it was meant to explain why there were some shaders “missing”  Most WiiU games fake DOF in various ways, as full sampling is GPU expensive. The old graphics pack scaled one such instance incorrectly  so the “bokeh” effect was squished horizontally. 

I won’t be doing anything about the bloom/DOF, it works pretty well in most scenes and you probably will break brightness/gamma when you remove it. Putting that in the official repo is just asking for bug reports.

If you’re really curious, take a look at the old pack, and comment out the output part. It should get you started on what needs to be done.

**Comment by JOHN30011887** [comment]
Ah ok thanks for info.

Yeah it does work well in most scenes i noticed.
I guess will have to wait till the emulator gets more accurate with lighting and dof as i wouldnt know what to edit to mess around with it myself and if it will break things then yeah i'll just wait.
