### ISSUE TITLE
Bayonetta 2- Resolution pack causes lighting corruption in Vulkan

### ISSUE THREAD

**Issue by DaveACG** [slashiee/cemu_graphic_packs#437]
Can't recall when this happened exactly, have tried several older Cemu releases (as well as latest Patreon builds) so pretty sure it's a graphics pack update issue. OpenGL is unaffected, this is Vulkan only. 

Basically now with Vulkan, selecting a resolution other than default in Bayonetta 2 removes the lighting from the centre of the screen, only visible outside of a circle that pans with the player. I've tested with a combination of other mods, disabled all others and it's only the resolution setting that causes this.

eg:
![bayonetta 2_5k](https://user-images.githubusercontent.com/36821207/81511043-7ae13600-92e4-11ea-93b3-5cba49569cd4.jpg)

**Comment by Crementif** [comment]
I was reminded by the reddit thread that this issue was occuring, but after just trying, I can't actually replicate this. I only have a square as shadow, but that might just be a completely different problem.  So that's quite interesting. I would like to know what GPU driver you are using (I'm using the [Vulkan developer drivers](https://developer.nvidia.com/vulkan-driver) at the moment)
![shadow issue](https://user-images.githubusercontent.com/26669564/82253059-8372e580-9950-11ea-8ea4-6de6f17ce891.png) and the contents of the log.txt file after you've encountered this problem, which you can upload to a service like pastebin.com.

**Comment by DaveACG** [comment]
Latest Nvidia hotfix (445.98). I'll try the Vulkan beta drivers then.

**Comment by Crementif** [comment]
Forgot to mention that I was using 1440p, the shadow resolution pack to 200% and the portal workaround.

**Comment by slashiee** [comment]
No point in shadow resolution being enabled ATM since shadows don't work form Bayo 2

**Comment by DaveACG** [comment]
Ok, tried the Vulkan beta drivers, and matched your settings (1440p, 200% shadows, Portal fix) - no change.

![image](https://user-images.githubusercontent.com/36821207/82255753-2c0a5080-9923-11ea-9d49-42a300728dc8.png)
![image](https://user-images.githubusercontent.com/36821207/82255767-30366e00-9923-11ea-9104-4ab9f681aa6c.png)
![image](https://user-images.githubusercontent.com/36821207/82255798-42181100-9923-11ea-9129-c9234a67373f.png)
![image](https://user-images.githubusercontent.com/36821207/82255806-45ab9800-9923-11ea-9ecc-abdf20495039.png)
[log.txt](https://github.com/slashiee/cemu_graphic_packs/files/4646466/log.txt)

**Comment by Crementif** [comment]
Ended up being able to replicate it (I actually wasn't using the latest graphic packs, oops...) and fixed a core issue which caused bugs with Vulkan which was related with the ultrawide patch that was added.

Let me know whether this fixed your issue for you too! Thanks for letting us know about it.

**Comment by DaveACG** [comment]
Indeed it is fixed! Thanks very much.

**Comment by Crementif** [comment]
Awesome! 😁

**Comment by DaveACG** [comment]
Hmm, don't know if this is related to your graphics pack, but now Bayonetta 2 consistently is crashing with an '[22:24:11] Vulkan-Info: Pipeline creation failed to due to invalid shader' now. OpenGL is fine, this is just under Vulkan, have played it extensively under Vulkan without incident, only switched when this shadow bug came up. Was fine for about 1/2 hour, now can't get past this area:

![image](https://user-images.githubusercontent.com/36821207/82846082-22e62a00-9eb5-11ea-960d-7f60aad05c77.png)

Tried with usual mods/packs, and only with the res pack activated. Same thing. Also deleted all shader/pipeline caches and started fresh, no diff.
[log.txt](https://github.com/slashiee/cemu_graphic_packs/files/4679043/log.txt)


Log.txt attached. Let me know if you think it's related, otherwise I'll post it in the cemu reddit.

**Comment by Crementif** [comment]
Well, this issue thread is mostly meant for graphic pack issues. It's easier if you were to join the [official Cemu discord](https://discord.gg/5psYsup) if you haven't done so already, and that you'd mention your problem in the troubleshooting channel. I might even be able to help you there.

Also, I noticed that you send your log.txt file from OpenGL that didn't crash, so it doesn't really clarify anything.

**Comment by DaveACG** [comment]
Ah, whoops. Ok Discord it is.
