### ISSUE TITLE
Xenoblade Chronicles X: Overdrive Countdown is twice as fast with 60 FPS.

### ISSUE THREAD

**Issue by Maxunit** [slashiee/cemu_graphic_packs#439]
Heyo :)

I just played around with the latest gfx pack release and enabled the 60 FPS Patch for XCX and noticed, that most seems to be running fine except for the Overdrive Countdown. It gets reduced twice as fast compared to the vanilla 30 fps.

Cheers,

Maxunit

**Comment by lasyan3** [comment]
Hi, I also noticed this some days ago and released a fix in the v5 repo : https://github.com/slashiee/gfx_pack/commit/e09bcb3c79fc755a5e50faf0e514f6f54a9aba63
