### ISSUE TITLE
Fast Racing Neo - Resolution Scaling Broken after Pack v660

### ISSUE THREAD

**Issue by DaveACG** [slashiee/cemu_graphic_packs#441]
The ultra Widescreen mod introduced in Pack V660 for Fast Racing: Neo seems to have affected 16:9 resolution scaling, no longer functional in that release and all subsequent packs to date. Tried 4K and 5120x2880, stays at 720. v659 was last pack scaling was functional.

Affects both OpenGL and Vulkan. Cemu Versions tested: 1.19.0D + 1.18.2.

**Comment by slashiee** [comment]
Try the latest graphic pack update, it should work now.

**Comment by DaveACG** [comment]
Thanks! Working.
