### ISSUE TITLE
Xenoblade X  60 FPS pack issue

### ISSUE THREAD

**Issue by samaelmakato** [slashiee/cemu_graphic_packs#451]
After testing the updated XCX 60 fps pack, I found it works pretty well even in soul voice QTE. However, in Overdrives (OC gears) 

mode, the elapsed time accelerates , at  least as twice as the elapsed time without 60 fps pack . 

Is there any way to solve it?

Many thanks~

**Comment by Crementif** [comment]
The same issue was made https://github.com/slashiee/cemu_graphic_packs/issues/439 . Until we merge V5 graphic packs (which should be soon™️) you can download a work-in-progress version of the fixed pack [here](https://cdn.discordapp.com/attachments/292733452590120961/710196681416769556/XenobladeChroniclesX_60FPS.zip).

**Comment by samaelmakato** [comment]
Dear crementif,

Thanks for you quick response~   The WIP version of 60 fps pack for XCX
works perfectly.

I will check the whether there is the same issue before posting in GitGub.

Appreciate your help

Best Regards,

makato

Crementif <notifications@github.com> 於 2020年6月26日 週五 下午8:57寫道：
