### ISSUE TITLE
Xenoblade Chronicles X

### ISSUE THREAD

**Issue by AKKypher** [slashiee/cemu_graphic_packs#460]
Some of the Graphic Pack is no longer working, such as dlc missions offline etc. Still is very stable and runs very well. it's just the Graphic Pack issues. most of the graphic pack still works well.

**Comment by Crementif** [comment]
What version of the game are you running? It says the version in the title bar.

**Comment by AKKypher** [comment]
Version 48

**Comment by lasyan3** [comment]
Try the mods [from this link](https://www.reddit.com/r/cemu_xenoblade/comments/g4duku/xcx_mods_updated_for_v5_graphic_packs/). They are updated for version 5, whereas packs in the current repo are in the old version 4 (they will be updated to v5 once the repo owner allows it).
