### ISSUE TITLE
Bayonetta: Reduced Bloom

### ISSUE THREAD

**Issue by leleobhz** [slashiee/cemu_graphic_packs#47]
Hello!

Can you apply the c9b60c9de9de5e03_0000000000000079_ps_source.txt from http://www.mediafire.com/file/hol1eaku1vu121x/Bayonetta_reducedBloom.zip to Bayonetta profile to fix the "all white screen" issue at Bayonetta?

Thanks!

**Comment by slashiee** [comment]
blind..
https://github.com/slashiee/cemu_graphic_packs/tree/master/Workaround/Bayonetta_Bloom
