### ISSUE TITLE
Anisotropic Filtering Packs that apply filtering to all Texture Samplers

### ISSUE THREAD

**Issue by DaRkL3AD3R** [slashiee/cemu_graphic_packs#474]
I'm interested in modifying anisotropic filtering graphics packs so that they would apply AF to all surfaces, possibly filtering out certain ones (in the case of Breath of the Wild with the cascaded shadow map problem). The reason being is when we are limiting application to only specific sets of textures, we will miss out on many surfaces that could greatly benefit from higher quality texture filtering. When running at very high resolution, the blurring from trilinear filtering becomes painfully obvious. An example of the effects these kinds of selective restrictions can have is attached below.
![Cemu_2020_10_13_00_57_55_996](https://user-images.githubusercontent.com/29787293/95817686-1e999c80-0cf0-11eb-930d-79df250f0bff.png)

Excuse the gamma shift from Rivatuner image capture but focus your attention on the dirt decals spread around the top of the tower's floor. In Vulkan with the AF pack enabled, it is clearly missed in the filtering process and looks extremely blurry and low detail. In comparison with OpenGL and driver enforced AF applied to all surfaces, it is much more detailed and impressive.
![Cemu_2020_10_13_01_15_45_910](https://user-images.githubusercontent.com/29787293/95818375-b77ce780-0cf1-11eb-8929-3c65c5066570.png)

**Comment by DaRkL3AD3R** [comment]
I've had better success so far by swapping out the depth = 83 filter with width =, height = and using a variety of common texture resolutions like 64x64, 128x128, 256x256, 512x512 and 1024x1024. However after having dumped textures from a general scene in the game, I can see that there are so many different resolutions that aren't just power of 2 based and even some that are not square but rather rectangular.

Is there a wildcard character I can use to pass through for the TextureRedefine test for width and height so it can just apply to all surfaces? And then have a separate redefine to filter out the shadow maps specifically?

**Comment by vladkosi** [comment]
I am using this with no visible glitches or bugs:

`[TextureRedefine]`
`formats = 0x31,0x431,0x33,0x433,0x34,0x234,0x35,0x235`
`overwriteAnisotropy = 16`

**Comment by Crementif** [comment]
Oh, I swear I had send a reply for this already. But yeah, you can indeed just not use any filters (like `width`, `format` etc.) in a `[TextureRedefine]` and still use the overwrites.

But I think you should probably use *some* filters at the very least so that you don't put everything through the filter since it could cause unwanted side effects.

We do plan on filtering more stuff in the official pack so that we also include that so that everything, where it makes sense, is filtered. This was just the demonstration pack that was made before the feature got launched.

**Comment by DaRkL3AD3R** [comment]
I'm pretty sure the first thing I tried was this:

[TextureRedefine]
overwriteAnisotropy = 16

and it didn't work. There was no visible anisotropic filtering on any surface. Am I missing something there?

**Comment by Crementif** [comment]
Hm, maybe I'm wrong. I don't see why it wouldn't work, but I guess it might be an arbitrary limitation.

If you really wanna filter everything you could use the most generic filter which would be `tilemodes = 2, 3, 4`. `1` is usually videos, so you don't wanna apply AF to those. I'm not 100% sure if tilemode 2 and 3 are a thing either, but I know that 4 is a majority of a game's textures.

**Comment by slashiee** [comment]
Feel free to try 172026f16e96e40ca0abf11685efa3bf683e47d2 to see if it fixes your issue

**Comment by DaRkL3AD3R** [comment]
So far it seems to match my custom settings, I haven't found any surfaces that are definitively missing it and need AF. I'd consider this case closed, and if I ever come across any such surfaces in need of it I'll be sure to reply to this issue with screenshots of it. Thanks.
