### ISSUE TITLE
[Request] BotW FPS++ modifications

### ISSUE THREAD

**Issue by Colmines92** [slashiee/cemu_graphic_packs#477]
Hi.
I do not know about the others, but in the specific case of my PC when I use FPS ++ the game reaches half or less the FPS that I specified. Let's say if I select 30 FPS the game runs at 10 or 15, if I select 60 FPS it runs at 20 or 25, if I select 120 FPS it runs me at 30 (sometimes a little more).
The thing is, when I'm running at 30 despite running at a steady, smooth speed, it looks like it's not at the speed it should be.

Well, what do I propose?
Last night I modified the FPS limit, adding a 240 FPS setting and Dynamic speed, adding a 64 average. When using those settings my game still runs at 30 FPS. Using these settings the game still runs at 30 FPS (I have it locked to that limit from the drivers of my video card), but the thing is that now it runs as if it were at 60FPS, smoothly and there is not even any problem with the cinematics. And almost all the time it remains at 30 FPS.

I don't know if this will work for all PCs or just low-end PCs like mine, but I think these settings would be worth taking a look at and trying them out.

My specs:
MotherBoard: B85-D3H (4th gen)
Processor: Intel core i5 4460
RAM: 6 GB
VideoCard: nVidia Geforce GTX 650

**Comment by Crementif** [comment]
It really sounds like your using an old update of the game or some wrong settings. The FPS++ don't require any tinkering to actually work. Could you maybe send your log.txt file while having the game opened?
