### ISSUE TITLE
[Request] BotW Full sync at GX2DrawDone() fix?

### ISSUE THREAD

**Issue by Colmines92** [slashiee/cemu_graphic_packs#478]
I don't know if what I'm proposing can be achieved using graphic packs, but I suppose it can.

As you know this function: GX2DrawDone () reduces the performance of games, in my case to a great extent.

With this option disabled I can play pretty smooth, most of the time at 30 FPS. The big drawback that I see disabling this option is when using the Sheikah stone camera (it does not recognize objects).

My proposal is if by means of a new graphic pack you could know when you are using the camera, and if it is detected that it is being used, use the GX2DrawDone () function regardless of whether it is disabled or not and when you stop using it, return to its previous state.

Just a proposal.

**Comment by Crementif** [comment]
Having full sync at GX2DrawDone() disabled is already a hack that's eventually gonna be removed. The hack only works on OpenGL too, and Vulkan gets more or equal performance with better accuracy.

I have some plans for adding far better performance improvement options in the form of graphic packs, however.
