### ISSUE TITLE
CEMU 1.8.0, BOTW and updated graphics Pack cause more crashes

### ISSUE THREAD

**Issue by frankyfife** [slashiee/cemu_graphic_packs#53]
Without graphic pack BOTW runs fine, but enable the 5k (or 4k or FHD) cause the game to crash every 2-3 Minutes.

Is this a know issue?

I'm on a nVidia 1080ti with latest drivers.

**Comment by slashiee** [comment]
Please post this in #38.
To answer your question: I have heard that graphic packs caused a bit of more crashing in previous versions of Cemu, but not to the extent of this. Nothing that we can do about it, unfortunately.
