### ISSUE TITLE
21:9 Graphic Packs

### ISSUE THREAD

**Issue by slashiee** [slashiee/cemu_graphic_packs#56]
# Mario Kart 8
[1080p Graphic Pack](https://github.com/slashiee/cemu_graphic_packs/tree/master/Quality/MK8_1080pUW)
[2160p Graphic Pack](https://github.com/slashiee/cemu_graphic_packs/tree/master/Quality/MK8_2160pUW)

![MK8_1080pUW](https://user-images.githubusercontent.com/15317421/30625217-c5c18690-9d76-11e7-9369-bcd1e9375851.png)

**Comment by getdls** [comment]
Address differs for me, (pic Nvidia, 8Gb). But aspect ratio for looks correct (ie squishy for 16:9 screen)

![21aspect](https://cloud.githubusercontent.com/assets/25286924/26527280/b2f9a622-4390-11e7-8863-12a9358aa5cc.png)

**Comment by getdls** [comment]
Wind Waker same appoach, 
![ww21](https://cloud.githubusercontent.com/assets/25286924/26531261/dd68b380-43e5-11e7-842c-02f9431ff9f5.png)
 0x1004aaf0

**Comment by slashiee** [comment]
# Super Mario 3D World

use same instructions for Mario Kart 8. Will make a better graphic pack later

## 2560x1080

```
[Definition]
titleIds = 0005000010145c00
name = "SM3DW - 1080p (21:9)"
version = 2

[TextureRedefine]
width = 1280
height = 720
overwriteWidth = 2560
overwriteHeight = 1080
```
![image](https://cloud.githubusercontent.com/assets/15317421/26531439/00a6bda8-439e-11e7-8676-a5049d0e9351.png)

**Comment by getdls** [comment]
# Tropical Freeze
Same approach as Mario Kart, 6th value on the list.


## 2560x1080 alt 5120x2160
```
[Definition]
titleIds = 0005000010137F00,0005000010138300,0005000010144800
name = "Donkey Kong Country: Tropical Freeze - (21:9)" #
		
[TextureRedefine] # game rendering resolution
width =	1920	
height = 	1080	
formatsExcluded = 0x41A # exclude the intro background texture 		
overwriteWidth = 2560 # 5120
overwriteHeight = 1080 # 2160

**Comment by getdls** [comment]
Just realized I spent 2h re-inventing the GBA temp thread.. -_-  *doh*   I'm done, let them do it instead. 

https://gbatemp.net/threads/release-cemu-wii-u-emulator.399524/page-1047

**Comment by slashiee** [comment]
@getdls I'd continue on, Esppiral is a total ass when it comes to him sharing the codes. Won't even share BotW, which is very high demand

**Comment by slashiee** [comment]
# Super Smash Bros. for Wii U

using memory searcher:
- go into a match and pause
- search for 1.77777777 (float)
- choose third to last address
- divide width by height (for 2560x1080 do 2560/1080)
- set the address to what you got from resolution dividing

## 2560x1080

```
[Definition]
titleIds = 0005000010110E00,0005000010145000,0005000010144F00,ffffffffd72e798a
name = "Super Smash Bros. - 1080p (21:9)"
version = 2

[TextureRedefine] # tv
width = 1920
height = 1080
overwriteWidth = 2560
overwriteHeight = 1080

[TextureRedefine] # half-res
width = 960
height = 540
overwriteWidth = 1280
overwriteHeight = 540

[TextureRedefine] # q-res
width = 480
height = 270
overwriteWidth = 640
overwriteHeight = 270

[TextureRedefine] # o-res 
width = 240
height = 135
overwriteWidth = 320
overwriteHeight = 235

[TextureRedefine] # half-res 2
width = 120
height = 67
overwriteWidth = 160
overwriteHeight = 67

[TextureRedefine] # q-res 2
width = 60
height = 33
overwriteWidth = 80
overwriteHeight = 33

[TextureRedefine] # o-res 2
width = 30
height = 16
overwriteWidth = 40
overwriteHeight = 16

[TextureRedefine] # o-res 3
width = 8
height = 1
overwriteWidth = 11
overwriteHeight = 1
```
![image](https://cloud.githubusercontent.com/assets/15317421/26532393/7ce4b698-43b4-11e7-868b-29b5bffda18c.png)

**Comment by slashiee** [comment]
# The Legend of Zelda; Breath of the Wild

https://www.reddit.com/r/cemu/comments/6drjb0/guide_to_play_your_cemu_games_in_ultrawide_219_or/di64tcd/

## 2560x1080

```
[Definition]
titleIds = 00050000101C9300,00050000101C9400,00050000101C9500
name = "The Legend of Zelda: Breath of the Wild - 1080p (21:9)"
version = 2

[TextureRedefine] #TV
width = 1280
height = 720
formatsExcluded = 0x008 # exclude the intro background texture
overwriteWidth = 2560
overwriteHeight = 1080

[TextureRedefine] #TV2
width = 1280
height = 721
overwriteWidth = 2560
overwriteHeight = 1082

[TextureRedefine] #TV3
width = 1280
height = 608
overwriteWidth = 2560
overwriteHeight = 912

[TextureRedefine] #TV4
width = 1152
height = 648
overwriteWidth = 2304
overwriteHeight = 972

[TextureRedefine] #half-res1
width = 640
height = 360
overwriteWidth = 1280
overwriteHeight = 540

[TextureRedefine] #half-res2
width = 640
height = 290
overwriteWidth = 1280
overwriteHeight = 435

[TextureRedefine] #half-res3
width = 640
height = 288
overwriteWidth = 1280
overwriteHeight = 432

[TextureRedefine] #q-res1
width = 320
height = 180
formats = 0x001		#Scale depth masking, not bloom
overwriteWidth = 640
overwriteHeight = 270

#[TextureRedefine] #q-res2
#width = 320
#height = 145
#overwriteWidth = 640
#overwriteHeight = 218

#[TextureRedefine] #q-res3
#width = 320
#height = 144
#overwriteWidth = 640
#overwriteHeight = 216

[TextureRedefine] #o-res1
width = 160
height = 90
formats = 0x001		#Scale depth masking, not bloom
overwriteWidth = 320
overwriteHeight = 135

[TextureRedefine] # O
width = 80
formats = 0x001		#Scale depth masking, not bloom
height = 45
overwriteWidth = 160
overwriteHeight = 68

[TextureRedefine] # M
width = 80
height = 44
overwriteWidth = 160
overwriteHeight = 66

[TextureRedefine] # G
width = 40
height = 22
overwriteWidth = 80
overwriteHeight = 33

[TextureRedefine] #fog
width = 720
height = 360
overwriteWidth = 1440
overwriteHeight = 540
```
Havent gotten this 21:9 hack working yet. Maybe 1.2.0 doesn't work with it?

**Comment by slashiee** [comment]
# Yoshi's Woolly World

using memory searcher:
- go into a stage
- search for 1.77777777 (float)
- choose any address in the range of 0x2608
- divide width by height (for 2560x1080 do 2560/1080)
- set the addresses to what you got from resolution dividing until it works
- revert the other addresses that didn't work back to 1.77777777
- redo process for every new stage

## 2560x1080

```
[Definition]
titleIds = 0005000010131F00,0005000010184E00,0005000010184D00
name = "Yoshi's Woolly World - 1080p (21:9)"
version = 2

[TextureRedefine] # tv
width = 1280
height = 720
overwriteWidth = 2560
overwriteHeight = 1080
```
![image](https://cloud.githubusercontent.com/assets/15317421/26539323/acc91484-4400-11e7-97c7-b48c13fd610d.png)

**Comment by slashiee** [comment]
# Paper Mario: Color Splash

using memory searcher:
- search for 1.77777777 (float)
- choose third address on the list
- divide width by height (for 2560x1080 do 2560/1080)
- set the address to what you got from resolution dividing

## 2560x1080

```
[Definition]
titleIds = 500001f600900,500001f600a00,500001f600b00
name = "Paper Mario: Color Splash - 1080p (21:9)"
version = 2

[TextureRedefine]
width = 1280
height = 720
formatsExcluded = 0x431,0x001
overwriteWidth = 2560
overwriteHeight = 1080
```

**Comment by getdls** [comment]
GUI scaling, WIP, . I'll stick the file here as I'm away for a couple of days. Needs more shaders, but you get the gist of it from the comment. 

[TheWindWaker_21_9_GUI.zip](https://github.com/slashiee/cemu_graphic_packs/files/1036929/TheWindWaker_21_9_GUI.zip)


![ww21](https://cloud.githubusercontent.com/assets/25286924/26563891/e2d3be06-44d9-11e7-89e1-f34c98278a03.png)

![21aspect2](https://cloud.githubusercontent.com/assets/25286924/26563892/e6cfc9f0-44d9-11e7-9b28-d90734f73cfc.png)

**Comment by slashiee** [comment]
# Splatoon

Tutorial soon, Splatoon is a pain in the ass to do. It does require Cheat Engine though.

## 2560x1080

```
[Definition]
titleIds = 0005000010176900,0005000010176A00,0005000010162B00
name = "Splatoon - 1080p"
version = 2

[TextureRedefine] # tv
width = 1280
height = 720
overwriteWidth = 2560
overwriteHeight = 1080

[TextureRedefine] # half-res alpha
width = 640
height = 360
formatsExcluded = 0x41A,0x431 # exclude obvious textures
overwriteWidth = 1280
overwriteHeight = 540

[TextureRedefine] # squid sisters
width = 1024
height = 576
overwriteWidth = 1536
overwriteHeight = 864

[TextureRedefine] # gamepad
width = 854
height = 480
overwriteWidth = 2560
overwriteHeight = 1080

[TextureRedefine] # multiplayer
width = 848
height = 480
overwriteWidth = 2560
overwriteHeight = 1080

[TextureRedefine] # half-res alpha (multiplayer)
width = 424
height = 240
overwriteWidth = 1280
overwriteHeight = 540
```
![image](https://cloud.githubusercontent.com/assets/15317421/26610897/3bb88292-455f-11e7-8418-50db3a8b955f.png)

**Comment by slashiee** [comment]
# Xenoblade Chronicles X

using cheat engine:
- search hex value 398EE33F, after search is done click next scan
- right click all values, and change the value to 398EE33E
- click next scan, and add the only address to the address list
- press F6, click yes. right click the only item on the list and NOP it. press OK
- change the address value to 26B41740, then afterwards click active

## 2560x1080

```
coming soon
```
image coming soon

**Comment by slashiee** [comment]
# The Legend of Zelda: The Wind Waker HD

alternative patching (HUD scales properly!)
- decompress rpx file using rpl2elf (rpl2elf.exe c-king.rpx c-king21x9.rpx)
- using a hex editor, replace all instances of **39 8E E3 3F** with [another aspect ratio](http://www.wsgf.org/article/common-hex-values) in the rpx file
- boot the modified rpx, you will lose your save data because the rpx hash has changed. nothing can be done about this until exzap changes how saving works

![image](https://user-images.githubusercontent.com/15317421/27321008-843e0458-554d-11e7-935c-8ce84a63bd51.png)

**Comment by slashiee** [comment]
Guess i'll unlock the conversation from here for anyone who finds a UW for another game not mentioned here.

patches.txt instructions are included with cemuhook: cemuhook_182b_0531.zip\graphicPacks\sample_patches.zip\readme_patches.txt

**Comment by slashiee** [comment]
Reformatted all the posts to link directly to the graphic packs themselves.

**Comment by slashiee** [comment]
# Sonic Lost World
[1080p Graphic Pack](https://github.com/slashiee/cemu_graphic_packs/tree/master/Quality/LostWorld_1080pUW)
[2160p Graphic Pack](https://github.com/slashiee/cemu_graphic_packs/tree/master/Quality/LostWorld_2160pUW)

![Uploading image.png…]()

**Comment by winneon** [comment]
I've been using the Breath of the Wild 21:9 pack for the past few days, but I've noticed that the UI is slightly stretched. Now because it's from 16:9 to 21:9, the stretch is very minimal, but it is noticeable, especially with the stamina indicator. Is there a way to fix this?

16:9:

![bt6fsrve8uvg](https://user-images.githubusercontent.com/4269491/31696504-75875d8c-b377-11e7-8910-04227323835d.png)

21:9:

![umg6twap20d0](https://user-images.githubusercontent.com/4269491/31696503-740526ba-b377-11e7-85ae-71ad8b75100c.png)
