### ISSUE TITLE
issue with 1440p graphicPack

### ISSUE THREAD

**Issue by artik** [slashiee/cemu_graphic_packs#58]
After many tests on my 2560x1440 screen resolution, I wanted to test the 1440p graphicpack. Unfortunatly, I have the feeling the resolution is not 1:1 pixel, and everything is blurry (like 720p native resolution). When I try the 1800p or 2160p, game are stunningly sharps. Why the 1440p is not rendering as my 1:1 resolution ?
(I verified and the pack is active)

**Comment by slashiee** [comment]
Cemu issue.
