### ISSUE TITLE
16:10 graphics packs

### ISSUE THREAD

**Issue by rodjun** [slashiee/cemu_graphic_packs#59]
Yes there are people using 16:10 in 2017!

I just would like to know how to calculate the values for a "4k" 1680x1050 graphics pack (so 3360x2100), i already understand that i have to change 1.33333 to 1.6 (1680/1050) on memory but the numbers on the resolution pack look kinda arbitraty, TV2 looks like normal width and height +2, i can't find logic on the other ones, any guide on how to calculate these values? That's for BOTW btw

**Comment by slashiee** [comment]
couple of things:
- for the cheat engine script, change both ultrawide db scans to "CD CC CC 3F"
![image](https://cloud.githubusercontent.com/assets/15317421/26567771/a960dc52-44b2-11e7-8d30-614c0cc4855d.png)
![image](https://cloud.githubusercontent.com/assets/15317421/26567775/b114c940-44b2-11e7-957a-8ee2f40b462d.png)
- i'd just use a regular 4k graphic pack so save yourself the trouble.

**Comment by slashiee** [comment]
guess another thing to note, related to graphic pack editing:
for these aspect ratio packs i usually divide new aspect ratio width by old aspect ratio width. doing that gives me "0.875" (3360/3840 = 0.875) so any width values i multiply by that. so for example fog width is 1890 (2160 x 0.875 = 1890). i do not change height at all
