### ISSUE TITLE
[Tokyo Mirage] Kind of an issue?

### ISSUE THREAD

**Issue by Tsume** [slashiee/cemu_graphic_packs#6]
Could you make one for Tokyo Mirage Sessions #Fe? Performance and Quality? Would be extremely grateful.

**Comment by slashiee** [comment]
Tokyo Mirage doesn't even play properly, it's hard to see anything at all. Once Exzap improves compatibility for this game, I'll consider it.

**Comment by slashiee** [comment]
Eh, screw it. Adding.
