### ISSUE TITLE
4K Graphics Packs aren't True 4K

### ISSUE THREAD

**Issue by shinra358** [slashiee/cemu_graphic_packs#60]
True 4K is 4096x2304. You guys are using the low end 4K which still leaves slight shimmering on background objects. Can you guys add the True 4K resolutions for the games please?

**Comment by BreakPoints** [comment]
The 4K being used in these packs conform to the 4K standard being used by all TVs and the majority of monitors. The reason 3840×2160 is so common is because it fits 4x 1080p exactly. In the case of cemu, most people use 4K resolutions for super sampling, 3840x2160 works best for 1920x1080 (the most common monitor resolution) as every pixel is calculated from 4 pixels. Anything slightly above or below can look inconsistent and blurry as a result.

**Comment by shinra358** [comment]
I play 4096x2304 all the time with pcsx2. I prefer zero shimmering. The image only gets messed up when your window rez is this 4k on a 1080p screen. Internal rez doesnt matter as far that that. 4096x 2304 is also a standard monitor resolution. And with gedosato with pc games, this rez is the highest internal rez ive found to completely eliminate any shimmering in any game. Except ffxiii2 pc, bcuz 5k gets rid of the far back ocean shimmer in that game.

Will changing the values of existing packs with this rez mess up anything glitch wise?

**Comment by BreakPoints** [comment]
Grabbing a graphics pack for the game you want and changing the values should work fine, make sure you adjust half and quarter resolutions if they already exsist.

**Comment by shinra358** [comment]
Ok

**Comment by shinra358** [comment]
unfortunately, it didnt work. just makes jaggies everywhere :(

**Comment by BreakPoints** [comment]
Worse than the current 4K pack? Could you upload a screenshot?

**Comment by shinra358** [comment]
Yes. But again, i edited a pack that new cemu said is old.

On May 30, 2017 3:34 PM, "BreakPoints" <notifications@github.com> wrote:

Worse than the current 4K pack? Could you upload a screenshot?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/slashiee/cemu_graphic_packs/issues/60#issuecomment-304984443>,
or mute the thread

**Comment by BreakPoints** [comment]
When you said "existing" I thought you meant the existing packs in the current batch, sorry. Delete your current graphicspacks and download the latest version.

**Comment by shinra358** [comment]
which do we edit anyway, the normal width and height or the overwritewidth and height?

**Comment by shinra358** [comment]
![mario](https://cloud.githubusercontent.com/assets/3978291/26602425/66a6b414-4551-11e7-87b9-2fcb9187647d.png)
Even putting the high end 4k rez on the new pack creates jaggies everywhere. hard to capture with still shot but you can see them all around mario at 2304p.

**Comment by BreakPoints** [comment]
Are you using the patrion version or the public version 1.8.0b? There was some fix to do with detecting screen size. That might be it? It's difficult to tell from the screenshot as I'm on my phone

**Comment by shinra358** [comment]
Public version

**Comment by BreakPoints** [comment]
Other than trying the different scaling options in the Cemu menu and resolutions, I don't know what to suggest.
Maybe you're expecting too much from 4k supersampling, there's still a bit of aliasing without the scaling algorithm adding some smoothing.
Are you on a 1440p monitor?

**Comment by JOHN30011887** [comment]
@Breakpoints, i agree with what you said but as for all tvs being the 3840x2160 res for 4k aint true, my sony 43inch android tv is 4096x2160

**Comment by BreakPoints** [comment]
@JOHN30011887
Interesting, that's the first one I've heard about, still shouldn't have talked in absolutes.

@shinra358
Next time I'm at a computer I can compare your screenshot with what I get to see if it's anything unexpected. It's odd that your custom resolution doesn't seem to be working.

**Comment by JOHN30011887** [comment]
@BreakPoints no problem, thought id just mention it thats all
@shinra358, looking at your pic it looks like your only running the native 720p res, here is how my rules look like

[Definition]
titleIds = 000500001010ec00
name = "MARIO KART 8 (4K)"
version = 2

# Main Screen Resolution
[TextureRedefine]
width = 1280
height = 720
formatsExcluded = 0x41A,0x431 # exclude the intro background texture, race end background
overwriteWidth = 3840
overwriteHeight = 2160

# Half Res Alpha (and DOF)
[TextureRedefine]
width = 640
height = 360
formatsExcluded = 0x41A # exclude obvious textures
overwriteWidth = 1920
overwriteHeight = 1080

# Quarter Res Alpha (Motion blur effect around edges of screen)
[TextureRedefine]
width = 320
height = 180
formatsExcluded = 0x41A # exclude obvious textures
overwriteWidth = 960
overwriteHeight = 540

# Multiplayer-Mode Resolution (2p)
[TextureRedefine]
width = 640
height = 720
formatsExcluded = 0x41A # exclude obvious textures
overwriteWidth = 1920
overwriteHeight = 2160

# Multiplayer-Mode Half Res Alpha (2p)
[TextureRedefine]
width = 320
height = 360
formatsExcluded = 0x41A # exclude obvious textures
overwriteWidth = 960
overwriteHeight = 1080

# Multiplayer-Mode Quarter Res Alpha (2p)
[TextureRedefine]
width = 160
height = 180
formatsExcluded = 0x41A # exclude obvious textures
overwriteWidth = 480
overwriteHeight = 540

# MKTV output
[TextureRedefine]
width = 960
height = 540
formatsExcluded = 0x41A # exclude obvious textures
overwriteWidth = 2880
overwriteHeight = 1620

# MKTV internal render targets
[TextureRedefine]
width = 960
height = 536
formatsExcluded = 0x41A # exclude obvious textures
overwriteWidth = 2880
overwriteHeight = 1608

# MKTV half res alpha
[TextureRedefine]
width = 480
height = 268
formatsExcluded = 0x41A # exclude obvious textures
overwriteWidth = 1440
overwriteHeight = 804

# Shadows High Res
[TextureRedefine]
width = 1024
height = 1024
formats = 0x005
overwriteWidth = 2048
overwriteHeight = 2048

**Comment by shinra358** [comment]
I know. The pic is having main screen rez at high end 4k though which is
the problem.

**Comment by slashiee** [comment]
when graphic packs came out in 1.7.0, the pre-packaged graphic packs were using that 4k value, so we just went on with it.
