### ISSUE TITLE
BreathOfTheWild_HighResShadows is blurry

### ISSUE THREAD

**Issue by artik** [slashiee/cemu_graphic_packs#61]
After applying the BreathOfTheWild_HighResShadows, shadows look blurry. Same as my previous report: CEMU bug ?

http://i.imgur.com/TUOPHQ7.png

**Comment by slashiee** [comment]
AMD?

**Comment by artik** [comment]
No: Nvidia GPU. BotW 1.2, CEMU 1.8.0b

**Comment by slashiee** [comment]
Odd. No clue. Try raising the resolution

**Comment by artik** [comment]
I'll thanks!
Can be closed

**Comment by artik** [comment]
I reopen. For me it was a bug in the rules.txt. I explain:

1. I took the values in the BreathOfTheWild_HighResShadows pack, and x8 (extreme values, just for the test) = Nothing changed
2. I search many time, and I finally found other values [here](http://gbatemp.net/threads/release-cemu-wii-u-emulator.399524/page-978#post-7169354) that perfectly work for me:

Instead of

> [TextureRedefine]
> width = 360
> height = 360
> formats = 0x005
> overwriteWidth = 2880
> overwriteHeight = 2880

I set

> [TextureRedefine]
> width = 640
> height = 360
> overwriteWidth = 5120
> overwriteHeight = 2880

Now I have perfect sharp shadows: http://i.imgur.com/GwCY6vA.png

Note that the line "formats = 0x005", makes the shadows totally bugged (60% of the screen went black).

After targeting that the value 360x360 is not correct, I lowered the resolution a bit to get back to my 30fps. My final rules.txt:

> [Definition]
> titleIds = 00050000101C9300,00050000101C9400,00050000101C9500
> name = "The Legend of Zelda: Breath of the Wild - Higher Quality Shadows"
> version = 2
> 
> [TextureRedefine]
> width = 720
> height = 720
> overwriteWidth = 2880
> overwriteHeight = 2880
> 
> [TextureRedefine]
> width = 640
> height = 360
> overwriteWidth = 2560
> overwriteHeight = 1440

For me the actual pack doesn,'t work, in any configuration.

**Comment by slashiee** [comment]
of coruse regular packs wont work, you're replacing one of the values (640x360, half resolution of 720p)

**Comment by artik** [comment]
Ok, so you mean I applyied this too "widely"? Sorry it's not clear.
I'm trying a pack that has not consequence on my setup and configuration (and all that I tried), and I found a value that fix this issue and finally does the job. I'd like to understand what I did, and what's wrong in spmething that was not working for me and now is. I there a way to write it properly ?

**Comment by slashiee** [comment]
Your shadow graphic pack is being overwritten by the main graphic pack. Plus, resizing the half res resolution will cause graphical issues (heat waves will not work)

**Comment by slashiee** [comment]
No response in a while, guess I'm closing..

**Comment by slashiee** [comment]
i could try finding the right format. from what i've dumped, these are all the formats that I've seen for 640x360

0x001
0x019
0x816
0x820
0x80e
