### ISSUE TITLE
Problem with Super mario 3D World

### ISSUE THREAD

**Issue by Jeisin15** [slashiee/cemu_graphic_packs#62]
I have an NVidia GPU geforce 210. I can play it but in black and white. With the graphic pack of AA(Antialiasing) Removal, i can see in color But the game is seen in half.
Any help with this?
thanks
![help](https://cloud.githubusercontent.com/assets/29048395/26696772/149e3122-4710-11e7-83ef-32b11eded8ad.png)
![help2](https://cloud.githubusercontent.com/assets/29048395/26696778/1bfcd496-4710-11e7-9529-b17d1eef0091.png)

**Comment by slashiee** [comment]
update graphic drivers. not a graphic pack issue or a cemu issue

**Comment by slashiee** [comment]
actually, you need a new graphic card. AFAIK this one is incompatible with Cemu
