### ISSUE TITLE
Little bugs in the 21:9 Zelda BotW GUI

### ISSUE THREAD

**Issue by artik** [slashiee/cemu_graphic_packs#63]
After applying the 21:9 GUI, there is 2 little bugs on the map:
http://i.imgur.com/2svAtfk.png

External arrow, yellow arrow and markers are out of the map. I think a layer is not set as 21:9 in this part.

**Comment by slashiee** [comment]
this would be for @getdls, not me

**Comment by artik** [comment]
getdls has a git, or can you guide me to post this in the correct place? Tought he was contributor here, that's why.

**Comment by getdls** [comment]
He just did (@getdls) I'll take another poke at it on sunday, but I'm not optimistic. From what I remember its a case of fix one, break the other. 

Shader fixing GUI was more of an experiment. It works for Wind waker, but tbh, it's a bit crap for BOTW. You probably noticed the map  and bloom issues.  Anything else that breaks, videos?

**Comment by artik** [comment]
I wait the perfect 21:9 to start Zelda, so for now, it's only search and improvements ;)
I fixed the blurry shadows this night, just missing this layer fix, and I start it... if you have good news on sunday. Thanks for answer and good luck!

**Comment by JavierSegoviaCordoba** [comment]
Any update about this?
