### ISSUE TITLE
Can you create a graphic pack to fix luma levels ?

### ISSUE THREAD

**Issue by mooms06** [slashiee/cemu_graphic_packs#64]
Hi slashiee,
I think you have seen this thread on Reddit: [[suggestion] Fix Luma levels](https://www.reddit.com/r/cemu/comments/6f258w/suggestion_fix_luma_levels/)

Do you think you can make a graphic pack for BOTW to change the luma levels to 0-255 ?
I think you would make a lot of happy with it.

Edit: if it's possible, the graphic pack should only affects the actual 3D open world an not the menus, because they will look too dark (at least that's what I experimented with ReShade).

Regards.

**Comment by slashiee** [comment]
This is not possible via graphic packs. Plus the luma levels being like this is pretty much accurate emulation.

**Comment by slashiee** [comment]
sorry for another ping @getdls 

might be a job for you, i only know how to adapt shaders from old format to new format, not how to edit new ones completely

**Comment by getdls** [comment]
Zelda contrasty, If it  works, plz commit. 
[BreathOfTheWild_Contrast.zip](https://github.com/slashiee/cemu_graphic_packs/files/1051835/BreathOfTheWild_Contrast.zip)

It looks like this shader has another performance path, but it's nothing I can reproduce.

**Comment by getdls** [comment]
*doh* close and comment isn't comment. Please close once this has been tested..

**Comment by mooms06** [comment]
Thank you for taking care of this getdls !

I can only test on nvidia.
It works indeed, but I have the feeling it's not the same as using the "levels" in ReShade, where you can see it add more contrast but also more vibrant colors.

It's hard to compare since we need to restart cemu to enable/disable graphic pack, and because of the dynamic weather of the game.

I've tried to read the script, but I'm not sure to understand which line(s) I should uncomment to try modifying the levels instead of the gamma.

Also, if I understand the script, you've added a part of the NoAA graphic pack, any issues if I have the latter already enabled ?

**Comment by getdls** [comment]
Version 2 uploaded, should be simpler to use just change the top 4 values: 

```
const float gamma = 0.85; // 1.0 is neutral 0.85 suggested. Botw is already colour graded at this stage
const float exposure = 1.4; // 1.0 is neutral 1.4 suggested
const float vibrance = 0.55;  // 0.8 or higher and ppl will call you a sweetFx noob. 
const float crushContrast = 0.004; // 0.0 is neutral. Very small increments suggested. 0.002 
```

I don't recommend using the "levels" part of the shader, they just crush top/bottom for no good reason, but to activate them uncomment the following lines:
```

Header
/*
const float floor = 16.0 / 255; 
const float scale = 255.0/(235.0-16.0);
*/

Body

//vec3 fColour = (fColour.xyz - floor) * scale;  //uncomment this if really want to scale 0-255->16-235..
```

**Comment by slashiee** [comment]
**No.**

https://www.reddit.com/r/cemu/comments/6f258w/suggestion_fix_luma_levels/dihf4e7/

**Comment by slashiee** [comment]
I think I will add the contrast graphic pack to the repo if it's ready to go @getdls

**Comment by getdls** [comment]
I'll do a less agressive default setting and commit tonight
