### ISSUE TITLE
[Multiple] Underscaling width breaks 3D graphics

### ISSUE THREAD

**Issue by Valkirie** [slashiee/cemu_graphic_packs#65]
Hey guys, just a note here to let you know that 360/540p graphic pack for SUPER MARIO 3D WORLD is broken and cause all models to disappear.

**Comment by slashiee** [comment]
Can confirm, happens for me as well.
![image](https://user-images.githubusercontent.com/15317421/27514305-a01ce260-593b-11e7-849f-dbc572236494.png)

**Comment by getdls** [comment]
Noticed that Xenogear is missing grass, possible related

**Comment by YeisonVelez11** [comment]
@slashiee @Valkirie @getdls I am getting this  problem:  http://i.imgur.com/sqOmQ6i.jpg I am using the ultimate version, how can fix it? this is my configuration for get more fps:

http://i.imgur.com/CfwhO44.jpg

withouth configuration I get 40-45 fps, I have core i7 8 ram 2gb nvidia 610m. After of use this configuration I get 60 fps but the models disappear.


thanks

**Comment by slashiee** [comment]
go back to version 1.8.0

**Comment by slashiee** [comment]
![image](https://user-images.githubusercontent.com/15317421/28245173-628d12be-69b5-11e7-837a-673a1846728a.png)
![image](https://user-images.githubusercontent.com/15317421/28245174-661ba36e-69b5-11e7-935e-6b189f63d80d.png)

**Comment by slashiee** [comment]
Seems like also affects higher resolutions, as indicated by #69

**Comment by slashiee** [comment]
Closing because I honestly prefer less issues than more, plus it's mainly not a graphic pack issue.
