### ISSUE TITLE
Zelda: Breath of the Wild - 4k missing effects/broken DoF

### ISSUE THREAD

**Issue by DaRkL3AD3R** [slashiee/cemu_graphic_packs#69]
Imgur album demonstrating some of the problems: http://imgur.com/a/BHfS1

First 2 pictures are taken at native resolution but with AARemoval, Contrasty and High Res Shadows all enabled. Remaining pictures are the same thing but with 2160p pack toggled on.

Depth of field is broken and renders everything dark/black.

Missing light corona effects completely during intro sequence.

Likely other bugs too that I'm not made aware of yet. Only visible with higher resolution packs.

**Comment by slashiee** [comment]
Another 1.8.1 issue?

**Comment by DaRkL3AD3R** [comment]
Sadly no, I've had this issue basically from the get go. I can't think of a single point in time, from 1.7.4 to 1.8.1 where this issue did not happen for me. It's always been there.

**Comment by slashiee** [comment]
Oh. I have no clue what's causing this issue then. Guess people don't care that much to report it

**Comment by slashiee** [comment]
In that case, might as well reopen the BotW issue again. ugh. #38
