### ISSUE TITLE
Captain Toad: Treasure Tracker only listed

### ISSUE THREAD

**Issue by masvil** [slashiee/cemu_graphic_packs#7]
Captain Toad: Treasure Tracker is in Supported Games list but there is no Graphic Pack available.

**Comment by Darkemaste** [comment]
It's currently merged with Super Mario 3D World, (many issues/fixes apply to both) if you scroll down when selecting a graphic pack in Cemu you will see "Super Mario 3D World + Captain Toad: Treasure Tracker".

**Comment by masvil** [comment]
Good, thank you.
It should be nice to improve repository accessibility being more clear about available titles. Currently no one can know "nested" Graphic Packs stuff without a reference in the dir name.

**Comment by slashiee** [comment]
Just like what @Darkemaste said, it's combined with 3D World. I currently have it combined in terms of similar engines, or similar ways on how the games are built. I can see it being confusing, though.
