### ISSUE TITLE
UW graphic_pack patches don´t work right.

### ISSUE THREAD

**Issue by LoneGermanWanderer** [slashiee/cemu_graphic_packs#74]
Cemu 1.8.2b + CemuHook 0.5.3.1 + Win10x64
i7 7700K@4.5GHz + 1060gtx6GB + 32GB sysRAM

The SuperMario3DWorld_1080p_UW patch don´t work with my copy of 
Super Mario 3D World (Cache/SaveDirNr: 7bba927a, GameID: ARDP01).

The MK8_1080pUW patch have the wrong aspect ratio in Multiplayer.
![mariokart](https://user-images.githubusercontent.com/30589348/28775279-64439d38-75f1-11e7-8ee1-a72dc94d4033.jpg)

**Comment by slashiee** [comment]
Super Mario 3D World might not be the same RPX for all regions, causing it to not work for you.

Nothing can be really done about Mario Kart 8 though I believe, because I don't think there's a way to detect that it's multiplayer in patches.txt

**Comment by Xalphenos** [comment]
Looking in to sm3dw right now.

**Comment by LoneGermanWanderer** [comment]
Cool thx^^
i have found a temporary solution for the mario kart multiplayer.
![mariokart2](https://user-images.githubusercontent.com/30589348/28798313-67d8cdf8-7644-11e7-95f4-a66504eb3802.jpg)

**Comment by Xalphenos** [comment]
For now change the modulematches line to "moduleMatches = 0xD2308838" for sm3dw.  Codes the same but the module checksum is different.  Got to test JP, and all the captain toads before adding a new patches.txt.
