### ISSUE TITLE
The Legend of Zelda: Breath of the Wild - AARemoval in inventory screen

### ISSUE THREAD

**Issue by alexkiri** [slashiee/cemu_graphic_packs#81]
When using the 4k and AARemoval pack, the inventory screen still shows broken antialiasing
I might have found a solution for it. Let me know if this doesn't only happen for me, and I'll do a pull request
Here are some examples.
![aabrokendetail](https://user-images.githubusercontent.com/6061770/30722895-4d8e0b36-9f3c-11e7-9f47-aa390ca123ee.png)
![aafixeddetail](https://user-images.githubusercontent.com/6061770/30722899-5218a35a-9f3c-11e7-92da-0dad149fe669.png)
Cropped from 4k, resized 2x with no filter, for the love of pixels

**Comment by slashiee** [comment]
Curious as to why you didn't do the pull request in the first place. Either way, the screenshots look good, and ofc several people from #botw_discussion should test this pack.

**Comment by alexkiri** [comment]
It might sound stupid, but this is the first time I'm using github. I've used git a lost, but not github, so I had no idea what a fork is. Now, I do!

**Comment by slashiee** [comment]
Alright! I'll move your description there.
