### ISSUE TITLE
Double clicking left hand side doesn't work

### ISSUE THREAD

**Issue by AppleT1ny** [slashiee/cemu_graphic_packs#85]
As in the title, double clicking the left hand side doesn't start the game anymore. When clicking right hand side and then "start" the game starts properly.

![unbenannt](https://user-images.githubusercontent.com/24819763/30787188-a59c998e-a183-11e7-96b8-cb25ab82b86f.PNG)

**Comment by slashiee** [comment]
https://github.com/RedDuckss/CemUI
